.github/workflows/static-analysis-pr.yml
README.md
appveyor.yml

Cloning git submodules without history saves up almost 1,2GB storage space (~700MB vs 1,9GB on NTFS) and reduces the duration and size of the download.
This is the default behavior of [GitHub Checkout Action](https://github.com/actions/checkout#:~:text=Only%20a%20single%20commit%20is%20fetched%20by%20default%2C%20for%20the%20ref/SHA%20that%20triggered%20the%20workflow.) when submodules cloning is enabled. There's a mistakenly added extra step in `static-analysis-pr.yml` which does the same thing one more time, slowing the pipeline.

Clone submodules shallowly

---

tasks/mpi/ivanov_m_integration_trapezoid/func_tests/main.cpp
tasks/mpi/ivanov_m_integration_trapezoid/include/ops_mpi.hpp
tasks/mpi/ivanov_m_integration_trapezoid/perf_tests/main.cpp
tasks/mpi/ivanov_m_integration_trapezoid/src/ops_mpi.cpp
tasks/seq/ivanov_m_integration_trapezoid/func_tests/main.cpp
tasks/seq/ivanov_m_integration_trapezoid/include/ops_seq.hpp
tasks/seq/ivanov_m_integration_trapezoid/perf_tests/main.cpp
tasks/seq/ivanov_m_integration_trapezoid/src/ops_seq.cpp

**Алгоритм интегрирования методом трапеций подразумевает:**
1) Разделение отрезка интегрирования на N равных частей
2) Получение значения функции в точках начала и конца i-ой части отрезка
3) Определение площади трапеции, образованной 4-мя точками, полученными в шаге 1 и 2
4) Суммирование площадей трапеций
**Последовательная версия:** поиск длины i-ого отрезка (`step`), последовательный проход по каждому отрезку длины `step` в заданном диапазоне интегрирования (от a до b) и получение площадей трапеций. Так как площадь i-ой трапеции равна `(h_i + h_(i + 1)) / 2 * step`, то можно вынести за пределы цикла, суммирующего площади трапеций, операции: (`/ 2 * step`)
**Параллельная версия:** получение входных параметров для 0-ого процесса, расчёт step, передача через `broadcast` во все остальные …

Иванов Михаил. Задача 1. Вариант 20. Интегрирование – метод трапеций.

---

tasks/mpi/tyurin_m_count_sentences_in_string/func_tests/main.cpp
tasks/mpi/tyurin_m_count_sentences_in_string/include/ops_mpi.hpp
tasks/mpi/tyurin_m_count_sentences_in_string/perf_tests/main.cpp
tasks/mpi/tyurin_m_count_sentences_in_string/src/ops_mpi.cpp
tasks/seq/tyurin_m_count_sentences_in_string/func_tests/main.cpp
tasks/seq/tyurin_m_count_sentences_in_string/include/ops_seq.hpp
tasks/seq/tyurin_m_count_sentences_in_string/perf_tests/main.cpp
tasks/seq/tyurin_m_count_sentences_in_string/src/ops_seq.cpp

Последовательная версия: На вход подается строка. Последовательный алгоритм проходит по строке и считает количество предложений, определяя их окончания по символам точки, восклицательного или вопросительного знака. Результатом является целое число — общее количество предложений в строке.
Параллельная версия (MPI): Строка равномерно делится между всеми процессами с использованием MPI broadcast. Каждый процесс подсчитывает предложения в своей части строки, а затем результаты объединяются с помощью MPI reduce. Итоговый результат — общее количество предложений.

Тюрин Михаил. Задача 1. Вариант 25. Подсчет числа предложений в строке.

---

tasks/mpi/vasilev_s_nearest_neighbor_elements/func_tests/main.cpp
tasks/mpi/vasilev_s_nearest_neighbor_elements/include/ops_mpi.hpp
tasks/mpi/vasilev_s_nearest_neighbor_elements/perf_tests/main.cpp
tasks/mpi/vasilev_s_nearest_neighbor_elements/src/ops_mpi.cpp
tasks/seq/vasilev_s_nearest_neighbor_elements/func_tests/main.cpp
tasks/seq/vasilev_s_nearest_neighbor_elements/include/ops_seq.hpp
tasks/seq/vasilev_s_nearest_neighbor_elements/perf_tests/main.cpp
tasks/seq/vasilev_s_nearest_neighbor_elements/src/ops_seq.cpp

- **Класс**: `FindClosestNeighborsSequential`
- **Описание**: Последовательная версия алгоритма находит минимальную разницу между соседними элементами вектора. 
- **Алгоритм**:
- В методе `pre_processing` вектор входных данных инициализируется из `taskData`, задается начальное значение `min_diff_` как максимально возможное, а также начальные индексы `index1_` и `index2_` устанавливаются в `-1`.
- В методе `run` осуществляется проход по всем парам соседних элементов, вычисляется разница, и, если она меньше текущей минимальной разницы, обновляются `min_diff_`, `index1_` и `index2_`.
- Метод `post_processing` записывает результат (минимальная разница и индексы) в выходной буфер.
- **Результат**: Алгоритм возвращает минимальную разницу между соседними элементами и соответствующие индексы. …

Васильев Сергей. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.

---

tasks/mpi/laganina_e_sum_values_by_columns_matrix/func_tests/main.cpp
tasks/mpi/laganina_e_sum_values_by_columns_matrix/include/ops_mpi.hpp
tasks/mpi/laganina_e_sum_values_by_columns_matrix/perf_tests/main.cpp
tasks/mpi/laganina_e_sum_values_by_columns_matrix/src/ops_mpi.cpp
tasks/seq/laganina_e_sum_values_by_columns_matrix/func_tests/main.cpp
tasks/seq/laganina_e_sum_values_by_columns_matrix/include/ops_seq.hpp
tasks/seq/laganina_e_sum_values_by_columns_matrix/perf_tests/main.cpp
tasks/seq/laganina_e_sum_values_by_columns_matrix/src/ops_seq.cpp

Последовательная версия: Мы проходим по матрице в два этапа: внешний цикл проходит по столбцам, а вложенный — по строкам. Результаты суммирования записываются в массив, длина которого равна количеству столбцов.
Параллельная версия: Мы разбиваем матрицу на части в зависимости от количества столбцов и процессов, определяя, сколько столбцов будет обрабатываться каждым процессом, а также индекс последнего обрабатываемого столбца. Суммирование значений осуществляется с использованием функции, аналогичной той, что применялась в последовательной реализации.

Лаганина Елена. Задача 1. Вариант 12. Сумма значений матрицы по столбцам

---

tasks/mpi/malyshev_a_sum_rows_matrix/func_tests/main.cpp
tasks/mpi/malyshev_a_sum_rows_matrix/include/ops_mpi.hpp
tasks/mpi/malyshev_a_sum_rows_matrix/perf_tests/main.cpp
tasks/mpi/malyshev_a_sum_rows_matrix/src/ops_mpi.cpp
tasks/seq/malyshev_a_sum_rows_matrix/func_tests/main.cpp
tasks/seq/malyshev_a_sum_rows_matrix/include/ops_seq.hpp
tasks/seq/malyshev_a_sum_rows_matrix/perf_tests/main.cpp
tasks/seq/malyshev_a_sum_rows_matrix/src/ops_seq.cpp

Seq: 
1. Данные валидируются (количество строк матрицы должно совпадать с размером выхода)
2. Данные построчно копируются из 'taskData'
3. Строки суммируются с помощью `std::accumulate`
4. Результат копируется в `taskData`
MPI: 
1. Данные нулевого процесса валидируются (количество строк матрицы должно совпадать с размером выхода)
2. Данные нулевого процесса построчно копируются из 'taskData'
3. Вычисляются размеры передаваемых данных процессам. Неделящийся остаток будет ~отправлен последнему процессу~ равномерно распределен между процессами начиная с конца. (upd by [0a6e48c](https://github.com/learning-process/ppc-2024-autumn/pull/201/commits/0a6e48c6a0e7fbd8e607299de1f17dae3d091645)) 
4. Данные рассылаются с помощью `scatterv`
5. Локальные строки суммируются с помощью `std::accumulate` …

Малышев Антон. Задача 1. Вариант 11. Сумма значений по строкам матрицы

---

tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
tasks/mpi/gordeva_t_max_val_of_column_matrix/include/ops_mpi.hpp
tasks/mpi/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
tasks/seq/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
tasks/seq/gordeva_t_max_val_of_column_matrix/include/ops_seq.hpp
tasks/seq/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp

Reverts learning-process/ppc-2024-autumn#271
Ошибка заключалась в том, что отличались максимальное значение вычисленное и максимальное значение проверочное в perf тестах. Ошибка исправлена: измене диапазон значений элементов, теперь тесты работают корректно
**Описание программы.**
Программа вычисляет максимальное значение в каждом столбце матрицы.
_-Последовательная задача:_
изначально максимальное значение равно первому элементу текущего столбца; происходит сравнение текущего максимального значения с каждым элементом из соответствующего столбца - если значение элемента больше, то оно становится максимальным значением
результат: вектор с максимальными значениями для каждого столбца
_-MPI задача:_
матрица разбивается на кол-во процессов
каждый процесс ищет максимум в каждом столбце своих …

Revert "Revert "Revert "Гордеева Таисия. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы"""

---

tasks/mpi/shulpin_monte_carlo_integration/func_tests/main.cpp
tasks/mpi/shulpin_monte_carlo_integration/include/monte_carlo_integral.hpp
tasks/mpi/shulpin_monte_carlo_integration/perf_tests/main.cpp
tasks/mpi/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
tasks/seq/shulpin_monte_carlo_integration/func_tests/main.cpp
tasks/seq/shulpin_monte_carlo_integration/include/monte_carlo_integral.hpp
tasks/seq/shulpin_monte_carlo_integration/perf_tests/main.cpp
tasks/seq/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp

**Описание ошибки**
Ошибка заключалась в том, что validation проверяет количество введенных параметров(a, b, N). В perf test было реализовано только добавления параметра N(для переменной inputs_count), из-за чего валидация постоянно проваливалась. Исправлено

Revert. Шульпин Илья. Задача 1. Вариант 21. Интегрирование методом Монте-Карло

---

tasks/mpi/zinoviev_a_sum_cols_matrix/func_tests/main.cpp
tasks/mpi/zinoviev_a_sum_cols_matrix/include/ops_mpi.hpp
tasks/mpi/zinoviev_a_sum_cols_matrix/perf_tests/main.cpp
tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
tasks/mpi/zinoviev_readers_and_writers/func_tests/main.cpp
tasks/mpi/zinoviev_readers_and_writers/include/ops_mpi.hpp
tasks/mpi/zinoviev_readers_and_writers/perf_tests/main.cpp
tasks/mpi/zinoviev_readers_and_writers/src/ops_mpi.cpp
tasks/seq/zinoviev_a_sum_cols_matrix/func_tests/main.cpp
tasks/seq/zinoviev_a_sum_cols_matrix/include/ops_seq.hpp
tasks/seq/zinoviev_a_sum_cols_matrix/perf_tests/main.cpp
tasks/seq/zinoviev_a_sum_cols_matrix/src/ops_seq.cpp
tasks/seq/zinoviev_readers_and_writers/func_tests/main.cpp
tasks/seq/zinoviev_readers_and_writers/include/ops_seq.hpp
tasks/seq/zinoviev_readers_and_writers/perf_tests/main.cpp
tasks/seq/zinoviev_readers_and_writers/src/ops_seq.cpp
tasks/stl/example/func_tests/main.cpp

Здесь представлены последовательная и параллельная реализации суммы значений по столбцам матрицы. **В последовательной** реализуем вложенный цикл, проходя по каждому столбцу матрицы, суммируя значения её элементов. Итоговые суммы помещаются в отдельный вектор. **В параллельной** распределяем столбцы матрицы в зависимости от числа доступных процессов. Определяем величину, которая обозначает количество столбцов, отведенных каждому процессу, а также индекс последнего обрабатываемого столбца для каждого процесса. Каждая группа столбцов суммируется с использованием функции, аналогичной той, что применяется в последовательной версии. Полученные результаты затем консолидируются в общий вектор.

Зиновьев Александр Задача 1 Вариант 12 Сумма значений по столбцам матрицы

---

tasks/mpi/korotin_e_my_scatter/func_tests/main.cpp
tasks/mpi/korotin_e_my_scatter/include/ops_mpi.hpp
tasks/mpi/korotin_e_my_scatter/perf_tests/main.cpp
tasks/mpi/korotin_e_my_scatter/src/ops_mpi.cpp
tasks/mpi/korotin_e_scatter/func_tests/main.cpp
tasks/mpi/korotin_e_scatter/include/ops_mpi.hpp
tasks/mpi/korotin_e_scatter/perf_tests/main.cpp
tasks/mpi/korotin_e_scatter/src/ops_mpi.cpp

Задача: Нахождение максимального элемента марицы.
seq: Присваемваем max значение первого элемента матрицы, затем проходимся по всем остальным элементам и сравниваем с max, если окажется, что элемент > max, присваиваем max значение этого элемента. По прохождении по всем элемнтам матрицы в max будет лежать максимальный элемента всей матрицы.
mpi: разделяем всю матрицу на m частей (где m - количество процессов), в случае, если окажется, что количество элементов матрицы не делится нацело на m, все "лишние" элементы отдаются корневому(тому, у которого изначально хранилась матрица) процессу. После чего все процессы выполняют алгоритм, описанный в seq, когда все процессы завершают работу над своей частью матрицы, выбираем максимальный из всех элементов, полученных каждым процессом.
Реализация …

Коротин Егор. Задача 2. Вариант 8. Реализация Scatter

---

tasks/mpi/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
tasks/mpi/khovansky_d_ribbon_vertical_scheme/include/ops_mpi.hpp
tasks/mpi/khovansky_d_ribbon_vertical_scheme/perf_tests/main.cpp
tasks/mpi/khovansky_d_ribbon_vertical_scheme/src/ops_mpi.cpp
tasks/seq/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
tasks/seq/khovansky_d_ribbon_vertical_scheme/include/ops_seq.hpp
tasks/seq/khovansky_d_ribbon_vertical_scheme/perf_tests/main.cpp
tasks/seq/khovansky_d_ribbon_vertical_scheme/src/ops_seq.cpp

Задача умножения матрицы на вектор заключается в том, чтобы вычислить результирующий вектор, каждый элемент которого представляет собой скалярное произведение строки матрицы на входной вектор. При использовании ленточной вертикальной схемы элементы матрицы распределяются между процессами по колонкам. Алгоритм предполагает распределение данных и вычислений для повышения производительности.
1. Инициализация данных:
Матрица и вектор загружаются в память из входных данных. Проверяется согласованность размеров.
2. Вычисление результата:
Выполняется обход строк матрицы. Для каждой строки происходит умножение её элементов на соответствующий элемент входного вектора и суммирование результата.
3. Сохранение результата:
Результирующий вектор сохраняется и …

Хованский Дмитрий. Задача 2. Вариант 16. Ленточная вертикальная схема.

---

tasks/mpi/khokhlov_a_iterative_seidel_method/func_tests/main_khokhlov.cpp
tasks/mpi/khokhlov_a_iterative_seidel_method/include/ops_mpi_khokhlov.hpp
tasks/mpi/khokhlov_a_iterative_seidel_method/perf_tests/main_khokhlov.cpp
tasks/mpi/khokhlov_a_iterative_seidel_method/src/ops_mpi_khokhlov.cpp
tasks/seq/khokhlov_a_iterative_seidel_method/func_tests/main_khokhlov.cpp
tasks/seq/khokhlov_a_iterative_seidel_method/include/ops_seq_khokhlov.hpp
tasks/seq/khokhlov_a_iterative_seidel_method/perf_tests/main_khokhlov.cpp
tasks/seq/khokhlov_a_iterative_seidel_method/src/ops_seq_khokhlov.cpp

Задача: решить систему линейных алгебраических уравнений итеративным методом Зейделя.
Последовательная версия: на вход подается вещественная матрица коэффициентов А размером n на n и вектор b размером n, требуется найти вектор решений x размером n.  Метод Зейделя выполняет итерации, обновляя значения 
𝑥[𝑖] на основе текущего состояния других 𝑥[𝑗].
Условие сходимости: проверяется норма разности текущего и предыдущего решений 
∣∣𝑥(𝑘+1)−𝑥𝑘∣∣<𝜀.
формула обновления компоненты xi:
xi^(k+1) = 1/Aii(bi −(j=0,j!=i)(n-1)∑Aijxj^(k+1))
Параллельная версия: матрица коэффициентов А разбивается на локальные матрицы размера n*local_n, где local_n равняется делением нацело числа строк на число процессов, остаток записывается в последний процесс, вектор b также разбивается на локальные вектора размера …

Хохлов Андрей. Задача 2. Вариант 23. Итеративные методы (Зейделя).

---

tasks/mpi/kondratev_ya_radix_sort_batcher_merge/func_tests/main.cpp
tasks/mpi/kondratev_ya_radix_sort_batcher_merge/include/ops_mpi.hpp
tasks/mpi/kondratev_ya_radix_sort_batcher_merge/perf_tests/main.cpp
tasks/mpi/kondratev_ya_radix_sort_batcher_merge/src/ops_mpi.cpp
tasks/seq/kondratev_ya_radix_sort_batcher_merge/func_tests/main.cpp
tasks/seq/kondratev_ya_radix_sort_batcher_merge/include/ops_seq.hpp
tasks/seq/kondratev_ya_radix_sort_batcher_merge/perf_tests/main.cpp
tasks/seq/kondratev_ya_radix_sort_batcher_merge/src/ops_seq.cpp

Из-за [особенностей хранния double](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#IEEE_754_double-precision_binary_floating-point_format:_binary64)  сортировка происходит в три этапа:
- инвертирование знакового бита чтобы отрицательные числа стали меньше положительных
- сортировка
- восстановление знакового бита
Сортировка происходит в 8 шагов по 8 бит (1 байт)
- Массив разделяется по процессам
- Процессы сортируют локальные данные поразрядной сортировкой
- Цикл выполняется world.size() раз (по количеству процессов)
- На четных шагах (step % 2 == 0): Четные процессы (world.rank() % 2 == 0) обмениваются данными со следующим процессом. Нечетные процессы обмениваются данными с предыдущим процессом
- На нечетных шагах (step % 2 == 1): Нечетные процессы обмениваются …

Кондратьев Ярослав. Задача 3. Вариант 21. Поразрядная сортировка для вещественных чисел (тип double)  с четно-нечетным слиянием Бэтчера.

---

tasks/mpi/gnitienko_k_contrast_enhancement/func_tests/main.cpp
tasks/mpi/gnitienko_k_contrast_enhancement/include/ops_mpi.hpp
tasks/mpi/gnitienko_k_contrast_enhancement/perf_tests/main.cpp
tasks/mpi/gnitienko_k_contrast_enhancement/src/ops_mpi.cpp
tasks/seq/gnitienko_k_contrast_enhancement/func_tests/main.cpp
tasks/seq/gnitienko_k_contrast_enhancement/include/ops_seq.hpp
tasks/seq/gnitienko_k_contrast_enhancement/perf_tests/main.cpp
tasks/seq/gnitienko_k_contrast_enhancement/src/ops_seq.cpp

Была ревертнута не та лабораторная, в которой наблюдался баг с gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105651

Revert "Revert "Гнитиенко Кирилл. Задача 2. Вариант 27. Повышение контраста изображения""

---

tasks/mpi/krylov_m_crs_mmul/func_tests/main.cpp
tasks/mpi/krylov_m_crs_mmul/func_tests/matrix.cpp
tasks/mpi/krylov_m_crs_mmul/include/matrix.hpp
tasks/mpi/krylov_m_crs_mmul/include/smmul_mpi.hpp
tasks/mpi/krylov_m_crs_mmul/perf_tests/main.cpp
tasks/mpi/krylov_m_crs_mmul/src/smmul_mpi.cpp
tasks/seq/krylov_m_crs_mmul/func_tests/main.cpp
tasks/seq/krylov_m_crs_mmul/func_tests/matrix.cpp
tasks/seq/krylov_m_crs_mmul/include/matrix.hpp
tasks/seq/krylov_m_crs_mmul/include/smmul_seq.hpp
tasks/seq/krylov_m_crs_mmul/perf_tests/main.cpp
tasks/seq/krylov_m_crs_mmul/src/smmul_seq.cpp

**Описание последовательной задачи.** На вход задачи подаются две матрицы, представленные в формате CSR. Правая матрица транспонируется для организации доступа по столбцам, затем на нее умножается левая матрица.
**Описание MPI задачи.** Реализуется схема, напоминающая обобщенную ленточную схему с разбиением только левой матрицы, правая матрица рассылается всем процессам в коммуникаторе. Для оптимизации рассылки правой матрицы используются расширенные возможности `boost::serialization` - введен дополнительный класс, представляющий фрагмент CSR-матрицы, организующий доступ к членам по невладеющим ссылкам (точнее говоря, с помощью `std::span`, являющегося невладеющей оберткой над указателем на непрерывный блок памяти и размером этого блока). В классе спрятана структура, содержащая владеющие …

Крылов Михаил. Задача 3. Вариант 4. Умножение разреженных матриц. Элементы типа double.  Формат хранения матрицы – строковый (CRS).

---

tasks/mpi/kovalev_k_num_of_orderly_violations/func_tests/main.cpp
tasks/mpi/kovalev_k_num_of_orderly_violations/include/header.hpp
tasks/mpi/kovalev_k_num_of_orderly_violations/perf_tests/main.cpp
tasks/mpi/kovalev_k_num_of_orderly_violations/src/sourse.cpp

Reverts learning-process/ppc-2024-autumn#604
Проблема, предположительно, была в рассинхроне процессов (гипотеза подтверждается тем, что в learning-process/ppc-2024-autumn#564 количество недостающих до правильного ответа элементов как раз и было равно количеству, которое 1 процесс должен был подсчитать). MPI_Barrier() добавлен, неоднократные запуски показали, что проблема решена. Код тривиальный, что ещё может ломаться - не знаю. Допускаю также, что моя работа падала вследствие ошибки у другого студента

Fix "Revert "Ковалев Константин. Задача 1. Вариант 6. Нахождение числа нарушений упорядоченности соседних элементов вектора.""

---

tasks/mpi/sozonov_i_image_filtering_vertical_gaussian_3x3/func_tests/main.cpp
tasks/mpi/sozonov_i_image_filtering_vertical_gaussian_3x3/include/ops_mpi.hpp
tasks/mpi/sozonov_i_image_filtering_vertical_gaussian_3x3/perf_tests/main.cpp
tasks/mpi/sozonov_i_image_filtering_vertical_gaussian_3x3/src/ops_mpi.cpp
tasks/seq/sozonov_i_image_filtering_vertical_gaussian_3x3/func_tests/main.cpp
tasks/seq/sozonov_i_image_filtering_vertical_gaussian_3x3/include/ops_seq.hpp
tasks/seq/sozonov_i_image_filtering_vertical_gaussian_3x3/perf_tests/main.cpp
tasks/seq/sozonov_i_image_filtering_vertical_gaussian_3x3/src/ops_seq.cpp

Ядро Гаусса 3x3: 
К изображению добавляем нулевые края со всех сторон. Для каждого пикселя (кроме граничных) берется окно размером 3×3. Значения пикселей из этого окна умножаются на соответствующие коэффициенты ядра, и их сумма записывается в новый массив как фильтрованное значение пикселя. Это позволяет убрать шум, сохраняя детали изображения.
**Описание MPI задачи**
Столбцы изображения равномерно распределяются между процессами, включая дополнительные столбцы для учета соседей. Главный процесс отправляет каждому процессу его часть изображения. Каждый процесс выполняет свертку ядра Гаусса на своей части изображения. Все процессы отправляют обработанные данные главному процессу, который собирает итоговое изображение.

Созонов Илья. Задача 3. Вариант 27. Линейная фильтрация изображений (вертикальное разбиение). Ядро Гаусса 3x3.

---

tasks/mpi/kovalev_k_multidimensional_integrals_rectangle_method/func_tests/main.cpp
tasks/mpi/kovalev_k_multidimensional_integrals_rectangle_method/include/header.hpp
tasks/mpi/kovalev_k_multidimensional_integrals_rectangle_method/perf_tests/main.cpp
tasks/mpi/kovalev_k_multidimensional_integrals_rectangle_method/src/sourse.cpp
tasks/seq/kovalev_k_multidimensional_integrals_rectangle_method/func_tests/main.cpp
tasks/seq/kovalev_k_multidimensional_integrals_rectangle_method/include/header.hpp
tasks/seq/kovalev_k_multidimensional_integrals_rectangle_method/perf_tests/main.cpp
tasks/seq/kovalev_k_multidimensional_integrals_rectangle_method/src/sourse.cpp

Задача состоит в приближенном вычислении многомерного определённого интеграла от заданной функции. Используется многошаговая схема: для каждой взятой с вершины стека точки вычисляются следующие (точки следующей размерности, отстоющие друг от друга на шаг h). Точки кладутся на стек. Если точка с вершины стека содержит в себе координаты всех размерностей, то вычисляется значение функции в ней, умножается на шаг интегрирования h в степени размерности интеграла. Точка удаляется со стека. Алгоритм повторяется до тех пор пока стек не окажется пуст.
В параллельной версии используется свойство аддитивности интеграла по области: каждый из процессов вычисляет интеграл на своём отрезке, совокупность которых образует первую размерность исходного интеграла. Затем результаты со всех процессов …

Ковалев Константин. Задача 3. Вариант 7. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

---

tasks/mpi/borisov_s_crs_mul/func_tests/main.cpp
tasks/mpi/borisov_s_crs_mul/include/ops_mpi.hpp
tasks/mpi/borisov_s_crs_mul/perf_tests/main.cpp
tasks/mpi/borisov_s_crs_mul/src/ops_mpi.cpp
tasks/seq/borisov_s_crs_mul/func_tests/main.cpp
tasks/seq/borisov_s_crs_mul/include/ops_seq.hpp
tasks/seq/borisov_s_crs_mul/perf_tests/main.cpp
tasks/seq/borisov_s_crs_mul/src/ops_seq.cpp

Мной написана реализация умножения матриц в формате CRS с поддержкой двух версий: последовательной и параллельной с использованием MPI.
На вход подаются матрицы в стандартном (плотном) формате, которые преобразуются в CRS формат для оптимизации операций умножения и хранения. В последовательной версии матрица A в CRS формате по строкам умножается на матрицу B (также в CRS формате), а результаты сохраняются в CRS формате, что позволяет эффективно работать с разреженными данными и экономить память.
В MPI версии строки матрицы A равномерно распределяются между процессами, после чего каждый процесс выполняет умножение своих строк матрицы A на матрицу B. Процесс 0 отвечает за преобразование входных данных в CRS формат и их передачу другим процессам с использованием broadcast. После завершения …

Борисов Сергей. Задача 3. Вариант 4: Умножение разреженных матриц. Элементы типа double.  Формат хранения матрицы – строковый (CRS).

---

tasks/mpi/kozlova_e_radix_batcher_sort/func_tests/main.cpp
tasks/mpi/kozlova_e_radix_batcher_sort/include/ops_mpi.hpp
tasks/mpi/kozlova_e_radix_batcher_sort/perf_tests/main.cpp
tasks/mpi/kozlova_e_radix_batcher_sort/src/ops_mpi.cpp
tasks/seq/kozlova_e_radix_batcher_sort/func_tests/main.cpp
tasks/seq/kozlova_e_radix_batcher_sort/include/ops_seq.hpp
tasks/seq/kozlova_e_radix_batcher_sort/perf_tests/main.cpp
tasks/seq/kozlova_e_radix_batcher_sort/src/ops_seq.cpp

В классе реализована поразрядная сортировка для чисел с плавающей точкой типа double. Каждый элемент массива преобразуется в его 64-битное целочисленное представление, что позволяет работать с числами на уровне их битов. Для корректной сортировки отрицательных чисел старший бит (бит знака) инвертируется, чтобы все отрицательные числа были обработаны как положительные, не нарушая общей логики сортировки. Алгоритм выполняет сортировку, начиная с младшего бита и постепенно переходя к более старшим. На каждом шаге происходит разделение данных на две группы в зависимости от значения текущего бита (0 или 1). После завершения сортировки по всем битам, 64-битные целые числа преобразуются обратно в значения типа double, и отрицательные числа восстанавливают своё исходное состояние.
С помощью …

Козлова Екатерина. Задача 3. Вариант 21. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.

---

tasks/mpi/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
tasks/mpi/somov_i_bitwise_sorting_batcher_merge/include/ops_mpi.hpp
tasks/mpi/somov_i_bitwise_sorting_batcher_merge/perf_tests/main.cpp
tasks/mpi/somov_i_bitwise_sorting_batcher_merge/src/ops_mpi.cpp
tasks/seq/somov_i_bitwise_sorting_batcher_merge/func_tests/main.cpp
tasks/seq/somov_i_bitwise_sorting_batcher_merge/include/ops_seq.hpp
tasks/seq/somov_i_bitwise_sorting_batcher_merge/perf_tests/main.cpp
tasks/seq/somov_i_bitwise_sorting_batcher_merge/src/ops_seq.cpp

**1. SEQ (Последовательная версия):**
В последовательной версии алгоритма входной массив сортируется с использованием radix sort. Массив разбивается на положительные и отрицательные числа, которые преобразуются в целочисленное представление через reinterpret_cast и сортируются независимо друг от друга. Отрицательные числа инвертируются побитово перед сортировкой и восстанавливаются после. Затем два отсортированных массива объединяются, начиная с отрицательных чисел, обеспечивая корректный итоговый порядок.
**2. MPI (Параллельная версия):**
В параллельной реализации алгоритма массив данных распределяется между процессами с использованием MPI scatterv, при этом каждый процесс получает свою часть данных для обработки. На каждом процессе выполняется локальная сортировка с использованием radix …

Сомов Иван. Задача №3. Вариант 21. Поразрядная сортировка для вещественных чисел (тип double) с чётно-нечётным слиянием Бэтчера

---

tasks/mpi/bessonov_e_integration_monte_carlo/func_tests/main.cpp
tasks/mpi/bessonov_e_integration_monte_carlo/include/ops_mpi.hpp
tasks/mpi/bessonov_e_integration_monte_carlo/perf_tests/main.cpp
tasks/mpi/bessonov_e_integration_monte_carlo/src/ops_mpi.cpp
tasks/seq/bessonov_e_integration_monte_carlo/func_tests/main.cpp
tasks/seq/bessonov_e_integration_monte_carlo/include/ops_seq.hpp
tasks/seq/bessonov_e_integration_monte_carlo/perf_tests/main.cpp
tasks/seq/bessonov_e_integration_monte_carlo/src/ops_seq.cpp

SEQ:
Метод pre_processing() извлекает границы интегрирования a и b, а также количество случайных точек num_points из входных данных.
Интегрирование:
Метод run() выполняет следующие действия:
Инициализирует генератор случайных чисел.
Генерирует num_points случайных значений x в диапазоне [a, b].
Для каждого x вычисляет значение функции и суммирует результаты.
Вычисляет итоговый результат интегрирования как произведение диапазона интегрирования (b - a) на среднее значение вычисленных функций.
MPI
Метод run() выполняет следующие действия на каждом процессе:
Определяет количество точек num_points_for_process, которое необходимо обработать текущему процессу, учитывая общее количество процессов и возможный остаток.
Генерирует num_points_for_process случайных значений x в диапазоне [a, b]. …

Revert "Revert "Бессонов Егор. Задача 1. Вариант 21. Интегрирование – метод Монте-Карло.""

---

tasks/mpi/vavilov_v_bellman_ford/func_tests/main.cpp
tasks/mpi/vavilov_v_bellman_ford/include/ops_mpi.hpp
tasks/mpi/vavilov_v_bellman_ford/perf_tests/main.cpp
tasks/mpi/vavilov_v_bellman_ford/src/ops_mpi.cpp
tasks/seq/vavilov_v_bellman_ford/func_tests/main.cpp
tasks/seq/vavilov_v_bellman_ford/include/ops_seq.hpp
tasks/seq/vavilov_v_bellman_ford/perf_tests/main.cpp
tasks/seq/vavilov_v_bellman_ford/src/ops_seq.cpp

Алгоритм Беллмана-Форда широко используется для поиска кратчайших путей от одной вершины до всех остальных в графе с заданными весами рёбер. Основное преимущество алгоритма заключается в его способности корректно обрабатывать графы с отрицательными весами рёбер. 
Дан направленный граф $G = (V, E)$, где $V$ - множество вершин, $E$ - множество рёбер с весами $w(u, v)$. Требуется найти кратчайшие пути от заданной вершины $s \in V$ до всех остальных вершин графа.
Было реализовано 2 последовательной версии. Первая хранит в массиве исходящую вершину, входящую вершину и вес. Вторая версия заключается в реализации CRS графа. Поскольку использование CRS графа эффективнее, то параллельная версия была реализована с CRS хранением.
Схема последовательного алгоритма:
1) Инициализировать расстояния: …

Вавилов Виталий. Задача 3. Вариант 23. Алгоритм Беллмана-Форда

---

tasks/mpi/durynichev_d_radix_batcher/func_tests/main.cpp
tasks/mpi/durynichev_d_radix_batcher/include/ops_mpi.hpp
tasks/mpi/durynichev_d_radix_batcher/perf_tests/main.cpp
tasks/mpi/durynichev_d_radix_batcher/src/ops_mpi.cpp
tasks/seq/durynichev_d_radix_batcher/func_tests/main.cpp
tasks/seq/durynichev_d_radix_batcher/include/ops_seq.hpp
tasks/seq/durynichev_d_radix_batcher/perf_tests/main.cpp
tasks/seq/durynichev_d_radix_batcher/src/ops_seq.cpp

Алгоритм поразрядной сортировки для вещественных чисел типа double с использованием четно-нечетного слияния Бэтчера работает следующим образом: данные равномерно распределяются между процессами с помощью boost::mpi::scatter, затем происходит обмен элементами и их локальная сортировка согласно алгоритму Бэтчера. После этого отсортированные части объединяются в итоговый отсортированный массив с помощью boost::mpi::gather.

Дурыничев Дмитрий. Задача 3. Вариант 21. "Поразрядная сортировка для вещественных чисел (тип double)  с четно-нечетным слиянием Бэтчера."

---

tasks/mpi/korablev_v_jacobi_method/perf_tests/main.cpp
tasks/seq/korablev_v_jacobi_method/perf_tests/main.cpp

Выяснили, что для корректного запуска скрипта названия perf тестов внутри директорий mpi и seq должны называться по-разному, иначе запуск обвалится. Коммит на опережение

[FIX PERF TESTS] Кораблев Владлен. Задача 2. Вариант 22. Итеративные методы (Якоби)

---

tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/perf_tests/main.cpp
tasks/seq/shvedova_v_matrix_mult_horizontal_a_vertical_b_seq/perf_tests/main.cpp

Исправлен размер матрицы для корректного времени прохождения (теперь все в окрестности секунд. В seq версии тоже был изменен размер, так как была вероятность падения из-за слишком долгого прохождения. Теперь все корректно.

[FIX PERF] Шведова Виталина. Задача 2. Вариант 18. Ленточная горизонтальная схема А, вертикальное В

---

tasks/mpi/suvorov_d_shell_with_ord_merge/func_tests/main.cpp
tasks/mpi/suvorov_d_shell_with_ord_merge/include/ops_mpi.hpp
tasks/mpi/suvorov_d_shell_with_ord_merge/perf_tests/main.cpp
tasks/mpi/suvorov_d_shell_with_ord_merge/src/ops_mpi.cpp
tasks/seq/suvorov_d_shell_with_ord_merge/func_tests/main.cpp
tasks/seq/suvorov_d_shell_with_ord_merge/include/ops_seq.hpp
tasks/seq/suvorov_d_shell_with_ord_merge/perf_tests/main.cpp
tasks/seq/suvorov_d_shell_with_ord_merge/src/ops_seq.cpp

Задача "Сортировка Шелла с простым слиянием".
Описание последовательного решения задачи:
В последовательной версией в run() для входного вектора с данными выполняется функция shell_sort, которая реализует сортировку Шелла.
Для проверки корректности были реализованы тесты с следующими вариантами векторов данных:
1. Вектор уникальных элементов.
2. Вектор с повторяющимися элементами.
3. Вектор из 1 элемента.
4. Вектор с отрицательными числами.
Описание решения задачи с использованием MPI:
В параллельном решении входной вектор разбивается на части, части рассылаются вызовом scatterv каждому процессу. Каждый процесс для своей локальной части выполняет сортировку Шелла. Затем все части отправляются с помощью gatherv в 0 процесс. Но в результате все отсортированные части просто устанавливаются …

Суворов Дмитрий. Задача 3. Вариант 16. Сортировка Шелла с простым слиянием.

---

tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/func_tests/main.cpp
tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/include/ops_mpi.hpp
tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/perf_tests/main.cpp
tasks/mpi/lysov_i_matrix_multiplication_Fox_algorithm/src/ops_mpi.cpp
tasks/seq/lysov_i_matrix_multiplication_Fox_algorithm/func_tests/main.cpp
tasks/seq/lysov_i_matrix_multiplication_Fox_algorithm/include/ops_seq.hpp
tasks/seq/lysov_i_matrix_multiplication_Fox_algorithm/perf_tests/main.cpp
tasks/seq/lysov_i_matrix_multiplication_Fox_algorithm/src/ops_seq.cpp

seq: стандартное умножение матриц
mpi:
<b>Для работы алгоритма требуется \( q^2 \) процессов. Если число доступных процессов больше, лишние процессы остаются неактивными</b>
Алгоритм:
1. **Разделение матриц:**
- Матрицы \( A \) и \( B \) делятся на блоки размером K х K.
2. **Параллельные вычисления:**
- Каждый процесс обрабатывает назначенные ему блоки матриц \( A \) и \( B \).
- На каждом шаге:
- Блоки \( A \) передаются по строкам решётки процессов.
- Процессы умножают переданный блок \( A \) на локальный блок \( B \).
- Блоки \( B \) циклически передаются по столбцам.
3. **Сбор результата:**
- Локальные результаты процессов собираются для формирования итоговой матрицы \( C \).

Лысов Иван. Задача 3. Вариант 2. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Фокса.

---

tasks/mpi/rezantseva_a_rectangle_method/func_tests/main_rez_a.cpp
tasks/mpi/rezantseva_a_rectangle_method/include/ops_mpi_rez_a.hpp
tasks/mpi/rezantseva_a_rectangle_method/perf_tests/main_rez_a.cpp
tasks/mpi/rezantseva_a_rectangle_method/src/ops_mpi_rez_a.cpp
tasks/seq/rezantseva_a_rectangle_method/func_tests/main_rez_a.cpp
tasks/seq/rezantseva_a_rectangle_method/include/ops_seq_rez_a.hpp
tasks/seq/rezantseva_a_rectangle_method/perf_tests/main_rez_a.cpp
tasks/seq/rezantseva_a_rectangle_method/src/ops_seq_rez_a.cpp

**Вычисление многомерных интегралов методом прямоугольников (метод Римана)**
Разбиваем область интегрирования на подотрезки, в которых вычисляем значения функции в центрах этих подотрезков и суммируем площади прямоугольников, чтобы получить приближенную площадь под кривой.
Каждый процесс вычисляет свою часть интеграла, обрабатывая определенное количество точек, и суммирует результаты в локальную переменную. Результаты всех процессов объединяются с помощью reduce, для получения общего результата интегрирования.

Резанцева Анастасия. Задача 3. Вариант 7. Вычисление многомерных интегралов методом прямоугольников.

---

tasks/mpi/plekhanov_d_allreduce_boost/func_tests/main.cpp
tasks/mpi/plekhanov_d_allreduce_boost/include/ops_mpi.hpp
tasks/mpi/plekhanov_d_allreduce_boost/perf_tests/main.cpp
tasks/mpi/plekhanov_d_allreduce_boost/src/ops_mpi.cpp
tasks/mpi/plekhanov_d_allreduce_mine/func_tests/main.cpp
tasks/mpi/plekhanov_d_allreduce_mine/include/ops_mpi.hpp
tasks/mpi/plekhanov_d_allreduce_mine/perf_tests/main.cpp
tasks/mpi/plekhanov_d_allreduce_mine/src/ops_mpi.cpp

https://github.com/learning-process/ppc-2024-autumn/pull/412 - Основной PR.  Был реверт, потому что один из тестов на одной итерации превысил максимальное допустимое значение по времени - 1.09 секунд, чтобы это пофиксить, был убран func тест на матрице размером 5000 5000. Также прошу пересмотреть баллы, потому что последний коммит через один день после дедлайна.
Последовательное решение
В последовательном подходе мы начинаем с того, что проходим по каждому столбцу матрицы и находим минимальное значение в каждом из них. Для этого мы инициализируем переменную, которая будет хранить текущее минимальное значение, и сравниваем её с каждым элементом столбца. Как только мы определили минимум для столбца, мы переходим к следующему этапу — подсчету количества элементов, которые больше найденного …

FIX REVERT Плеханов Даниил. Задача 2. Вариант 7. Реализация all_reduce.

---

tasks/mpi/gromov_a_convex_hull/func_tests/main.cpp
tasks/mpi/gromov_a_convex_hull/include/ops_mpi.hpp
tasks/mpi/gromov_a_convex_hull/perf_tests/main.cpp
tasks/mpi/gromov_a_convex_hull/src/ops_mpi.cpp
tasks/seq/gromov_a_convex_hull/func_tests/main.cpp
tasks/seq/gromov_a_convex_hull/include/ops_seq.hpp
tasks/seq/gromov_a_convex_hull/perf_tests/main.cpp
tasks/seq/gromov_a_convex_hull/src/ops_seq.cpp

На вход подается изображение в виде матрицы, где каждая ячейка может быть пикселем). 
Цель – выделить соединенные компоненты изображения и для каждой из них вычислить выпуклую оболочку.
**Этапы выполнения:**
- Маркировка компонентов:
Для каждого пикселя выполняется проход сверху вниз и слева направо для поиска соединенных областей.
Используются два прохода: первый присваивает уникальные метки, второй уточняет их, чтобы объединить связные компоненты.
- Построение выпуклой оболочки:
Для каждой выделенной компоненты применяется алгоритм Джарвиса для вычисления её выпуклой оболочки.
- Реконструкция изображения:
Полученные выпуклые оболочки интегрируются обратно в результирующую матрицу.
**Результат:**
На выходе создается новое изображение, в котором …

Громов Алексей. Задача 3. Вариант 32. Построение выпуклой оболочки для компонент бинарного изображения.

---

tasks/mpi/belov_a_radix_sort_with_batcher_mergesort/func_tests/main.cpp
tasks/mpi/belov_a_radix_sort_with_batcher_mergesort/include/ops_mpi.hpp
tasks/mpi/belov_a_radix_sort_with_batcher_mergesort/perf_tests/main.cpp
tasks/mpi/belov_a_radix_sort_with_batcher_mergesort/src/ops_mpi.cpp
tasks/seq/belov_a_radix_sort_with_batcher_mergesort/func_tests/main.cpp
tasks/seq/belov_a_radix_sort_with_batcher_mergesort/include/ops_seq.hpp
tasks/seq/belov_a_radix_sort_with_batcher_mergesort/perf_tests/main.cpp
tasks/seq/belov_a_radix_sort_with_batcher_mergesort/src/ops_seq.cpp

Последовательная реализация задачи включает только этап поразрядной сортировки (Radix Sort) для целых чисел.  
1. **Поразрядная сортировка (Radix Sort):**  
С помощью `std::max_element` получаем наибольший элемент массива для определения его разрядности, после чего выполняется сортировка подсчётом для каждого разряда. В качестве типа данных для целых чисел используется `bigint`, фактически представляющий собой `long long`. Это допущение сделано для предотвращения переполнения и расширения диапазона поддерживаемых значений, что позволяет работать с большими числами.  
2. **Особенности работы с отрицательными числами:**  
Отрицательные числа предварительно инвертируются и сортируются, а затем записываются в обратном порядке с восстановлением знака. Такой подход позволяет использовать единый …

Белов Артём. Задача 3. Вариант 19. Поразрядная сортировка для целых чисел с четно-нечетным слиянием Бэтчера..

---

tasks/mpi/khokhlov_a_iterative_seidel_method/func_tests/main_khokhlov.cpp
tasks/mpi/khokhlov_a_iterative_seidel_method/include/ops_mpi_khokhlov.hpp
tasks/mpi/khokhlov_a_iterative_seidel_method/perf_tests/main_khokhlov.cpp
tasks/mpi/khokhlov_a_iterative_seidel_method/src/ops_mpi_khokhlov.cpp
tasks/seq/khokhlov_a_iterative_seidel_method/func_tests/main_khokhlov.cpp
tasks/seq/khokhlov_a_iterative_seidel_method/include/ops_seq_khokhlov.hpp
tasks/seq/khokhlov_a_iterative_seidel_method/perf_tests/main_khokhlov.cpp
tasks/seq/khokhlov_a_iterative_seidel_method/src/ops_seq_khokhlov.cpp

Исправлен диапазон точности в тестах, из-за которого они падали.
Задача: решить систему линейных алгебраических уравнений итеративным методом Зейделя.
Последовательная версия: на вход подается вещественная матрица коэффициентов А размером n на n и вектор b размером n, требуется найти вектор решений x размером n. Метод Зейделя выполняет итерации, обновляя значения
𝑥[𝑖] на основе текущего состояния других 𝑥[𝑗].
Условие сходимости: проверяется норма разности текущего и предыдущего решений
∣∣𝑥(𝑘+1)−𝑥𝑘∣∣<𝜀.
формула обновления компоненты xi:
xi^(k+1) = 1/Aii(bi −(j=0,j!=i)(n-1)∑Aijxj^(k+1))
Параллельная версия: матрица коэффициентов А разбивается на локальные матрицы размера n*local_n, где local_n равняется делением нацело числа строк на число процессов, остаток записывается в последний …

REVERT Хохлов Андрей. Задача 2. Вариант 23. Итеративные методы (Зейделя).

---

tasks/mpi/kalyakina_a_trapezoidal_integration_mpi/func_tests/main.cpp
tasks/mpi/kalyakina_a_trapezoidal_integration_mpi/include/ops_mpi.hpp
tasks/mpi/kalyakina_a_trapezoidal_integration_mpi/perf_tests/main.cpp
tasks/mpi/kalyakina_a_trapezoidal_integration_mpi/src/ops_mpi.cpp
tasks/seq/kalyakina_a_trapezoidal_integration_seq/func_tests/main.cpp
tasks/seq/kalyakina_a_trapezoidal_integration_seq/include/ops_seq.hpp
tasks/seq/kalyakina_a_trapezoidal_integration_seq/perf_tests/main.cpp
tasks/seq/kalyakina_a_trapezoidal_integration_seq/src/ops_seq.cpp

Изменены параметры функциональных тестов: понижено количество шагов интегрирования для seq_func_tests для выполнения ограничения по времени. 
Данная реализация имеет одно слабое место: количество подсчетов значения функции, а именно чем больше шагов при интегрировании, тем дольше выполняется программа, несмотря на то, что в каждой точке функция считается ровно один раз, независимо от количества вхождений точки в сумму (это определяется расчетом коэффициента)

[Fix revert] Калякина Анастасия. Задача 3. Вариант 8. Вычисление многомерных интегралов с использованием многошаговой схемы (метод трапеций).
