- tasks/mpi/muhina_m_min_of_vector_elements/func_tests/main.cpp
- tasks/mpi/muhina_m_min_of_vector_elements/include/ops_mpi.hpp
- tasks/mpi/muhina_m_min_of_vector_elements/perf_tests/main.cpp
- tasks/mpi/muhina_m_min_of_vector_elements/src/ops_mpi.cpp
- tasks/seq/muhina_m_min_of_vector_elements/func_tests/main.cpp
- tasks/seq/muhina_m_min_of_vector_elements/include/ops_seq.hpp
- tasks/seq/muhina_m_min_of_vector_elements/perf_tests/main.cpp
- tasks/seq/muhina_m_min_of_vector_elements/src/ops_seq.cpp
Каждый элемент вектора, сравниваем со значением переменной, в которой хранится минимальное значение вектора. Если значение данного элемента вектора меньше чем значение переменной, то записываем значение данного элемента вектора в переменную.
Описание MPI задачи:
- Делится вектор на фрагменты (по количеству процессов).
- Процесс с рангом 0 распределяет фрагменты между процессами.
- Каждый процесс получает свой фрагмент (local_input_).
- Каждый процесс находит минимальное значение в своем фрагменте.
- Используется функция reduce с оператором minimum для сбора минимального значения из всех процессов.
- Результат записывается в переменную res на процессе с рангом 0.
- Процесс с рангом 0 записывает найденное минимальное значение в выходной буфер.
> Мухина Маргарита. Задача 1. Вариант 4.  Минимальное значение элементов вектора.

- tasks/mpi/sorokin_a_check_lexicographic_order_of_strings/src/ops_mpi.cpp
> Fix tests with number of processes: 3, 5, 7, 8

- tasks/mpi/kazunin_n_count_freq_a_char_in_string/func_tests/main.cpp
- tasks/mpi/kazunin_n_count_freq_a_char_in_string/include/ops_mpi.hpp
- tasks/mpi/kazunin_n_count_freq_a_char_in_string/perf_tests/main.cpp
- tasks/mpi/kazunin_n_count_freq_a_char_in_string/src/ops_mpi.cpp
- tasks/seq/kazunin_n_count_freq_a_char_in_string/func_tests/main.cpp
- tasks/seq/kazunin_n_count_freq_a_char_in_string/include/ops_seq.hpp
- tasks/seq/kazunin_n_count_freq_a_char_in_string/perf_tests/main.cpp
- tasks/seq/kazunin_n_count_freq_a_char_in_string/src/ops_seq.cpp
Описание задачи
Задача заключается в подсчете частоты появления заданного символа в строке, используя как последовательный, так и параллельный подходы. Основная цель — продемонстрировать, как различные методы обработки данных влияют на производительность и эффективность выполнения.
Последовательный вариант
В последовательном варианте реализация использует стандартную библиотеку C++ для подсчета символа в строке. Код проходит по каждому символу строки и считает количество вхождений целевого символа. Этот метод прост в реализации, но может быть неэффективным для больших строк, так как выполняет всю работу на одном потоке.
Параллельный вариант (MPI)
Параллельный вариант использует библиотеку MPI (Message Passing Interface) для распределения нагрузки между несколькими процессами. В этом …
> Казунин Никита. Задача 1. Вариант 23. Подсчёт частоты символа в строке.

- tasks/mpi/vladimirova_j_max_of_vector_elements/func_tests/main.cpp
- tasks/mpi/vladimirova_j_max_of_vector_elements/include/ops_mpi.hpp
- tasks/mpi/vladimirova_j_max_of_vector_elements/perf_tests/main.cpp
- tasks/mpi/vladimirova_j_max_of_vector_elements/src/ops_mpi.cpp
- tasks/seq/vladimirova_j_max_of_vector_elements/func_tests/main.cpp
- tasks/seq/vladimirova_j_max_of_vector_elements/include/ops_seq.hpp
- tasks/seq/vladimirova_j_max_of_vector_elements/perf_tests/main.cpp
- tasks/seq/vladimirova_j_max_of_vector_elements/src/ops_seq.cpp
Задача заключается в нахождении максимального значения элементов всей матрицы
_Алгоритм:_
Работаем с развернутой матрицей (вектор). Находим максимальный элемент путем прохождения по вектору и сравнения текущего максимального значения с элементом вектора, если значение элемента больше, то меняем текущее максимальное значение на этот элемент и продолжаем.
Находим максимальное значение применив алгоритм ко всей матрице сразу.
Делим развернутую матрицу поровну между процессами, если поровну разделить не удалось, то процессы с 1 начинают забирать себе по единице остатка, таким образом максимальная разница в кол-ве работы между процессами равна 1 . Все процессы применяют алгоритм к своей части, из полученных значений …
> Владимирова Юлия. Задача 1. Вариант 13. Максимальное значение элементов матрицы.

- tasks/mpi/example/include/ops_mpi.hpp
- tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
- tasks/mpi/kudryashova_i_vector_dot_product/include/vectorDotProductMPI.hpp
- tasks/mpi/kudryashova_i_vector_dot_product/perf_tests/vectorDotProductMPIPerfTests.cpp
- tasks/mpi/kudryashova_i_vector_dot_product/src/vectorDotProductMPI.cpp
- tasks/seq/kudryashova_i_vector_dot_product/func_tests/vectorDotProductSeqFuncTests.cpp
- tasks/seq/kudryashova_i_vector_dot_product/include/vectorDotProductSeq.hpp
- tasks/seq/kudryashova_i_vector_dot_product/perf_tests/vectorDotProductSeqPerfTests.cpp
- tasks/seq/kudryashova_i_vector_dot_product/src/vectorDotProductSeq.cpp
Описание последовательной задачи
Задача заключается в вычислении скалярного произведения двух векторов. Алгоритм поэлементно перемножает соответствующие элементы векторов, а затем суммирует полученные результаты.
Описание MPI задачи
Параллельная задача решается на нескольких процессах MPI. На момент начала рассмотрения задачи мы имеем двухмерный вектор чисел, который содержит два входных вектора. Эти векторы делятся на сегменты в зависимости от количества процессов. Затем каждый сегмент передается соответствующему процессу для дальнейшей обработки. Каждый процесс получает свой сегмент данных, выполняет поэлементное умножение векторов и суммирует результаты. После этого результаты со всех процессов переходят в корневой процесс, где суммируются для получения результата, который и будет …
> Кудряшова Ирина. Задача 1. Вариант 9. Скалярное произведение векторов.

- tasks/mpi/vasenkov_a_char_freq/func_tests/main.cpp
- tasks/mpi/vasenkov_a_char_freq/include/ops_mpi.hpp
- tasks/mpi/vasenkov_a_char_freq/perf_tests/main.cpp
- tasks/mpi/vasenkov_a_char_freq/src/ops_mpi.cpp
- tasks/seq/vasenkov_a_char_freq/func_tests/main.cpp
- tasks/seq/vasenkov_a_char_freq/include/ops_seq.hpp
- tasks/seq/vasenkov_a_char_freq/perf_tests/main.cpp
- tasks/seq/vasenkov_a_char_freq/src/ops_seq.cpp
Описание последовательной задачи.
Входные данные - строка и символ, число вхождений которого нужно найти.
Выходные данные - целочисленное значение - количество символа в строке.
Для простоты и читаемости кода подсчет ведется с помощью метода count библиотеки std.
Описание параллельной задачи.
Разделяем строку на несколько подстрок и поручаем эту задачу нескольким потокам. Разделение происходит равномерно. Затем каждый поток считает число входов символа в своей части строки. В итоге всё суммируется с помощью reduce.
> Васенков Андрей. Задача 1. Вариант 23. Подсчет частоты символа в строке

- tasks/mpi/milovankin_m_sum_of_vector_elements/func_tests/main.cpp
- tasks/mpi/milovankin_m_sum_of_vector_elements/include/ops_mpi.hpp
- tasks/mpi/milovankin_m_sum_of_vector_elements/perf_tests/main.cpp
- tasks/mpi/milovankin_m_sum_of_vector_elements/src/ops_mpi.cpp
- tasks/seq/milovankin_m_sum_of_vector_elements/func_tests/main.cpp
- tasks/seq/milovankin_m_sum_of_vector_elements/include/ops_seq.hpp
- tasks/seq/milovankin_m_sum_of_vector_elements/perf_tests/main.cpp
- tasks/seq/milovankin_m_sum_of_vector_elements/src/ops_seq.cpp
_**Последовательная задача**_
Итерация по элементам вектора и суммирование значений.
**_Параллельная задача_**
Вектор разделяется между процессами на равные части. Если количество элементов N не делится нацело на количество процессов P, то первые `N % P` процессов обрабатывают еще по одному элементу. 
Данные распределяются по процессам функцией `scatterv`, каждый процесс подсчитывает свою часть с помощью `accumulate`, затем получившиеся в процессах суммы складываются функцией `reduce`.
> Милованкин Максим. Задача 1. Вариант 1. Сумма элементов вектора.

- tasks/mpi/rams_s_char_frequency/func_tests/main.cpp
- tasks/mpi/rams_s_char_frequency/include/ops_mpi.hpp
- tasks/mpi/rams_s_char_frequency/perf_tests/main.cpp
- tasks/mpi/rams_s_char_frequency/src/ops_mpi.cpp
- tasks/seq/rams_s_char_frequency/func_tests/main.cpp
- tasks/seq/rams_s_char_frequency/include/ops_seq.hpp
- tasks/seq/rams_s_char_frequency/perf_tests/main.cpp
- tasks/seq/rams_s_char_frequency/src/ops_seq.cpp
Входные данные: строка и символ.
Подсчет числа вхождений символа в строку с помощью std::count.
Выходные данные: число вхождений символа в строку.
Описание параллельной задачи:
Входная строка равномерно делится между процессами. В случае если целочисленное деление длины строки на количество процессов невозможно, оставшиеся символы добавляются к подстроке последнего процесса. Каждый процесс считает число символов в своей подстроке. Полученные в каждом из процессов значения суммируются при помощи reduce.
> ‎Рамс Сергей. Задача 1. Вариант 23. Подсчет частоты символа в строке

- tasks/mpi/kondratev_ya_max_col_matrix/func_tests/main.cpp
- tasks/mpi/kondratev_ya_max_col_matrix/include/ops_mpi.hpp
- tasks/mpi/kondratev_ya_max_col_matrix/perf_tests/main.cpp
- tasks/mpi/kondratev_ya_max_col_matrix/src/ops_mpi.cpp
- tasks/seq/kondratev_ya_max_col_matrix/func_tests/main.cpp
- tasks/seq/kondratev_ya_max_col_matrix/include/ops_seq.hpp
- tasks/seq/kondratev_ya_max_col_matrix/perf_tests/main.cpp
- tasks/seq/kondratev_ya_max_col_matrix/src/ops_seq.cpp
Описание последовательной задачи
- входящая матрица при считывании транспонируется для удобства использования
- последовательный построчный поиск максимума
Описание MPI задачи 
- входящая матрица при считывании транспонируется для удобства использования
- матрица построчно рассылается доступным процессам. Количество отправляемых строк зависит от ранга процесса (если ранг меньше остатка от деления количества строк на количество процессов, то отправляется step_ + 1)
- каждый процесс последовательно построчно ищет максимумы в полученных данных
- результаты от процессов отправляются в главный процесс, где объединяются и записываются в итоговый ответ
> Кондратьев Ярослав. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы

- tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
- tasks/mpi/gordeva_t_max_val_of_column_matrix/include/ops_mpi.hpp
- tasks/mpi/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
- tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
- tasks/seq/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
- tasks/seq/gordeva_t_max_val_of_column_matrix/include/ops_seq.hpp
- tasks/seq/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
- tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp
**Описание программы.**
Программа вычисляет максимальное значение в каждом столбце матрицы.
_-Последовательная задача:_
- изначально максимальное значение равно первому элементу текущего столбца; происходит сравнение текущего максимального значения с каждым элементом из соответствующего столбца - если значение элемента больше, то оно становится максимальным значением
- результат: вектор с максимальными значениями для каждого столбца
_-MPI задача:_
- матрица разбивается на кол-во процессов
- каждый процесс ищет максимум в каждом столбце своих данных
- результаты процессов отправляются на главный процесс и объединяются 
- результат: вектор максимальных значений для каждого столбца
> Гордеева Таисия. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы

- tasks/mpi/ermilova_d_min_element_matrix/func_tests/main.cpp
- tasks/mpi/ermilova_d_min_element_matrix/include/ops_mpi.hpp
- tasks/mpi/ermilova_d_min_element_matrix/perf_tests/main.cpp
- tasks/mpi/ermilova_d_min_element_matrix/src/ops_mpi.cpp
- tasks/seq/ermilova_d_min_element_matrix/func_tests/main.cpp
- tasks/seq/ermilova_d_min_element_matrix/include/ops_seq.hpp
- tasks/seq/ermilova_d_min_element_matrix/perf_tests/main.cpp
- tasks/seq/ermilova_d_min_element_matrix/src/ops_seq.cpp
Описание последовательной задачи
Последовательно обходятся все элементы матрицы, при нахождении элемента меньше, чем текущий минимум - значение минимума будет обновлено.
Описание MPI задачи
Матрица разбивается на равные части. Каждый процесс получает свою часть матрицы, затем находит минимум в выделенной ему части. После этого все процессы отправляют свои результаты корневому процессу, который собирает их и находит минимум для всей матрицы.
> Ермилова Дарья. Задача 1. Вариант 14. Минимальное значение элементов матрицы.

- tasks/mpi/volochaev_s_count_characters_27/func_tests/main.cpp
- tasks/mpi/volochaev_s_count_characters_27/include/ops_mpi.hpp
- tasks/mpi/volochaev_s_count_characters_27/perf_tests/main.cpp
- tasks/mpi/volochaev_s_count_characters_27/src/ops_mpi.cpp
- tasks/seq/volochaev_s_count_characters_27/func_tests/main.cpp
- tasks/seq/volochaev_s_count_characters_27/include/ops_seq.hpp
- tasks/seq/volochaev_s_count_characters_27/perf_tests/main.cpp
- tasks/seq/volochaev_s_count_characters_27/src/ops_seq.cpp
Последовательный вариант:
Input: 2 строки (могут быть разных длин). Если длины не совпадают, то начальное состояние ответа: разность длин 2 строк, иначе 0. Проходимся линейно по строкам и сравниваем по id. Если буквы на одинаковых позициях не совпадают, то прибавляем к ответу 2, иначе идем дальше до минимальной длины из 2 строк.
pre_processing: Получение данных. Мы берем 2 строки и смотрим на их длину. Если разные, то обрезаем большую до длины меньшей, а разницу в длине помещаем в ответ.
validation: проверяем входные и выходные данные по количеству ( входных должно быть 2, а выходных 1)
run: идем по 2 строкам и сравниваем символы по id. Если не совпадают, то прибавляем 2. Иначе идем дальше.
post_processing: запись результата.
Параллельный вариант:
идея та же, но мы бьем строки на потоки. …
> Волочаев Серафим Задача 1. Вариант 27: Подсчет числа несовпадающих символов двух строк

- tasks/mpi/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
- tasks/mpi/sozonov_i_nearest_neighbor_elements/include/ops_mpi.hpp
- tasks/mpi/sozonov_i_nearest_neighbor_elements/perf_tests/main.cpp
- tasks/mpi/sozonov_i_nearest_neighbor_elements/src/ops_mpi.cpp
- tasks/seq/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
- tasks/seq/sozonov_i_nearest_neighbor_elements/include/ops_seq.hpp
- tasks/seq/sozonov_i_nearest_neighbor_elements/perf_tests/main.cpp
- tasks/seq/sozonov_i_nearest_neighbor_elements/src/ops_seq.cpp
**Описание последовательной задачи:**
1. Создаём переменную min и инициализируем её максимальным возможным значением INT_MAX.
2. Проходим по вектору, начиная с первого элемента до предпоследнего, и находим модуль разности между текущим элементом и следующим за ним.
3. Если модуль разности между ними меньше текущего значения min, обновляем min и запоминаем индекс текущего элемента вектора.
**Описание MPI задачи:**
1. Создаем новый вектор diff, состоящий из пар: модуль разности соседних элементов исходного вектора и соответствующего индекса.
2. Полученный вектор пар делится равномерно на сегменты по числу процессов.
3. Каждый сегмент данных отправляется от нулевого процесса остальным.
4. Каждый процесс находит наименьший элемент и соответствующий ему индекс в полученном сегменте данных.
5. …
> Созонов Илья. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.

- tasks/mpi/matyunina_a_average_of_vector_elements/func_tests/main.cpp
- tasks/mpi/matyunina_a_average_of_vector_elements/include/ops_mpi.hpp
- tasks/mpi/matyunina_a_average_of_vector_elements/perf_tests/main.cpp
- tasks/mpi/matyunina_a_average_of_vector_elements/src/ops_mpi.cpp
- tasks/seq/matyunina_a_average_of_vector_elements/func_tests/main.cpp
- tasks/seq/matyunina_a_average_of_vector_elements/include/ops_seq.hpp
- tasks/seq/matyunina_a_average_of_vector_elements/perf_tests/main.cpp
- tasks/seq/matyunina_a_average_of_vector_elements/src/ops_seq.cpp
seq: На вход получаем вектор из элементов и должны найти среднее значение элементов этого вектора. Складываем значения каждого элемента вектора и записываем в одну переменную, а затем делим на общее число элементов. Таким образом мы найдём следнее значение.
mpi: Делим один большой вектор значений на несколько отрезков и передаём эти отрезки различным процессам, размер отрезков определяется относительно количества процессов на котором мы будем работать. После этого складываем все значения полученные из разных процессов в главном процессе и в нём же делим это число на размер всего вектора.
> Матюнина Александра. Задача 1. Вариант 2. Вычисление среднего значения элементов вектора

- tasks/mpi/bessonov_e_integration_monte_carlo/func_tests/main.cpp
- tasks/mpi/bessonov_e_integration_monte_carlo/include/ops_mpi.hpp
- tasks/mpi/bessonov_e_integration_monte_carlo/perf_tests/main.cpp
- tasks/mpi/bessonov_e_integration_monte_carlo/src/ops_mpi.cpp
- tasks/seq/bessonov_e_integration_monte_carlo/func_tests/main.cpp
- tasks/seq/bessonov_e_integration_monte_carlo/include/ops_seq.hpp
- tasks/seq/bessonov_e_integration_monte_carlo/perf_tests/main.cpp
- tasks/seq/bessonov_e_integration_monte_carlo/src/ops_seq.cpp
**SEQ:**
Метод _pre_processing()_ извлекает границы интегрирования _a_ и _b_, а также количество случайных точек _num_points_ из входных данных.
Интегрирование:
Метод _run()_ выполняет следующие действия:
- Инициализирует генератор случайных чисел.
- Генерирует num_points случайных значений x в диапазоне [a, b].
- Для каждого x вычисляет значение функции и суммирует результаты.
- Вычисляет итоговый результат интегрирования как произведение диапазона интегрирования (b - a) на среднее значение вычисленных функций.
**MPI**
Метод _run()_ выполняет следующие действия на каждом процессе:
- Определяет количество точек _num_points_for_process_, которое необходимо обработать текущему процессу, учитывая общее количество процессов и возможный остаток.
- Генерирует num_points_for_process случайных …
> Бессонов Егор. Задача 21. Интегрирование – метод Монте-Карло.

- tasks/mpi/shlyakov_m_min_value_of_row/func_tests/main.cpp
- tasks/mpi/shlyakov_m_min_value_of_row/include/ops_mpi.hpp
- tasks/mpi/shlyakov_m_min_value_of_row/perf_tests/main.cpp
- tasks/mpi/shlyakov_m_min_value_of_row/src/ops_mpi.cpp
- tasks/seq/shlyakov_m_min_value_of_row/func_tests/main.cpp
- tasks/seq/shlyakov_m_min_value_of_row/include/ops_seq.hpp
- tasks/seq/shlyakov_m_min_value_of_row/perf_tests/main.cpp
- tasks/seq/shlyakov_m_min_value_of_row/src/ops_seq.cpp
Этапы последовательной части:
1.Подготовка структуры для матрицы и результата.
2.Заполнение матрицы.
3.Поиск минимумов в каждой строке с обновлением минимального значения.
3.Сохранение найденных значений в выходной массив.
Этапы MPI части:
1.Главный процесс загружает матрицу и распределяет строки между всеми процессами.
2.Каждый процесс выполняет поиск минимальных значений в своём наборе строк.
3.Все процессы отправляют свои результаты главному процессу.
4.Главный процесс собирает результаты и сохраняет их в конечный массив.
> Шляков Максим. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы

- tasks/mpi/guseynov_e_check_lex_order_of_two_string/func_tests/main.cpp
- tasks/mpi/guseynov_e_check_lex_order_of_two_string/include/ops_mpi.hpp
- tasks/mpi/guseynov_e_check_lex_order_of_two_string/perf_tests/main.cpp
- tasks/mpi/guseynov_e_check_lex_order_of_two_string/src/ops_mpi.cpp
- tasks/seq/guseynov_e_check_lex_order_of_two_string/func_tests/main.cpp
- tasks/seq/guseynov_e_check_lex_order_of_two_string/include/ops_seq.hpp
- tasks/seq/guseynov_e_check_lex_order_of_two_string/perf_tests/main.cpp
- tasks/seq/guseynov_e_check_lex_order_of_two_string/src/ops_seq.cpp
Последовательное решение:
Проверяем символы с одинаковыми индексами в словах на неравенство. Если окажется, что i-ый символы не совпадают, то, в случае если символ в первом слове лексиграфически больше символа во втором слове, то первое слово больше, иначе - первое слово меньше. Мы движемся по словам с помощью цыкла, пока не достигнем конца наименьшего слова. Если находим несоответсвие в символе, то записывыем результат и выходим из цыкла. Если цикл пройден полностью, то возможно 3 варианта. Первый - слова одинаковы(длины слов равны), второй - первое слово является префиксом второго слова(первое слово меньше), третий - второе слово префикс первого(первое слово больше).
Паралельное решение:
Каждый поток получает свои отрезки слов, делают проверки в циклах, потом собираем отдельные …
> Гусейнов Эмил. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.

- tasks/mpi/khovansky_d_max_of_vector_elements/func_tests/main.cpp
- tasks/mpi/khovansky_d_max_of_vector_elements/include/ops_mpi.hpp
- tasks/mpi/khovansky_d_max_of_vector_elements/perf_tests/main.cpp
- tasks/mpi/khovansky_d_max_of_vector_elements/src/ops_mpi.cpp
- tasks/seq/khovansky_d_max_of_vector_elements/func_tests/main.cpp
- tasks/seq/khovansky_d_max_of_vector_elements/include/ops_seq.hpp
- tasks/seq/khovansky_d_max_of_vector_elements/perf_tests/main.cpp
- tasks/seq/khovansky_d_max_of_vector_elements/src/ops_seq.cpp
Задача нахождения максимального элемента в векторе заключается в том, чтобы определить наибольшее значение среди элементов одномерного вектора целых чисел. Для корректного выполнения алгоритма входные данные должны содержать хотя бы один элемент, а результат должен быть представлен единственным числом.
1.Инициализация данных: Входной вектор инициализируется значениями из входных данных.
2.Поиск максимального элемента: Выполняется проход по вектору, начиная с первого элемента. Для каждого элемента сравнивается текущее максимальное значение с текущим элементом вектора. Если текущий элемент больше, он становится новым максимальным значением.
3.Обработка результата: После завершения прохода по вектору максимальное значение сохраняется и возвращается в …
> Хованский Дмитрий. Задача 1. Вариант 3. Максимальное значение элементов вектора. 

- tasks/mpi/kurakin_m_min_values_by_rows_matrix/func_tests/main.cpp
- tasks/mpi/kurakin_m_min_values_by_rows_matrix/include/ops_mpi.hpp
- tasks/mpi/kurakin_m_min_values_by_rows_matrix/perf_tests/main.cpp
- tasks/mpi/kurakin_m_min_values_by_rows_matrix/src/ops_mpi.cpp
- tasks/seq/kurakin_m_min_values_by_rows_matrix/func_tests/main.cpp
- tasks/seq/kurakin_m_min_values_by_rows_matrix/include/ops_seq.hpp
- tasks/seq/kurakin_m_min_values_by_rows_matrix/perf_tests/main.cpp
- tasks/seq/kurakin_m_min_values_by_rows_matrix/src/ops_seq.cpp
Описание последовательного алгоритма:
- Проходим по каждому элементу строки и определяем её минимум
Описание MPI алгоритма:
- Нулевой процесс распределяет данные среди всех процессов. Он делит матрицу, представленную как вектор, на части. Количество частей равно количеству процессов.
- На этапе run() каждый процесс сам определяет границы строк и находит их минимумы. Если строка разбита на несколько процессов, то каждый процесс ищет минимум на своем участке, а затем, с помощью reduce, результат собирается в 0 процессе.
> Куракин Матвей. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы.

- tasks/mpi/poroshin_v_find_min_val_row_matrix/func_tests/main.cpp
- tasks/mpi/poroshin_v_find_min_val_row_matrix/include/ops_mpi.hpp
- tasks/mpi/poroshin_v_find_min_val_row_matrix/perf_tests/main.cpp
- tasks/mpi/poroshin_v_find_min_val_row_matrix/src/ops_mpi.cpp
- tasks/seq/poroshin_v_find_min_val_row_matrix/func_tests/main.cpp
- tasks/seq/poroshin_v_find_min_val_row_matrix/include/ops_seq.hpp
- tasks/seq/poroshin_v_find_min_val_row_matrix/perf_tests/main.cpp
- tasks/seq/poroshin_v_find_min_val_row_matrix/src/ops_seq.cpp
Этапы последовательной части:
Подготовка структуры для матрицы и результата:
Создаем одномерный массив (матрицу) для хранения данных (по строкам). Этот массив будет содержать значения, которые мы будем анализировать.
Также создаем одномерный массив для хранения результатов — минимальных значений, найденных в каждой строке матрицы.
Заполнение матрицы:
Инициализируем матрицу значениями. Это может быть сделано с помощью случайной генерации чисел или загрузки данных из файла.
Также важно удостовериться, что все элементы матрицы корректно заполнены, в этом случае мы можем начать поиск минимумов.
Поиск минимумов производится в каждой строке (с обновлением минимального значения):
Проходим по каждой строке матрицы и ищем минимальное значение.
Для каждой строки обновляем минимальное значение, если …
> Порошин Владислав. Задача 1. Вариант 17. Нахождение минимальных значений по строкам матрицы

- tasks/mpi/vedernikova_k_word_num_in_str/func_tests/main.cpp
- tasks/mpi/vedernikova_k_word_num_in_str/include/ops_mpi.hpp
- tasks/mpi/vedernikova_k_word_num_in_str/perf_tests/main.cpp
- tasks/mpi/vedernikova_k_word_num_in_str/src/ops_mpi.cpp
- tasks/seq/vedernikova_k_word_num_in_str/func_tests/main.cpp
- tasks/seq/vedernikova_k_word_num_in_str/include/ops_seq.hpp
- tasks/seq/vedernikova_k_word_num_in_str/perf_tests/main.cpp
- tasks/seq/vedernikova_k_word_num_in_str/src/ops_seq.cpp
**Описание**
- **Последовательная задача.** Программа является конечным автоматом с двумя состояниями - пробел (is_space) и не-пробел. Когда состояние меняется с "пробел" на "не-пробел", счетчик слов увеличивается. 
- **Параллельная задача.** Подсчет слов работает аналогично. Рассылка данных происходит с перехлестом в левую сторону, чтобы избежать двойного учета одного слова .
> Ведерникова Ксения. Задача 1. Вариант 24. Подсчет числа слов в строке

- tasks/mpi/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
- tasks/mpi/morozov_e_min_val_in_rows_matrix/include/ops_mpi.hpp
- tasks/mpi/morozov_e_min_val_in_rows_matrix/perf_tests/main.cpp
- tasks/mpi/morozov_e_min_val_in_rows_matrix/src/ops_mpi.cpp
- tasks/seq/morozov_e_min_val_in_rows_matrix/func_tests/main.cpp
- tasks/seq/morozov_e_min_val_in_rows_matrix/include/ops_seq.hpp
- tasks/seq/morozov_e_min_val_in_rows_matrix/perf_tests/main.cpp
- tasks/seq/morozov_e_min_val_in_rows_matrix/src/ops_seq.cpp
**_Описание последовательной задачи_**
Создаем вектор размера равным количеству строк матрицы. Проходимся по строкам матрицы и вычисляем максимальное значение и кладем в вектор ответов.
**_Описание параллельной задачи_**
Делим матрицу на несколько частей (в каждой равное количество строк (почти, максимальная разница по количество<=1)). Вычисляем в каждой части минимальное значение по строкам. Собираем все ответы в один общий вектор ответов.
> Морозов Егор. Задача 1. Вариант17.  Нахождение минимальных значений по строкам матрицы

- tasks/mpi/kozlova_e_lexic_order/func_tests/main.cpp
- tasks/mpi/kozlova_e_lexic_order/include/ops_mpi.hpp
- tasks/mpi/kozlova_e_lexic_order/perf_tests/main.cpp
- tasks/mpi/kozlova_e_lexic_order/src/ops_mpi.cpp
- tasks/seq/kozlova_e_lexic_order/func_tests/main.cpp
- tasks/seq/kozlova_e_lexic_order/include/ops_seq.hpp
- tasks/seq/kozlova_e_lexic_order/perf_tests/main.cpp
- tasks/seq/kozlova_e_lexic_order/src/ops_seq.cpp
Последовательная версия задачи заключается в определении, упорядочены ли две строки в лексикографическом порядке. Проверяется каждая строка. Если в любой момент текущий символ больше следующего, строка считается неупорядоченной лексикографически. В результат записывается вектор из двух чисел, результатов проверки лексикографического порядка первой и второй строки соответственно. Если строка упорядочена записывается 1, не упорядочена - 0.
Параллельная версия выполняет ту же задачу, но с использованием MPI для распределения вычислений между несколькими процессами. Входные строки передаются всем процессам, при этом главный процесс получает строки и отправляет их остальным процессам через broadcast. Каждый процесс получает часть символов строк и выполняет проверку их упорядоченности. Строки …
> Козлова Екатерина. Задача 1. Вариант 26. Проверка лексикографической упорядоченности двух строк.

- tasks/mpi/koshkin_n_sum_values_by_columns_matrix/func_tests/main.cpp
- tasks/mpi/koshkin_n_sum_values_by_columns_matrix/include/ops_mpi.hpp
- tasks/mpi/koshkin_n_sum_values_by_columns_matrix/perf_tests/main.cpp
- tasks/mpi/koshkin_n_sum_values_by_columns_matrix/src/ops_mpi.cpp
- tasks/seq/koshkin_n_sum_values_by_columns_matrix/func_tests/main.cpp
- tasks/seq/koshkin_n_sum_values_by_columns_matrix/include/ops_seq.hpp
- tasks/seq/koshkin_n_sum_values_by_columns_matrix/perf_tests/main.cpp
- tasks/seq/koshkin_n_sum_values_by_columns_matrix/src/ops_seq.cpp
Создается двумерный вектор для хранения элементов матрицы. Программа вычисляет сумму для каждого столбца матрицы и сохраняет результаты в отдельный вектор.
Описание MPI задачи: распределяем строки по процессам, и каждый процесс посчитает сумму для определенного набора строк. Итоговые суммы по столбцам собираем на главном процессе.
1) В pre_processing() храним исходную матрицу в одномерном векторе input_ (размером rows * columns);
2) 2.1) В run() используем broadcast для передачи значений rows (строчки) и columns (столбцы);
2.2) Главный процесс (с ранком 0) делит строки матрицы между процессами, каждому процессу отправляется отрезок данных (несколько строк матрицы) через send();
2.3) Остальные процессы получают свои строки через recv() и сохраняют их в …
> Кошкин Никита. Задача 1. Вариант 12. Сумма значений по столбцам матрицы.

- tasks/mpi/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
- tasks/mpi/koshkin_m_scalar_product_of_vectors/include/ops_mpi.hpp
- tasks/mpi/koshkin_m_scalar_product_of_vectors/perf_tests/main.cpp
- tasks/mpi/koshkin_m_scalar_product_of_vectors/src/ops_mpi.cpp
- tasks/seq/koshkin_m_scalar_product_of_vectors/func_tests/main.cpp
- tasks/seq/koshkin_m_scalar_product_of_vectors/include/ops_seq.hpp
- tasks/seq/koshkin_m_scalar_product_of_vectors/perf_tests/main.cpp
- tasks/seq/koshkin_m_scalar_product_of_vectors/src/ops_seq.cpp
Описание последовательной задачи: 
Задача состоит в том, чтобы выполнить поэлементное умножение двух векторов. Каждый элемент первого вектора умножается на соответствующий элемент второго вектора, и полученные произведения суммируются. В итоге получаем значение скалярного произведения
Описание MPI задачи:
Задан двумерный вектор целых чисел, содержащий два входных вектора. Эти векторы разделяются на равные части в соответствии с количеством процессов. Каждый процесс получает свою часть данных, где выполняется поэлементное умножение соответствующих элементов двух векторов. После этого произведения в каждом процессе суммируются, а результаты передаются на нулевой процесс, там они суммируются, для получения итогового произведения
> Кошкин Матвей. Задача 1. Вариант 9. Скалярное произведение векторов

- tasks/mpi/sadikov_I_sum_values_by_columns_matrix/func_tests/main.cpp
- tasks/mpi/sadikov_I_sum_values_by_columns_matrix/include/ops_mpi.h
- tasks/mpi/sadikov_I_sum_values_by_columns_matrix/perf_tests/main.cpp
- tasks/mpi/sadikov_I_sum_values_by_columns_matrix/src/mpi_src.cpp
- tasks/seq/sadikov_I_sum_values_by_columns_matrix/func_tests/seq_func_tests.cpp
- tasks/seq/sadikov_I_sum_values_by_columns_matrix/include/sq_task.h
- tasks/seq/sadikov_I_sum_values_by_columns_matrix/perf_tests/main.cpp
- tasks/seq/sadikov_I_sum_values_by_columns_matrix/src/ops_seq.cpp
Описание последовательного решения:
Входные данные транспонируются и записываются в вектор matrix. С помощью цикла по количеству столбцов проходим по вектору matrix и при помощи std::accumulate получаем сумму по каждому столбцу. Данные записываются в вектор sum.
Описание параллельного решения:
Входные данные транспонируются и записываются в вектор matrix. Далее высчитываем delta - количество столбцов, выделяемое каждому процессу. Если количество столбцов не делится между процессами нацело, оставшиеся столбцы передаются последнему процессу. Каждый из процессов проходит по своим столбцам при помощи std::accumulate и записывает результат в вектор local_input. Позднее все векторы объединяются в один, который передается в ответ.
> Садиков Иван. Задача 1. Вариант 12. Сумма значений по столбцам матрицы

- tasks/mpi/stroganov_m_count_symbols_in_string/func_tests/main.cpp
- tasks/mpi/stroganov_m_count_symbols_in_string/include/ops_mpi.hpp
- tasks/mpi/stroganov_m_count_symbols_in_string/perf_tests/main.cpp
- tasks/mpi/stroganov_m_count_symbols_in_string/src/ops_mpi.cpp
- tasks/seq/stroganov_m_count_symbols_in_string/func_tests/main.cpp
- tasks/seq/stroganov_m_count_symbols_in_string/include/ops_seq.hpp
- tasks/seq/stroganov_m_count_symbols_in_string/perf_tests/main.cpp
- tasks/seq/stroganov_m_count_symbols_in_string/src/ops_seq.cpp
Данный проект реализует задачу подсчета символов в строке двумя методами: последовательным и параллельным с использованием MPI. Цель проекта — сравнить производительность и корректность обоих подходов, протестировав их с использованием различных данных.
Основные компоненты:
Тесты: Для обоих методов используются тесты на базе gtest для оценки корректности и производительности реализации.
Функции подсчета символов: Реализация включает функции для генерации случайных строк и непосредственного подсчета символов, а также классы для запуска задач в последовательной и параллельной среде.
Цель:
Проект демонстрирует преимущества и недостатки параллельной обработки по сравнению с последовательной, позволяя оценить, насколько MPI может ускорить выполнение задачи при обработке больших объемов данных.
> Строганов Михаил. Задача 1. Вариант 22. Нахождение числа буквенных символов в строке.

- tasks/mpi/example/include/ops_mpi.hpp
- tasks/mpi/kudryashova_i_vector_dot_product/func_tests/vectorDotProductMPIFuncTests.cpp
- tasks/mpi/kudryashova_i_vector_dot_product/include/vectorDotProductMPI.hpp
- tasks/mpi/kudryashova_i_vector_dot_product/perf_tests/vectorDotProductMPIPerfTests.cpp
- tasks/mpi/kudryashova_i_vector_dot_product/src/vectorDotProductMPI.cpp
- tasks/seq/kudryashova_i_vector_dot_product/func_tests/vectorDotProductSeqFuncTests.cpp
- tasks/seq/kudryashova_i_vector_dot_product/include/vectorDotProductSeq.hpp
- tasks/seq/kudryashova_i_vector_dot_product/perf_tests/vectorDotProductSeqPerfTests.cpp
- tasks/seq/kudryashova_i_vector_dot_product/src/vectorDotProductSeq.cpp
Fixed seq_perf_tests
https://github.com/learning-process/ppc-2024-autumn/pull/69
> Кудряшова Ирина. Задача 1. Вариант 9. Скалярное произведение векторов

- tasks/mpi/Sdobnov_V_sum_of_vector_elements/func_tests/main.cpp
- tasks/mpi/Sdobnov_V_sum_of_vector_elements/include/ops_mpi.hpp
- tasks/mpi/Sdobnov_V_sum_of_vector_elements/perf_tests/main.cpp
- tasks/mpi/Sdobnov_V_sum_of_vector_elements/src/ops_mpi.cpp
- tasks/seq/Sdobnov_V_sum_of_vector_elements/func_tests/main.cpp
- tasks/seq/Sdobnov_V_sum_of_vector_elements/include/ops_seq.hpp
- tasks/seq/Sdobnov_V_sum_of_vector_elements/perf_tests/main.cpp
- tasks/seq/Sdobnov_V_sum_of_vector_elements/src/ops_seq.cpp
_**Последовательная задача**_
Переводим матрицу в вектор и по итератору складываем элементы полученного вектора
**_Параллельная задача_**
Переводим матрицу в вектор. Высчитываем размер и смещение векторов, которые потом рассылаем по прочим процессам с помощью функции 'scatterv'. В каждом процессе по итератору считаем сумму элементов переданного вектора. В конце объединяем результаты процессов с помощью функции 'reduce'
> Сдобнов Владимир. Задача 1. Вариант 10. Сумма элементов матрицы.

- tasks/mpi/volochaev_s_count_characters_27/func_tests/main.cpp
- tasks/mpi/volochaev_s_count_characters_27/include/ops_mpi.hpp
- tasks/mpi/volochaev_s_count_characters_27/perf_tests/main.cpp
- tasks/mpi/volochaev_s_count_characters_27/src/ops_mpi.cpp
- tasks/seq/volochaev_s_count_characters_27/func_tests/main.cpp
- tasks/seq/volochaev_s_count_characters_27/include/ops_seq.hpp
- tasks/seq/volochaev_s_count_characters_27/perf_tests/main.cpp
- tasks/seq/volochaev_s_count_characters_27/src/ops_seq.cpp
Последовательный вариант:
Input: 2 строки (могут быть разных длин). Если длины не совпадают, то начальное состояние ответа: разность длин 2 строк, иначе 0. Проходимся линейно по строкам и сравниваем по id. Если буквы на одинаковых позициях не совпадают, то прибавляем к ответу 2, иначе идем дальше до минимальной длины из 2 строк.
pre_processing: Получение данных. Мы берем 2 строки и смотрим на их длину. Если разные, то обрезаем большую до длины меньшей, а разницу в длине помещаем в ответ.
validation: проверяем входные и выходные данные по количеству ( входных должно быть 2, а выходных 1)
run: идем по 2 строкам и сравниваем символы по id. Если не совпадают, то прибавляем 2. Иначе идем дальше.
post_processing: запись результата.
Параллельный вариант:
идея та же, но мы бьем строки на потоки. …
> fix Revert "Волочаев Серафим Задача 1. Вариант 27: Подсчет числа несовпадающих символов двух строк"

- tasks/mpi/tsatsyn_a_vector_dot_product/func_tests/main.cpp
- tasks/mpi/tsatsyn_a_vector_dot_product/include/ops_mpi.hpp
- tasks/mpi/tsatsyn_a_vector_dot_product/perf_tests/main.cpp
- tasks/mpi/tsatsyn_a_vector_dot_product/src/ops_mpi.cpp
- tasks/seq/tsatsyn_a_vector_dot_product/func_tests/main.cpp
- tasks/seq/tsatsyn_a_vector_dot_product/include/ops_seq.hpp
- tasks/seq/tsatsyn_a_vector_dot_product/perf_tests/main.cpp
- tasks/seq/tsatsyn_a_vector_dot_product/src/ops_seq.cpp
Создаем 2 вектора определённого размера. В цикле перемножаем их координаты и сохраняем ответ в переменной.
**Описание параллельной задачи**
Создаём 2 вектора определённого размера. Определяем долю того что будут делать новые процессы (delta) и распределяем им соответствующую работу.
> Цацын Александр. Задача 1. Вариант 9.  Скалярное произведение векторов.

- tasks/mpi/tarakanov_d_integration_the_trapezoid_method/func_tests/main.cpp
- tasks/mpi/tarakanov_d_integration_the_trapezoid_method/include/ops_mpi.hpp
- tasks/mpi/tarakanov_d_integration_the_trapezoid_method/perf_tests/main.cpp
- tasks/mpi/tarakanov_d_integration_the_trapezoid_method/src/ops_mpi.cpp
- tasks/seq/tarakanov_d_integration_the_trapezoid_method/func_tests/main.cpp
- tasks/seq/tarakanov_d_integration_the_trapezoid_method/include/ops_seq.hpp
- tasks/seq/tarakanov_d_integration_the_trapezoid_method/perf_tests/main.cpp
- tasks/seq/tarakanov_d_integration_the_trapezoid_method/src/ops_seq.cpp
**seq:** 
Интегрируем от a до b с шагом h. На каждом шаге рассчитывает площадь трапеции и добавляет её к итоговому результату. По завершении результат сохраняется в выходной переменной.
**mpi:**
Каждому процессу даём по некоторому множеству трапеций, по которым процесс и будет проходиться, выполняя стандартный последовательный алгоритм. В конце суммируем результат со всех потоков в одну переменную.
> Тараканов Денис. Задача 1. Вариант 20. Интегрирование - метод трапеций.

- tasks/mpi/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
- tasks/mpi/gordeva_t_max_val_of_column_matrix/include/ops_mpi.hpp
- tasks/mpi/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
- tasks/mpi/gordeva_t_max_val_of_column_matrix/src/ops_mpi.cpp
- tasks/seq/gordeva_t_max_val_of_column_matrix/func_tests/main.cpp
- tasks/seq/gordeva_t_max_val_of_column_matrix/include/ops_seq.hpp
- tasks/seq/gordeva_t_max_val_of_column_matrix/perf_tests/main.cpp
- tasks/seq/gordeva_t_max_val_of_column_matrix/src/ops_seq.cpp
Reverts learning-process/ppc-2024-autumn#180
Ошибка заключалась в том, что один из тестов отрабатывал больше 1 секунды. Собственно, так тест работал из-за большого размера матрицы. Ошибка исправлена
**Описание программы.**
Программа вычисляет максимальное значение в каждом столбце матрицы.
_-Последовательная задача:_
изначально максимальное значение равно первому элементу текущего столбца; происходит сравнение текущего максимального значения с каждым элементом из соответствующего столбца - если значение элемента больше, то оно становится максимальным значением
результат: вектор с максимальными значениями для каждого столбца
_-MPI задача:_
матрица разбивается на кол-во процессов
каждый процесс ищет максимум в каждом столбце своих данных
результаты процессов отправляются на главный процесс …
> Revert "Гордеева Таисия. Задача 1. Вариант 16. Нахождение максимальных значений по столбцам матрицы"

- tasks/mpi/zaitsev_a_min_of_vector_elements/func_tests/main.cpp
- tasks/mpi/zaitsev_a_min_of_vector_elements/include/ops_mpi.hpp
- tasks/mpi/zaitsev_a_min_of_vector_elements/perf_tests/main.cpp
- tasks/mpi/zaitsev_a_min_of_vector_elements/src/ops_mpi.cpp
- tasks/seq/zaitsev_a_min_of_vector_elements/func_tests/main.cpp
- tasks/seq/zaitsev_a_min_of_vector_elements/include/ops_seq.hpp
- tasks/seq/zaitsev_a_min_of_vector_elements/perf_tests/main.cpp
- tasks/seq/zaitsev_a_min_of_vector_elements/src/ops_seq.cpp
Принять, что первый элемент вектора, является текущим минимальным найденным. 
Сравнить текущий минимальный элемент с очередным непроверенным элементом вектора, начиная со второго.
При достижении конца вектора текущий минимальный элемент будет минимальным элементом во всем векторе.
Разбить вектор на подвекторы длины, равной соотношению длины исходного вектора к количеству выделенных потоков.
В каждом потоке запустить последовательную реализацию алгоритма для соответствующего подвектора.
С помощью `boost::mpi::reduce()` найти наименьший элемент среди минимумов, полученных в каждом потоке.
> Зайцев Артем. Задача 1. Вариант 4. Минимальный элемент вектора.

- tasks/mpi/shulpin_monte_carlo_integration/func_tests/main.cpp
- tasks/mpi/shulpin_monte_carlo_integration/include/monte_carlo_integral.hpp
- tasks/mpi/shulpin_monte_carlo_integration/perf_tests/main.cpp
- tasks/mpi/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
- tasks/seq/shulpin_monte_carlo_integration/func_tests/main.cpp
- tasks/seq/shulpin_monte_carlo_integration/include/monte_carlo_integral.hpp
- tasks/seq/shulpin_monte_carlo_integration/perf_tests/main.cpp
- tasks/seq/shulpin_monte_carlo_integration/src/monte_carlo_integral.cpp
Метод Монте-Карло для интегрирования — это численный метод, основанный на случайном выборе точек в области интегрирования.
Допустим, у нас есть функция 𝑓(𝑥), которую нужно проинтегрировать на интервале [𝑎,𝑏] : 𝐼 = ∫𝑓(𝑥)𝑑𝑥
​1. Генерация случайных точек:
2. Вычисление среднего значения функции: Среднее значение = 1/N ∑f(Xi) (i = 1; до N), где N — общее количество случайных точек.
3. Умножение на длину интервала: 𝐼 ≈ (𝑏 − 𝑎 ) ⋅ 1/N ∑𝑓(Xi) (i = 1; до N)
**Параллельная реализация метода Монте-Карло для интегрирования функции с использованием MPI**
Параллельная реализация метода Монте-Карло для интегрирования функции на отрезке [𝑎,𝑏] основана на распределении нагрузки между несколькими процессами, где каждый процесс вычисляет приближённое значение интеграла на своём подотрезке. Итоговый …
> Шульпин Илья. Задача 1. Вариант 21. Интегрирование методом Монте-Карло

- tasks/mpi/leontev_n_vector_sum/func_tests/main.cpp
- tasks/mpi/leontev_n_vector_sum/include/ops_mpi.hpp
- tasks/mpi/leontev_n_vector_sum/perf_tests/main.cpp
- tasks/mpi/leontev_n_vector_sum/src/ops_mpi.cpp
- tasks/seq/leontev_n_vector_sum/func_tests/main.cpp
- tasks/seq/leontev_n_vector_sum/include/ops_seq.hpp
- tasks/seq/leontev_n_vector_sum/perf_tests/main.cpp
- tasks/seq/leontev_n_vector_sum/src/ops_seq.cpp
Для суммирования всех элементов вектора используется стандартная функция std::accumulate. Тестами проверен данный функционал для разного числа элементов и проведены замеры времени выполнения.
Описание MPI задачи:
Вектор разделяется на части, параллельно для каждой части выполняется std::accumulate. Затем все результаты сложения складываются. Тестами проверена работоспособность данной схемы, а так же произведены замеры производительности в сравнении с последовательной реализацией.
> Леонтьев Никита. Задача 1. Вариант 1. Сумма элементов вектора.

- tasks/mpi/chernova_n_word_count/func_tests/main.cpp
- tasks/mpi/chernova_n_word_count/include/ops_mpi.hpp
- tasks/mpi/chernova_n_word_count/perf_tests/main.cpp
- tasks/mpi/chernova_n_word_count/src/ops_mpi.cpp
- tasks/seq/chernova_n_word_count/func_tests/main.cpp
- tasks/seq/chernova_n_word_count/include/ops_seq.hpp
- tasks/seq/chernova_n_word_count/perf_tests/main.cpp
- tasks/seq/chernova_n_word_count/src/ops_seq.cpp
**Описание последовательной задачи.**
Входные данные - строка, в которой нужно найти количество входящих слов.
Выходные данные - целочисленное значение - количество слов в строке.
**Описание параллельной задачи.**
Разделяем строку на несколько подстрок и поручаем эту задачу нескольким потокам. Разделение происходит равномерно. Затем каждый поток считает число слов в своей части строки. В итоге всё суммируется с помощью reduce.
> Чернова Наталья. Задача 1. Вариант 24. Подсчет числа слов в строке

- tasks/mpi/vershinina_a_integration_the_monte_carlo_method/func_tests/main.cpp
- tasks/mpi/vershinina_a_integration_the_monte_carlo_method/include/ops_mpi.hpp
- tasks/mpi/vershinina_a_integration_the_monte_carlo_method/perf_tests/main.cpp
- tasks/mpi/vershinina_a_integration_the_monte_carlo_method/src/ops_mpi.cpp
- tasks/seq/vershinina_a_integration_the_monte_carlo_method/func_tests/main.cpp
- tasks/seq/vershinina_a_integration_the_monte_carlo_method/include/ops_seq.hpp
- tasks/seq/vershinina_a_integration_the_monte_carlo_method/perf_tests/main.cpp
- tasks/seq/vershinina_a_integration_the_monte_carlo_method/src/ops_seq.cpp
Последовательное решение:
Определяем сколько случайных точек попало в нашу область, вычисляем плотность и с помощью нее получаем значение нужного нам интеграла.
Параллельное решение:
Тоже самое, только используется фиксированное число итераций, входные данные рассылаются всем процессам через boost::mpi::broadcast и распараллеливается финальная часть алгоритма.
> Вершинина Александра. Задача 1. Вариант 21. Интегрирование – метод Монте-Карло

- tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/func_tests/main.cpp
- tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/include/ops_mpi.hpp
- tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/perf_tests/main.cpp
- tasks/mpi/shvedova_v_matrix_mult_horizontal_a_vertical_b_mpi/src/ops_mpi.cpp
- tasks/seq/shvedova_v_matrix_mult_horizontal_a_vertical_b_seq/func_tests/main.cpp
- tasks/seq/shvedova_v_matrix_mult_horizontal_a_vertical_b_seq/include/ops_seq.hpp
- tasks/seq/shvedova_v_matrix_mult_horizontal_a_vertical_b_seq/perf_tests/main.cpp
- tasks/seq/shvedova_v_matrix_mult_horizontal_a_vertical_b_seq/src/ops_seq.cpp
В последовательной версии реализован наивный метод матричного умножения, не требующий отдельного описания. Единственное, что заслуживает внимания - были внесены некоторые отличия в последовательный алгоритм, находящийся в папке mpi - он стал использовать мой класс для матрицы, как и его параллельная версия. Сделано это для удобства тестирования параллельной версии.
Для удобства работы используется специальный класс Matrix.
- На **нулевом процессе** (root):
- Получаем входные данные (матрицы \( A \) и \( B \)), их размеры, а также вычисляем количество строк и столбцов для каждой матрицы.
- Строим вспомогательные структуры данных:
- Массивы индексов для строк матрицы \( A \) и столбцов матрицы \( B \).
- Разбиение на части для распределения данных между процессами.
- Производим разбиение …
> Шведова Виталина. Задача 2. Вариант 18. Умножение матриц - ленточная горизонтальная схема A, вертикальное B.

- tasks/mpi/korablev_v_jacobi_method/func_tests/main.cpp
- tasks/mpi/korablev_v_jacobi_method/include/ops_mpi.hpp
- tasks/mpi/korablev_v_jacobi_method/perf_tests/main.cpp
- tasks/mpi/korablev_v_jacobi_method/src/ops_mpi.cpp
- tasks/seq/korablev_v_jacobi_method/func_tests/main.cpp
- tasks/seq/korablev_v_jacobi_method/include/ops_seq.hpp
- tasks/seq/korablev_v_jacobi_method/perf_tests/main.cpp
- tasks/seq/korablev_v_jacobi_method/src/ops_seq.cpp
- Определяем размер системы уравнений n) из размера вектора правой части b.
- Создаём вектор x_prev, чтобы сохранять значения неизвестных с предыдущей итерации.
- Инициализируем счётчик итераций.
Повторяем до тех пор, пока:
1. Не достигнуто заданное максимальное количество итераций.
2. Условие сходимости не выполнено (проверяется разница между текущим и предыдущим приближением):
- Для каждой переменной x_k:
- Вычисляем сумму произведений коэффициентов строки матрицы \( A \), исключая диагональный элемент, и значений из вектора x_prev
- Обновляем x_k.
- Вычисляем относительное изменение между векторами x_prev и x_k.
- Если оно меньше заданного порога точности, итерации завершаются.
- Если достигается максимальное количество итераций, процесс останавливается, даже если точность не …
> Кораблев Владлен. Задача 2. Вариант 22.  Итеративные методы (Якоби)

- tasks/mpi/korovin_n_line_topology/func_tests/main.cpp
- tasks/mpi/korovin_n_line_topology/include/ops_mpi.hpp
- tasks/mpi/korovin_n_line_topology/perf_tests/main.cpp
- tasks/mpi/korovin_n_line_topology/src/ops_mpi.cpp
В данной задаче необходимо реализовать передачу данных, используя топологию сети "Линейка". В этой топологии каждый процесс связан только с соседними процессами, что обеспечивает простую последовательность передачи данных. Например, от процесса 0 к процессу 1, от процесса 1 к процессу 2, и так далее, до процесса n
- Данные должны дойти до получателя без повреждений и изменений
- Выполнить требование — поддержка передачи данных при большой нагрузке, то есть при участии большого количества процессов
- Реализовать возможность передачи данных от любого выбранного процесса-отправителя к любому другому процессу-получателю в пределах одного коммуникатора
**pre_processing**
- Выбирается отправитель **root** и получатель **dst**, задается количество передаваемых данных **n**
- Отправитель …
> Коровин Никита. Задача 2. Вариант 10. Топология сети передачи данных - "Линейка".

- tasks/mpi/kondratev_ya_contrast_adjustment/func_tests/main.cpp
- tasks/mpi/kondratev_ya_contrast_adjustment/include/ops_mpi.hpp
- tasks/mpi/kondratev_ya_contrast_adjustment/perf_tests/main.cpp
- tasks/mpi/kondratev_ya_contrast_adjustment/src/ops_mpi.cpp
- tasks/seq/kondratev_ya_contrast_adjustment/func_tests/main.cpp
- tasks/seq/kondratev_ya_contrast_adjustment/include/ops_seq.hpp
- tasks/seq/kondratev_ya_contrast_adjustment/perf_tests/main.cpp
- tasks/seq/kondratev_ya_contrast_adjustment/src/ops_seq.cpp
Последовательное решение:
- Из `taskData` считывается массив струтур `Pixel`
- Вычисляется среднее значение цвета изображения по 3-м каналам
- Каждый канал каждого пикселя пересчитывается по формуле 
$$pixel.channel = constrast * (pixel.channel - average.channel) + average.channel$$
- Массив струтур `Pixel` записывается в `taskData`
Параллельное решение: 
- Из `taskData` считывается массив струтур `Pixel`
- Рассылается размер массива и коэффициент коррекции
- Процессы вычисляют размеры пакетов данных
- Пакеты данных рассылаются соответсвующим процессам
- Поканально вычисляются суммы значений локальных пакетов данных
- `all_reduce` вычисляет и рассылает процессам поканальные суммы значений
- Процессы по полученным суммам вычисляют средние значения
-  Каждый канал каждого пикселя в пакете …
> Кондратьев Ярослав. Задача 2. Вариант 27. Повышение контраста

- tasks/mpi/shurigin_s_vertikal_shema_mpi/func_tests/main.cpp
- tasks/mpi/shurigin_s_vertikal_shema_mpi/include/ops_mpi.hpp
- tasks/mpi/shurigin_s_vertikal_shema_mpi/perf_tests/main.cpp
- tasks/mpi/shurigin_s_vertikal_shema_mpi/src/ops_mpi.cpp
- tasks/seq/shurigin_s_vertikal_shema/func_tests/main.cpp
- tasks/seq/shurigin_s_vertikal_shema/include/ops_seq.hpp
- tasks/seq/shurigin_s_vertikal_shema/perf_tests/main.cpp
- tasks/seq/shurigin_s_vertikal_shema/src/ops_seq.cpp
1. Последовательная версия алгоритма Реализация стандартного умножения матрицы на вектор: для каждой строки матрицы вычисляется скалярное произведение с вектором.
2. Параллельная версия алгоритма (Вертикальная схема) Основные этапы:
2.1. Инициализация данных
- Главный процесс (rank 0) получает матрицу m×n и вектор n
- Вычисляет распределение столбцов между процессами
- Создает массивы sizes и displs для распределения данных
2.2. Распределение работы
- Broadcast вектора всем процессам
- Каждый процесс получает свой набор столбцов матрицы
- Неиспользуемые процессы (при num_proc > cols) помечаются (size = 0, displacement = -1)
2.3. Вычисления
- Каждый процесс обрабатывает свои столбцы
- Вычисляет частичные суммы произведений для каждой строки
- Использует row-major порядок для доступа к …
> Шурыгин Сергей. Задача №2. Вариант №16. Ленточная вертикальная схема

- tasks/mpi/drozhdinov_d_gauss_vertical_scheme/func_tests/main.cpp
- tasks/mpi/drozhdinov_d_gauss_vertical_scheme/include/ops_mpi.hpp
- tasks/mpi/drozhdinov_d_gauss_vertical_scheme/perf_tests/main.cpp
- tasks/mpi/drozhdinov_d_gauss_vertical_scheme/src/ops_mpi.cpp
- tasks/seq/drozhdinov_d_gauss_vertical_scheme/func_tests/main.cpp
- tasks/seq/drozhdinov_d_gauss_vertical_scheme/include/ops_seq.hpp
- tasks/seq/drozhdinov_d_gauss_vertical_scheme/perf_tests/main.cpp
- tasks/seq/drozhdinov_d_gauss_vertical_scheme/src/ops_seq.cpp
Прямой ход метода Гаусса: на каждом шаге выбирается ведущий (`major`) элемент, другие элементы строки делятся на него, производятся элементарные преобразования со строками матрицы и со столбцом свободных членов. 
Обратный ход метода Гаусса: для каждой строки от последней к первой вычисляется значение переменной.
Используется вертикальная схема разделения данных (по столбцам матрицы), каждый процесс получает блок столбцов, остаток делится между процессами с меньшим рангом(при необходимости). Каждый процесс локально ищет максимальный элемент в столбцах, которые он обрабатывает, и передаёт результат через `all_reduce` для определения глобального максимума. С помощью `broadcast` рассылаются коэффициенты для элементарных преобразований и порядок использования строк. В обратном ходе каждый …
> Дрождинов Дмитрий. Задача 2. Вариант 20. Метод Гаусса – ленточная вертикальная схема.

- tasks/mpi/sorokin_a_producer_consumer/func_tests/main.cpp
- tasks/mpi/sorokin_a_producer_consumer/include/ops_mpi.hpp
- tasks/mpi/sorokin_a_producer_consumer/perf_tests/main.cpp
- tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
В тесте создаётся вектор значений от 1 до n, где n это число процессов производителей. В целом по условию задачи эти значения могут быть произвольные, но для удобства запишем так. После чего вектор разбивается на кусочки по одному элементу и раздаётся процессам производителям. Сам алгоритм основан на буфере состоящем из одного элемента. Туда записывается значение процессами производителями и подаётся сигнал какой именно процесс потребитель должен считать это значение. Каждый процесс делает запросы буферу с определённой периодичностью, а когда все потребители получат свои данные, то процесс прекращается. На выходе должен получиться точно такой же массив какой мы отправили на вход.
> Сорокин Андрей. Задача 2. Вариант 1. Производители-потребители

- tasks/mpi/milovankin_m_hypercube_topology/func_tests/main.cpp
- tasks/mpi/milovankin_m_hypercube_topology/include/ops_mpi.hpp
- tasks/mpi/milovankin_m_hypercube_topology/perf_tests/main.cpp
- tasks/mpi/milovankin_m_hypercube_topology/src/ops_mpi.cpp
**_Параллельная задача_**
- Начальный процесс получает данные в виде структуры `DataIn`, вычисляет следующий процесс в пути, добавляет его в `route` и отправляет данные ему. 
- Все остальные процессы вызывают `recv`.
- Промежуточные процессы принимают данные, записывают ID следующего процесса в `route` и отправляют данные дальше.
- Следующий процесс вычисляется переворачивая 1 бит, чтобы он совпал с битом в ID цели.
- Последний процесс после получения данных отправляет их обратно в начальный процесс, чтобы корректно завершить работу неиспользованных процессов и записать результаты в `TaskData`.
- Начальный процесс проходит по `route` и отправляет сигнал завершения процессам, которых в нем нет.
> Милованкин Максим. Задача 2. Вариант 14. Топология Гиперкуб.

- tasks/mpi/vedernikova_k_star_topology_mpi/func_tests/main.cpp
- tasks/mpi/vedernikova_k_star_topology_mpi/include/ops_mpi.hpp
- tasks/mpi/vedernikova_k_star_topology_mpi/perf_tests/main.cpp
- tasks/mpi/vedernikova_k_star_topology_mpi/src/ops_mpi.cpp
**Алгоритм**: процесс, у которого `rank == 0`, принимается за концентратор, остальные - узлы (`nodes`). Процессы посылают концентратору ранг процесса-получателя и данные. После получения коммуникатор отправляет процессу-получателю данные и номер процесса, от которого он должен получить данные. После завершения работы каждому узлу отправляется в качестве ранга процесса-отправителя специальное значение `Term`, запрашивающее завершение работы.
> Ведерникова Ксения. Задача 2. Вариант 12. Топология сети "Звезда".

- tasks/mpi/kudryashova_i_gather my/func_tests/GatherMyMPIFuncTests.cpp
- tasks/mpi/kudryashova_i_gather my/include/GatherMyMPI.hpp
- tasks/mpi/kudryashova_i_gather my/perf_tests/GatherMyMPIPerfTests.cpp
- tasks/mpi/kudryashova_i_gather my/src/GatherMyMPI.cpp
- tasks/mpi/kudryashova_i_gather/func_tests/GatherMPIFuncTests.cpp
- tasks/mpi/kudryashova_i_gather/include/GatherMPI.hpp
- tasks/mpi/kudryashova_i_gather/perf_tests/GatherMPIPerfTests.cpp
- tasks/mpi/kudryashova_i_gather/src/GatherMPI.cpp
Реализована функция gather. В качестве рассматриваемой задачи мною была выбрана задача скалярного произведения векторов.
Для начала корневой процесс распределяет данные между остальными процессами. Каждый процесс получает свой сегмент данных, выполняет поэлементное умножение векторов и суммирует результаты. Таким образом, мы получили локальные результаты. После этого вступает в работу функция gather_my(), которая реализована по принципу двоичного дерева. Мы представляем все процессы в качестве дерева и начинаем просматривать его начиная от "листьев", в направлении "корня".  Локальные результаты, которые получили дочерние процессы, переходят "родителям", от них далее и так вплоть до корневого процесса, где значения собираются в вектор. В конце корневой процесс суммирует все полученные …
> Кудряшова Ирина. Задача 2. Вариант 9. Обобщенная передача от всех одному (gather)

- tasks/mpi/volochaev_s_vertical_ribbon_scheme_16/func_tests/main.cpp
- tasks/mpi/volochaev_s_vertical_ribbon_scheme_16/include/ops_mpi.hpp
- tasks/mpi/volochaev_s_vertical_ribbon_scheme_16/perf_tests/main.cpp
- tasks/mpi/volochaev_s_vertical_ribbon_scheme_16/src/ops_mpi.cpp
- tasks/seq/volochaev_s_vertical_ribbon_scheme_16/func_tests/main.cpp
- tasks/seq/volochaev_s_vertical_ribbon_scheme_16/include/ops_seq.hpp
- tasks/seq/volochaev_s_vertical_ribbon_scheme_16/perf_tests/main.cpp
- tasks/seq/volochaev_s_vertical_ribbon_scheme_16/src/ops_seq.cpp
Последовательный вариант:
подается матрица А и вектор В. Перемножаем обычным алгоритмом. Проходимся по всем строкам матрицы А, умножаем на вектор В и складываем в res.
Параллельный вариант:
Разделим матрицу А на "ленты". Каждая лента будет отослана своему потоку вместе с вектором В. Далее выполняем подзадачу умножения "ленты" на вектор и складываем скалярно с res.
> Волочаев Серафим Задача 2. Вариант 16: Ленточная вертикальная схема

- tasks/mpi/sarafanov_m_gauss_jordan_method/func_tests/main.cpp
- tasks/mpi/sarafanov_m_gauss_jordan_method/include/ops_mpi.hpp
- tasks/mpi/sarafanov_m_gauss_jordan_method/perf_tests/main.cpp
- tasks/mpi/sarafanov_m_gauss_jordan_method/src/ops_mpi.cpp
- tasks/seq/sarafanov_m_gauss_jordan_method/func_tests/main.cpp
- tasks/seq/sarafanov_m_gauss_jordan_method/include/ops_seq.hpp
- tasks/seq/sarafanov_m_gauss_jordan_method/perf_tests/main.cpp
- tasks/seq/sarafanov_m_gauss_jordan_method/src/ops_seq.cpp
Этот репозиторий реализует параллельный и последовательный метод Гаусса-Жордана для решения систем линейных уравнений.
MPI реализация: использует библиотеку MPI для распределения вычислений между процессами, оптимизируя обработку матрицы на этапах разложения и преобразования. Обеспечивает параллельное обновление матрицы и сбор результатов, сокращая время выполнения.
SEQ реализация: выполняет тот же алгоритм последовательно без параллелизма. Проста в реализации и используется для сравнения производительности с MPI-версией.
> Сарафанов Максим. Задача 2 вариант 21 Метод Гаусса-Жордана

- tasks/mpi/kalyakina_a_producers_consumers/func_tests/main.cpp
- tasks/mpi/kalyakina_a_producers_consumers/include/ops_mpi.hpp
- tasks/mpi/kalyakina_a_producers_consumers/perf_tests/main.cpp
- tasks/mpi/kalyakina_a_producers_consumers/src/ops_mpi.cpp
В данной реализации есть три вида процессов:
1. **Менеджер по работе с буфером** – это всегда нулевой процесс, он принимает сообщения с данными от производителей, записывая значение в буфер, и отправляет сообщения потребителям, когда те готовы их обработать. Данный процесс также является производителем.
2. **Производители** – процессы, выполняющие некоторую работу по созданию данных.
3. **Потребители** – процессы, обрабатывающие созданные данные.
Количество производителей и, как следствие, потребителей (зависит от количества производителей) определяется входными параметрами, как и количество ресурсов, которые нужно создать и обработать, и размер буфера.
> Калякина Анастасия. Задача 2. Вариант 1. Задача "Производители-потребители"

- tasks/mpi/komshina_d_grid_torus_topology/func_tests/main.cpp
- tasks/mpi/komshina_d_grid_torus_topology/include/ops_mpi.hpp
- tasks/mpi/komshina_d_grid_torus_topology/perf_tests/main.cpp
- tasks/mpi/komshina_d_grid_torus_topology/src/ops_mpi.cpp
Алгоритм решетка-тор работает в распределенной системе, где каждый узел общается с четырьмя соседями (слева, справа, сверху и снизу) с учетом периодической (топорной) связи между ними. Он выполняет несколько этапов: проверяет корректность данных, обменивается информацией между узлами и обрабатывает данные после обмена. Всё это происходит параллельно с использованием MPI для эффективной работы в многозадачной среде. При этом система использует квадратную сетку процессов, то есть количество процессов должно быть полным квадратом, чтобы правильно распределить процессы по двумерной решетке.
> Комшина Дарья. Задача 2. Вариант 13. Топология сети передачи данных решетка-тор.

- tasks/mpi/lopatin_i_strip_horizontal_scheme/func_tests/stripHorizontalSchemeFuncTestsMPI.cpp
- tasks/mpi/lopatin_i_strip_horizontal_scheme/include/stripHorizontalSchemeHeaderMPI.hpp
- tasks/mpi/lopatin_i_strip_horizontal_scheme/perf_tests/stripHorizontalSchemePerfTestsMPI.cpp
- tasks/mpi/lopatin_i_strip_horizontal_scheme/src/stripHorizontalSchemeMPI.cpp
- tasks/seq/lopatin_i_strip_horizontal_scheme/func_tests/stripHorizontalSchemeFuncTestsSeq.cpp
- tasks/seq/lopatin_i_strip_horizontal_scheme/include/stripHorizontalSchemeHeaderSeq.hpp
- tasks/seq/lopatin_i_strip_horizontal_scheme/perf_tests/stripHorizontalSchemePerfTestsSeq.cpp
- tasks/seq/lopatin_i_strip_horizontal_scheme/src/stripHorizontalSchemeSeq.cpp
- seq
1. using an outer loop we go through the rows of the matrix
2. we go through the columns with an inner loop
3. inside loops, we calculate the element of the resulting vector by summing the multiplied rows of the matrix by the vector
- mpi
1. send matrix and vector sizes
2. determine strip size for each process
3. allocating memory for the local part of the matrix and local vector for each process
4. sending local vector to processes
5. sending parts of the matrix to processes
6. calculate the local result
7. collecting results
> Лопатин Илья. Задача 2. Вариант 15. Ленточная горизонтальная схема.

- tasks/mpi/bessonov_e_star_topology/func_tests/main.cpp
- tasks/mpi/bessonov_e_star_topology/include/ops_mpi.hpp
- tasks/mpi/bessonov_e_star_topology/perf_tests/main.cpp
- tasks/mpi/bessonov_e_star_topology/src/ops_mpi.cpp
Главный процесс (ранг 0) играет роль центрального узла, который последовательно обменивается данными с остальными процессами:
Выполняет отправку данных всем остальным узлам в сети.
Получает ответ от каждого узла после отправки данных.
Остальные узлы:
Получают данные только от центрального узла.
Отправляют ответ обратно центральному узлу
Порядок обхода (traversal_order_) используется для отслеживания последовательности взаимодействий.
Например:
Если есть 3 узла (0, 1, 2), то порядок обхода: [0, 1, 0, 2, 0]
> Бессонов Егор. Задача 2. Вариант 12. Топология сетей передачи данных - Звезда

- tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
- tasks/mpi/voroshilov_v_torus_grid/include/ops_mpi.hpp
- tasks/mpi/voroshilov_v_torus_grid/perf_tests/main.cpp
- tasks/mpi/voroshilov_v_torus_grid/src/ops_mpi.cpp
Реализовать с помощью MPI программу, в которой несколько процессов взаимодействуют между собой исключительно в рамках виртуальной топологии "решётка-тор". В рамках этой топологии процессы выстраиваются в квадратную сетку (задача актуальна только для количества процессов равного `n^2`, где n - натуральное число).
В этой сетке каждый процесс может обмениваться данными не более чем с четырьмя своими соседями (с верхним и нижним, с левым и правым), при этом сетка зациклена (существует связь между первым и последним процессами в строке, между первым и последним процессами в столбце).
Цель - передать некоторый буфер данных от процесса-источника процессу-приёмнику, проверить на приёмнике корректность дошедших данных и при этом приёмник должен получить вектор пути, по которому эти данные прошли и …
> Ворошилов Виталий. Задача 2. Вариант 13. Топология сетей передачи данных "Решётка-тор"

- tasks/mpi/kozlova_e_jacobi_method/func_tests/main.cpp
- tasks/mpi/kozlova_e_jacobi_method/include/ops_mpi.hpp
- tasks/mpi/kozlova_e_jacobi_method/perf_tests/main.cpp
- tasks/mpi/kozlova_e_jacobi_method/src/ops_mpi.cpp
- tasks/seq/kozlova_e_jacobi_method/func_tests/main.cpp
- tasks/seq/kozlova_e_jacobi_method/include/ops_seq.hpp
- tasks/seq/kozlova_e_jacobi_method/perf_tests/main.cpp
- tasks/seq/kozlova_e_jacobi_method/src/ops_seq.cpp
Система линейных уравнений представляется следующим образом: 
_Ax=B_, 
где _A_ — это матрица коэффициентов, _B_ — вектор правых частей, а _x_ — искомый вектор решений. В этой версии алгоритм выполняет итерации в одном процессе, последовательно вычисляя новые приближения для каждого элемента вектора решения по следующей формуле: 
На каждой итерации вычисляется разница между текущим и предыдущим вектором решения, и процесс продолжается до тех пор, пока эта разница не станет меньше заданной точности _eps_.  Также проверяется, что на главной диагонали матрицы _A_ нет нулевых элементов, так как это сделает метод Якоби неприменимым.
Алгоритм выполняет аналогичные действия, что и в последовательной версии, но с распределением вычислений между процессами. Каждый процесс обрабатывает определённый …
> Козлова Екатерина. Задача 2. Вариант 22. Итеративные методы (Якоби)

- tasks/mpi/polikanov_v_gauss_band_columns/func_tests/main.cpp
- tasks/mpi/polikanov_v_gauss_band_columns/include/ops_mpi.hpp
- tasks/mpi/polikanov_v_gauss_band_columns/perf_tests/main.cpp
- tasks/mpi/polikanov_v_gauss_band_columns/src/ops_mpi.cpp
- tasks/seq/polikanov_v_gauss_band_columns/func_tests/main.cpp
- tasks/seq/polikanov_v_gauss_band_columns/include/ops_seq.hpp
- tasks/seq/polikanov_v_gauss_band_columns/perf_tests/main.cpp
- tasks/seq/polikanov_v_gauss_band_columns/src/ops_seq.cpp
Последовательная версия метода Гаусса с использованием ленточной структуры столбцов:
- **Валидация**: Проверяет корректность входных данных (размеры матрицы и число уравнений).
- **Предобработка**: Преобразует входные данные в формат матрицы и подготавливает буферы для ответов.
- **Выполнение**: 
- На каждой итерации выделяется подматрица для обработки текущей полосы.
- Вычисляются множители для исключения неизвестных.
- Применяются преобразования Гаусса.
- Проводится обратная подстановка для нахождения ответа.
- **Постобработка**: Результаты вычислений записываются в буфер выходных данных.
Параллельная версия метода Гаусса с использованием MPI для распараллеливания:
- **Валидация**: Проверяет входные данные аналогично последовательной версии.
- **Предобработка**: 
- Подготавливает …
> Поликанов Виталий. Задача 2. Вариант 20. Решение СЛАУ - "Метод Гаусса – ленточная вертикальная схема"

- tasks/mpi/kavtorev_d_iterative_jacobi/func_tests/main.cpp
- tasks/mpi/kavtorev_d_iterative_jacobi/include/ops_mpi.hpp
- tasks/mpi/kavtorev_d_iterative_jacobi/perf_tests/main.cpp
- tasks/mpi/kavtorev_d_iterative_jacobi/src/ops_mpi.cpp
- tasks/seq/kavtorev_d_iterative_jacobi/func_tests/main.cpp
- tasks/seq/kavtorev_d_iterative_jacobi/include/ops_seq.hpp
- tasks/seq/kavtorev_d_iterative_jacobi/perf_tests/main.cpp
- tasks/seq/kavtorev_d_iterative_jacobi/src/ops_seq.cpp
Итерационный метод Якоби предназначен для решения систем уравнений вида \(AX = F\), где:  
- \(A\) — квадратная матрица коэффициентов (N*N),  
- \(X\) — вектор неизвестных,  
- \(F\) — вектор свободных членов.  
Метод представлен в двух вариантах: **последовательном** и **параллельном** (с использованием MPI).
---
1. **Подготовка данных**:
- Считываются:
- Матрица \(A\),
- Вектор \(F\),
- Точность \(\varepsilon\),
- Максимальное количество итераций.
- Проверяются входные данные:
- Матрица \(A\) должна быть квадратной и диагонально преобладающей.
- Диагональные элементы \(A\) не должны быть равны нулю.
- Данные проверяются на отсутствие значений \(NaN\) и бесконечностей.
2. **Итерационный процесс**:
- Для каждой строки \(i\) рассчитывается новое значение \(x_i\).
- После каждой итерации …
> Кавторев Дмитрий. Задача 2. Вариант 22. Итеративные методы (Якоби)

- tasks/mpi/anikin_m_contrastscale/func_tests/main.cpp
- tasks/mpi/anikin_m_contrastscale/include/ops_mpi.hpp
- tasks/mpi/anikin_m_contrastscale/perf_tests/main.cpp
- tasks/mpi/anikin_m_contrastscale/src/ops_mpi.cpp
- tasks/seq/anikin_m_contrastscale/func_tests/main.cpp
- tasks/seq/anikin_m_contrastscale/include/ops_seq.hpp
- tasks/seq/anikin_m_contrastscale/perf_tests/main.cpp
- tasks/seq/anikin_m_contrastscale/src/ops_seq.cpp
Секвентальный алгоритм:
1. Считаем среднюю яркость изображения
2. Яркость одного пикселя вычисляется по формуле (valueR * 0.299 + valueG * 0.587 + valueB * 0.114);
3. Создаем массив данных содержащее 256 значений, эти значения значат то как определенное значение канала меняется при повышении контраста (newrgb[256])
for (int i = 0; i < 256; i++)
{
int delta = (int)i - lAB;
int temp  = (int)(lAB + k *delta);
if (temp < 0)
temp = 0;
if (temp >= 255)
temp = 255;
newrgb[i] = (unsigned char)temp;
}
5. Используя вычеслиненные значения конвертируем исходные значения в результат.
MPI алгоритм:
Разделяем исходный массив на кол-во процессов. Запускаем для каждого фрагмента секвентальный алгоритм
> Аникин Максим. Задача 2. Вариант 27. Повышение контраста.

- tasks/mpi/lysov_i_simple_iteration_method/func_tests/main.cpp
- tasks/mpi/lysov_i_simple_iteration_method/include/ops_mpi.hpp
- tasks/mpi/lysov_i_simple_iteration_method/perf_tests/main.cpp
- tasks/mpi/lysov_i_simple_iteration_method/src/ops_mpi.cpp
- tasks/seq/lysov_i_simple_iteration_method/func_tests/main.cpp
- tasks/seq/lysov_i_simple_iteration_method/include/ops_seq.hpp
- tasks/seq/lysov_i_simple_iteration_method/perf_tests/main.cpp
- tasks/seq/lysov_i_simple_iteration_method/src/ops_seq.cpp
В последовательной версии используется метод run() класса SlaeIterationTask, который решает систему линейных алгебраических уравнений (СЛАУ) методом простой итерации с заданной точностью.
1. Валидация и подготовка данных:  
Метод validation() проверяет корректность входных данных, включая размеры матрицы коэффициентов A, вектора правых частей b и вектора решений x.
2. Преобразование системы:  
Метод transformSystem() приводит СЛАУ к итерационной форме с матрицей B и вектором g, проверяя наличие нулевых диагональных элементов.
3. Проверка сходимости:  
Метод isDiagonallyDominant() проверяет матрицу на строгое диагональное доминирование для обеспечения сходимости метода.
4. Решение СЛАУ:  
Метод run() выполняет итерации до достижения заданной точности tolerance_ или максимального числа …
> Лысов Иван. Задача 2. Вариант 24. Метод простой итерации.

- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_mpi.hpp
- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_seq.hpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_seq.cpp
Алгоритм состоит из двух этапов: прямой ход и обратный ход.
**Этап 1: Прямой ход**
Для всех строк от i=0 до n-1 (перебираем ведущие строки):
1. Для всех строк от i=k+1 до n:
- Вычисляем множитель: m_ik=A[k,i]/(A[i,i]) ;
- Обновляем элементы строки i от j=i до n+1: A[k,j]=A[k,j]− A[i,j]⋅m_ik
После выполнения прямого хода матрица становится верхнетреугольной.
**Этап 2: Обратный ход**
Для всех строк от i=n−1 до 0 (в обратном порядке):
1. Находим свободный член b= A[i,n];
2. Находим значение очередной неизвестной, используя предыдущие:
- Вычитаем из свободного члена сумму: ∑_(j=i+1)^n▒〖A[i,j]∙x[j]〗 ;
- Получившееся выражение делим на диагональный элемент: x[i]=b/(A[i,i]);
После выполнения обратного хода получаем значения всех неизвестных.
**Описание MPI …
> Созонов Илья. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.

- tasks/mpi/dormidontov_e_circle_topology/func_tests/dect_main.cpp
- tasks/mpi/dormidontov_e_circle_topology/include/dect_ops_mpi.hpp
- tasks/mpi/dormidontov_e_circle_topology/perf_tests/dect_main.cpp
- tasks/mpi/dormidontov_e_circle_topology/src/dect_ops_mpi.cpp
Задача 11 Топология кольцо
Задача заключается в том, чтобы пройти по всем потокам и передать в массив номера посещённых рангов.
То есть мы начинаем в 0 ранге и кладём 0 ранг, идём в 1 , кладём 1 и так далее.В конце мы возвращаемся в 0 процесс и складываем 0.
> Дормидонтов Егор.Задача 2.Вариант 11.Топология кольцо

- tasks/mpi/pikarychev_i_sleeping_barber/func_tests/main.cpp
- tasks/mpi/pikarychev_i_sleeping_barber/include/ops_mpi.hpp
- tasks/mpi/pikarychev_i_sleeping_barber/src/ops_mpi.cpp
Проблема спящего брадобрея — классическая задача синхронизации и межпроцессного взаимодействия interprocess communication в многозадачной операционной системе. Проблема заключается в обеспечении того, чтобы парикмахер работал, когда есть клиенты, и отдыхал, когда клиентов нет. 
В силу отсутствия в MPI разделяемой памяти для координации брадобрея и клиентов используется отдельный процесс. Он отрабатывает N итераций для получения данных, после чего сообщает остальным процессам специальный код, вызывающий их завершение.
> Пикарычев Илья. Задача 2. Вариант 4. Задача "Спящий брадобрей"  

- tasks/mpi/vershinina_a_image_smoothing/func_tests/main.cpp
- tasks/mpi/vershinina_a_image_smoothing/include/ops_mpi.hpp
- tasks/mpi/vershinina_a_image_smoothing/perf_tests/main.cpp
- tasks/mpi/vershinina_a_image_smoothing/src/ops_mpi.cpp
- tasks/seq/vershinina_a_image_smoothing/func_tests/main.cpp
- tasks/seq/vershinina_a_image_smoothing/include/ops_seq.hpp
- tasks/seq/vershinina_a_image_smoothing/perf_tests/main.cpp
- tasks/seq/vershinina_a_image_smoothing/src/ops_seq.cpp
Сглаживание изображения происходит путем нахождения среднего значения соседних пикселей и самого пикселя для каждого пикселя изображения. В параллельном решении матрица делится построчно в зависимости от числа процессов, строки отправляются каждому процессу с помощью scatterv, затем вычисляются значения и с помощью gatherv собирается ответ.
> Вершинина Александра. Задача 2. Вариант 26. Сглаживание изображения

- tasks/mpi/koshkin_m_dining_philosophers/func_tests/main.cpp
- tasks/mpi/koshkin_m_dining_philosophers/include/ops_mpi.hpp
- tasks/mpi/koshkin_m_dining_philosophers/perf_tests/main.cpp
- tasks/mpi/koshkin_m_dining_philosophers/src/ops_mpi.cpp
В данной реализации рассматривается классическая задача синхронизации в параллельных вычислениях — "Проблема обедающих философов". Она описывает ситуацию, в которой несколько философов (задач) сидят за круглым столом, чередуя размышления и прием пищи. Каждый философ может приступить к еде только после того, как завладеет двумя "вилками" (ресурсами), лежащими слева и справа от него. Проблема заключается в предотвращении взаимоблокировок (deadlocks), голодания задач (starvation) и обеспечении корректного взаимодействия при совместном использовании ресурсов.
> Кошкин Матвей. Задача 2. Вариант 3. Задача «Обедающие философы».

- tasks/mpi/mezhuev_m_lattice_torus/func_tests/main .cpp
- tasks/mpi/mezhuev_m_lattice_torus/func_tests/main.cpp
- tasks/mpi/mezhuev_m_lattice_torus/include/mpi.hpp
- tasks/mpi/mezhuev_m_lattice_torus/perf_tests/main.cpp
- tasks/mpi/mezhuev_m_lattice_torus/src/mpi.cpp
Алгоритм "решетка-тор" предназначен для выполнения вычислений в распределенной системе, где каждый узел взаимодействует с четырьмя соседними узлами (по горизонтали и вертикали), при этом используется периодическое соединение, замыкающее границы сетки. Работа алгоритма разделена на несколько этапов: валидация входных данных, обмен информацией между узлами и последующая обработка полученных данных. Все операции выполняются параллельно, а для координации узлов и оптимизации вычислений используется библиотека MPI, что обеспечивает эффективную работу в условиях многозадачности.
> Межуев Максим Задача 2 Вариант 13. Решетка-Тор

- tasks/mpi/ermolaev_v_multidimensional_integral_rectangle/func_tests/main.cpp
- tasks/mpi/ermolaev_v_multidimensional_integral_rectangle/include/ops_mpi.hpp
- tasks/mpi/ermolaev_v_multidimensional_integral_rectangle/perf_tests/main.cpp
- tasks/mpi/ermolaev_v_multidimensional_integral_rectangle/src/ops_mpi.cpp
- tasks/seq/ermolaev_v_multidimensional_integral_rectangle/func_tests/main.cpp
- tasks/seq/ermolaev_v_multidimensional_integral_rectangle/include/ops_seq.hpp
- tasks/seq/ermolaev_v_multidimensional_integral_rectangle/perf_tests/main.cpp
- tasks/seq/ermolaev_v_multidimensional_integral_rectangle/src/ops_seq.cpp
Программа реализует вычисление n-мерных интегралов методом средних прямоугольников.
Вычисление интеграла происходит до достижения заданной точности. Точность решения определяется по [правилу Рунге](https://ru.wikipedia.org/wiki/Правило_Рунге#Оценка_точности_вычисления_определённого_интеграла)
Параллелизм: диапазон значений (разница между пределами интегрирования) и количество точек разбиения внешнего интеграла разделяются на равные части между процессами. Вложенные интегралы полностью вычисляются на каждом процессе
Такое разбиение позволяет равномерно распределить вычислительную нагрузку между всеми процессами.
> Ермолаев Владислав. Задача 3. Вариант 7. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников).

- tasks/mpi/kapustin_i_bubble/func_tests/main.cpp
- tasks/mpi/kapustin_i_bubble/include/avg_mpi.hpp
- tasks/mpi/kapustin_i_bubble/perf_tests/main.cpp
- tasks/mpi/kapustin_i_bubble/src/avg_mpi.cpp
- tasks/seq/kapustin_i_bubble/func_tests/main.cpp
- tasks/seq/kapustin_i_bubble/include/avg_seq.hpp
- tasks/seq/kapustin_i_bubble/perf_tests/main.cpp
- tasks/seq/kapustin_i_bubble/src/avg_seq.cpp
Задача заключается в реализации параллельной версии алгоритма сортировки пузырьком.  Входной массив делится на части, которые обрабатываются разными процессами. Каждый процесс выполняет сортировку своей части массива, затем данные обмениваются между процессами для корректной сортировки на всем объеме. После нескольких этапов обмена процесс с рангом 0 собирает отсортированные части и формирует итоговый отсортированный массив.
> Капустин Иван Задача 2 Вариант 25 "пузырьковая" сортировка

- tasks/mpi/ermilova_d_custom_reduce/func_tests/main.cpp
- tasks/mpi/ermilova_d_custom_reduce/include/ops_mpi.hpp
- tasks/mpi/ermilova_d_custom_reduce/perf_tests/main.cpp
- tasks/mpi/ermilova_d_custom_reduce/src/ops_mpi.cpp
- tasks/mpi/ermilova_d_reduceMPI/func_tests/main.cpp
- tasks/mpi/ermilova_d_reduceMPI/include/ops_mpi.hpp
- tasks/mpi/ermilova_d_reduceMPI/perf_tests/main.cpp
- tasks/mpi/ermilova_d_reduceMPI/src/ops_mpi.cpp
- tasks/mpi/example/func_tests/main.cpp
Реализована функция reduce. В качестве рассматриваемой задачи используется задача нахождения минимума в матрице.
Корневой процесс разбивает матрицу на равные части. Каждый процесс получает свою часть матрицы, затем находит минимум в выделенной ему части, используя функцию CustomReduce. Функция реализована по принципу двоичного дерева, где процессы, начиная с листьев (процессов, которые обрабатывают отдельные части данных), постепенно сливаются с соседними процессами. На каждом шаге два процесса сливают свои результаты (минимумы), пока не будет найдено одно итоговое минимальное значение, которое будет у корневого процесса.
> Ермилова Дарья. Задача 2. Вариант 6. Передача от всех одному (reduce).

- tasks/mpi/chastov_v_bubble_sort/func_tests/main.cpp
- tasks/mpi/chastov_v_bubble_sort/include/ops_mpi.hpp
- tasks/mpi/chastov_v_bubble_sort/perf_tests/main.cpp
- tasks/mpi/chastov_v_bubble_sort/src/ops_mpi.cpp
- tasks/seq/chastov_v_bubble_sort/func_tests/main.cpp
- tasks/seq/chastov_v_bubble_sort/include/ops_seq.hpp
- tasks/seq/chastov_v_bubble_sort/perf_tests/main.cpp
- tasks/seq/chastov_v_bubble_sort/src/ops_seq.cpp
Задача заключается в реализации алгоритма пузырьковой сортировки в двух вариантах: последовательном (SEQUENTIAL) и параллельном (MPI), с применением объектно-ориентированного подхода и тестированием функциональности.
Алгоритм пузырьковой сортировки:
1) Последовательно сравнивает соседние элементы массива.
2) Меняет их местами, если порядок нарушен.
3) Повторяет проходы по массиву до полной упорядоченности.
Последовательная версия (SEQUENTIAL):
Выполняет сортировку на одном процессе, используя стандартные структуры данных и алгоритмы.
Параллельная версия (MPI):
1) Использует технологии параллельного программирования (MPI) для распределения данных между процессами.
2) Обеспечивает ускорение за счет одновременной обработки фрагментов массива.
Тестирование:
1) Включает сценарии с различными …
> Частов Вячеслав. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки).

- tasks/mpi/chernova_n_topology_ring/func_tests/main.cpp
- tasks/mpi/chernova_n_topology_ring/include/ops_mpi.hpp
- tasks/mpi/chernova_n_topology_ring/perf_tests/main.cpp
- tasks/mpi/chernova_n_topology_ring/src/ops_mpi.cpp
В топологии сетей передачи данных кольцо мы передаём данные потокам по порядку и возвращаемся в исходный поток (0 - 1 - 2 - 3 - ... - n - 0).  Вектор output_ хранит в себе передаваемые данные, а вектор process_ - номера процессов, которым мы передавали данные (нужен для проверки корректности работы алгоритма).
> Чернова Наталья. Задача 2. Вариант 11. Топология сетей передачи данных кольцо

- tasks/mpi/shlyakov_m_allreduce/func_tests/main.cpp
- tasks/mpi/shlyakov_m_allreduce/include/ops_mpi.hpp
- tasks/mpi/shlyakov_m_allreduce/perf_tests/main.cpp
- tasks/mpi/shlyakov_m_allreduce/src/ops_mpi.cpp
**1. Последовательная версия:**
1. Найти минимальный элемент матрицы.
2. Подсчитать количество вхождений минимального элемента в каждую строку.
**2. MPI версия (два этапа):**
Этап 1 (Нахождение минимума):
1. Разделить матрицу между процессами.
2. Каждый процесс находит минимум в своей части матрицы.
3. Сравнить все найденные минимумы и определить глобальный минимум.
4. Разослать глобальный минимум всем процессам.
Этап 2 (Подсчет вхождений):
1. Каждый процесс подсчитывает количество вхождений глобального минимума в своих строках.
2. Сохранить результаты подсчета в локальный массив.
3. Объединить результаты всех процессов, получив итоговый массив с количеством вхождений минимума в каждой строке.
**3. Реализация all_reduce:**
1. Каждый процесс инициализирует результат входными данными.
2. …
> Шляков Максим. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce)

- tasks/mpi/sorokin_a_producer_consumer/src/ops_mpi.cpp
Исправление на неблокирующие функции.
> Исправление на isend и irecv. Сорокин Андрей. Задача 2. Вариант 1. Производители-потребители

- tasks/mpi/zaytsev_topology_star/func_tests/main.cpp
- tasks/mpi/zaytsev_topology_star/include/ops_mpi.hpp
- tasks/mpi/zaytsev_topology_star/perf_tests/main.cpp
- tasks/mpi/zaytsev_topology_star/src/ops_mpi.cpp
1. 0 процесс отправляет данные каждому процессу
2. Каждый процесс получает данные и отправляет их обратно 0 процессу
3. Для проверки, мы добавляем траекторию, и то есть когда начинает работать какой-то процесс, то мы записываем его номер в траекторию.
> Зайцев Денис. Задача 2. 12 вариант. Топология сетей - звезда

- tasks/mpi/tarakanov_d_ring_topology/func_tests/main.cpp
- tasks/mpi/tarakanov_d_ring_topology/include/ops_mpi.hpp
- tasks/mpi/tarakanov_d_ring_topology/perf_tests/main.cpp
- tasks/mpi/tarakanov_d_ring_topology/src/ops_mpi.cpp
Моя программа реализует обмен данными между процессами в сети с топологией "Кольцо" с использованием библиотеки MPI. Главный процесс (ранг 0) инициализирует входные данные, которые затем передаются следующему процессу в кольце. Каждый процесс принимает данные от предыдущего, при необходимости обрабатывает их и отправляет следующему. Последний процесс завершает цикл, возвращая данные обратно главному процессу.
Для передачи данных используются функции send и recv, которые обеспечивают передачу размера буфера и самих данных. Если программа запускается с одним процессом, обмен не выполняется, чтобы избежать излишней обработки. После завершения обмена главный процесс копирует полученные данные в выходной буфер для дальнейшей обработки.
>  Тараканов Денис. Задача 2. Вариант 11. Топология сети Кольцо

- tasks/mpi/korneeva_e_average_of_vector_elements/func_tests/main.cpp
- tasks/mpi/korneeva_e_average_of_vector_elements/include/ops_mpi.hpp
- tasks/mpi/korneeva_e_average_of_vector_elements/perf_tests/main.cpp
- tasks/mpi/korneeva_e_average_of_vector_elements/src/ops_mpi.cpp
**Последовательная версия:** В этом алгоритме все элементы вектора суммируются на одном процессе, и полученная сумма делится на количество элементов, чтобы вычислить среднее значение.
**MPI-версия:** В этой версии данные распределяются между несколькими процессами. Каждый процесс вычисляет сумму своей части вектора. После этого все результаты объединяются с помощью операции `MPI_Allreduce`, и только корневой процесс вычисляет итоговое среднее значение.
**Реализация allreduce:** Для реализации операции `allreduce` использована структура бинарного дерева. Каждый процесс отправляет свою часть суммы родительскому процессу в дереве. Вершины дерева постепенно объединяют результаты, и в конце итоговое значение среднего передается всем процессам.
> Корнеева Екатерина. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce)

- tasks/mpi/ermolaev_v_allreduce_my/include/test_funcs.hpp
> [FIX] removed logs from CI

- tasks/mpi/ivanov_m_gauss_horizontal/func_tests/main.cpp
- tasks/mpi/ivanov_m_gauss_horizontal/include/ops_mpi.hpp
- tasks/mpi/ivanov_m_gauss_horizontal/perf_tests/main.cpp
- tasks/mpi/ivanov_m_gauss_horizontal/src/ops_mpi.cpp
- tasks/seq/ivanov_m_gauss_horizontal/func_tests/main.cpp
- tasks/seq/ivanov_m_gauss_horizontal/include/ops_seq.hpp
- tasks/seq/ivanov_m_gauss_horizontal/perf_tests/main.cpp
- tasks/seq/ivanov_m_gauss_horizontal/src/ops_seq.cpp
**Входные данные:**
- расширенная матрица (матрица коэффициентов и вектор решения)
- количество уравнений в системе (количество строк)
**Последовательная версия:**
Прямой ход:
- На каждой итерации:
- - поиск максимального элемента (опорного элемента) в опорном стобце
- - если максимальный элемент находится не на опорной строке, меняем местами опорную строку и строку с максимальным элементом
- - делим все элементы опорной строки на опорный элемент
- - вычитаем из каждой строки ниже опорной опорную строку, умноженную на элемент с координатами (номер строки, номер опорного столбца)
Обратный ход:
- Во время хода с последней строки к первой последовательно получаем значение решения с индексом строки
**Параллельная версия:**
Прямой ход:
- На каждой итерации:
- - поиск максимального элемента …
> Иванов Михаил. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.

- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_mpi.hpp
- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_seq.hpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_seq.cpp
Алгоритм состоит из двух этапов: прямой ход и обратный ход.
**Этап 1: Прямой ход**
Для всех строк от i=0 до n-1 (перебираем ведущие строки):
1. Для всех строк от i=k+1 до n:
- Вычисляем множитель: m_ik=A[k,i]/(A[i,i]) ;
- Обновляем элементы строки i от j=i до n+1: A[k,j]=A[k,j]− A[i,j]⋅m_ik
После выполнения прямого хода матрица становится верхнетреугольной.
**Этап 2: Обратный ход**
Для всех строк от i=n−1 до 0 (в обратном порядке):
1. Находим свободный член b= A[i,n];
2. Находим значение очередной неизвестной, используя предыдущие:
- Вычитаем из свободного члена сумму: ∑_(j=i+1)^n▒〖A[i,j]∙x[j]〗 ;
- Получившееся выражение делим на диагональный элемент: x[i]=b/(A[i,i]);
После выполнения обратного хода получаем значения всех неизвестных.
**Описание MPI …
> Fix Revert. Созонов Илья. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема.

- tasks/mpi/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
- tasks/mpi/sozonov_i_nearest_neighbor_elements/include/ops_mpi.hpp
- tasks/mpi/sozonov_i_nearest_neighbor_elements/perf_tests/main.cpp
- tasks/mpi/sozonov_i_nearest_neighbor_elements/src/ops_mpi.cpp
- tasks/seq/sozonov_i_nearest_neighbor_elements/func_tests/main.cpp
- tasks/seq/sozonov_i_nearest_neighbor_elements/include/ops_seq.hpp
- tasks/seq/sozonov_i_nearest_neighbor_elements/perf_tests/main.cpp
- tasks/seq/sozonov_i_nearest_neighbor_elements/src/ops_seq.cpp
**Описание последовательной задачи:**
1. Создаём переменную min и инициализируем её максимальным возможным значением INT_MAX.
2. Проходим по вектору, начиная с первого элемента до предпоследнего, и находим модуль разности между текущим элементом и следующим за ним.
3. Если модуль разности между ними меньше текущего значения min, обновляем min и запоминаем индекс текущего элемента вектора.
**Описание MPI задачи:**
1. Создаем новый вектор diff, состоящий из пар: модуль разности соседних элементов исходного вектора и соответствующего индекса.
2. Полученный вектор пар делится равномерно на сегменты по числу процессов.
3. Каждый сегмент данных отправляется от нулевого процесса остальным.
4. Каждый процесс находит наименьший элемент и соответствующий ему индекс в полученном сегменте данных.
5. …
> Fix Revert. Созонов Илья. Задача 1. Вариант 7. Нахождение наиболее близких соседних элементов вектора.

- tasks/mpi/durynichev_d_allreduce/func_tests/main.cpp
- tasks/mpi/durynichev_d_allreduce/include/ops_mpi.hpp
- tasks/mpi/durynichev_d_allreduce/perf_tests/main.cpp
- tasks/mpi/durynichev_d_allreduce/src/ops_mpi.cpp
- tasks/mpi/durynichev_d_custom_allreduce/func_tests/main.cpp
- tasks/mpi/durynichev_d_custom_allreduce/include/ops_mpi.hpp
- tasks/mpi/durynichev_d_custom_allreduce/perf_tests/main.cpp
- tasks/mpi/durynichev_d_custom_allreduce/src/ops_mpi.cpp
1. **Двоичное дерево для обмена данными**:
- Используется обмен данными по схеме двоичного дерева, что обеспечивает логарифмическое количество шагов – `O(log(size))`.
2. **XOR-операция для определения партнера**:
- На каждом шаге `partner` определяется как `rank ^ step`. Это эффективно для реализации схожей с алгоритмом бинарного дерева для уменьшения данных.
3. **Симметричный обмен**:
- Процессы отправляют и принимают данные с партнером в зависимости от их ранга:
- Если `rank < partner`, сначала отправляют, затем принимают.
- Если `rank > partner`, сначала принимают, затем отправляют.
4. **Реконструкция дерева для распространения результата**:
- После редукции результат передается обратно по дереву для распространения на все процессы:
- **Получение данных от родителя** (`p`).
- …
> Дурыничев Дмитрий. Задача 2. Вариант 7. Передача от всех одному и рассылка (allreduce)

- tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
- tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/include/header.hpp
- tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/perf_tests/main.cpp
- tasks/mpi/kovalev_k_bubble_sort_oddeven_transposition/src/sourse.cpp
- tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/func_tests/main.cpp
- tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/include/header.hpp
- tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/perf_tests/main.cpp
- tasks/seq/kovalev_k_bubble_sort_oddeven_transposition/src/sourse.cpp
Reverts learning-process/ppc-2024-autumn#564
У кого-то упала моя задача 1 ( https://github.com/learning-process/ppc-2024-autumn/pull/129 ), ревертнули задачу 2.
> Revert "Revert "Ковалев Константин. Задача 2. Вариант 25. Сортировка пузырьком (алгоритм чет-нечетной перестановки)""

- scripts/run.sh
https://github.com/learning-process/ppc-2024-autumn/pull/428#discussion_r1868869805
#428, #553
> Handle dots within test lists correctly

- tasks/mpi/rezantseva_a_simple_iteration_method/func_tests/main_rezantseva.cpp
- tasks/mpi/rezantseva_a_simple_iteration_method/include/ops_mpi_rezantseva.hpp
- tasks/mpi/rezantseva_a_simple_iteration_method/perf_tests/main_rezantseva.cpp
- tasks/mpi/rezantseva_a_simple_iteration_method/src/ops_mpi_rezantseva.cpp
- tasks/seq/rezantseva_a_simple_iteration_method/func_tests/main_rezantseva.cpp
- tasks/seq/rezantseva_a_simple_iteration_method/include/ops_seq_rezantseva.hpp
- tasks/seq/rezantseva_a_simple_iteration_method/perf_tests/main_rezantseva.cpp
- tasks/seq/rezantseva_a_simple_iteration_method/src/ops_seq_rezantseva.cpp
Reverts learning-process/ppc-2024-autumn#605
> Revert "Revert "Резанцева Анастасия. Задача 2. Вариант 24. Метод простых итераций.""

- tasks/mpi/voroshilov_v_torus_grid/func_tests/main.cpp
- tasks/mpi/voroshilov_v_torus_grid/include/ops_mpi.hpp
- tasks/mpi/voroshilov_v_torus_grid/perf_tests/main.cpp
- tasks/mpi/voroshilov_v_torus_grid/src/ops_mpi.cpp
Reverts learning-process/ppc-2024-autumn#599
> Revert "Revert "Ворошилов Виталий. Задача 2. Вариант 13. Топология сетей передачи данных "Решётка-тор"""

- tasks/mpi/komshina_d_grid_torus_topology/func_tests/main.cpp
- tasks/mpi/komshina_d_grid_torus_topology/include/ops_mpi.hpp
- tasks/mpi/komshina_d_grid_torus_topology/perf_tests/main.cpp
- tasks/mpi/komshina_d_grid_torus_topology/src/ops_mpi.cpp
Reverts learning-process/ppc-2024-autumn#585
> Revert "Revert "Комшина Дарья. Задача 2. Вариант 13. Топология сети передачи данных решетка-тор.""

- tasks/mpi/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
- tasks/mpi/khovansky_d_ribbon_vertical_scheme/include/ops_mpi.hpp
- tasks/mpi/khovansky_d_ribbon_vertical_scheme/perf_tests/main.cpp
- tasks/mpi/khovansky_d_ribbon_vertical_scheme/src/ops_mpi.cpp
- tasks/seq/khovansky_d_ribbon_vertical_scheme/func_tests/main.cpp
- tasks/seq/khovansky_d_ribbon_vertical_scheme/include/ops_seq.hpp
- tasks/seq/khovansky_d_ribbon_vertical_scheme/perf_tests/main.cpp
- tasks/seq/khovansky_d_ribbon_vertical_scheme/src/ops_seq.cpp
Reverts learning-process/ppc-2024-autumn#578
> Revert "Revert "Хованский Дмитрий. Задача 2. Вариант 16. Ленточная вертикальная схема.""

- tasks/mpi/vershinina_a_image_smoothing/func_tests/main.cpp
- tasks/mpi/vershinina_a_image_smoothing/include/ops_mpi.hpp
- tasks/mpi/vershinina_a_image_smoothing/perf_tests/main.cpp
- tasks/mpi/vershinina_a_image_smoothing/src/ops_mpi.cpp
- tasks/seq/vershinina_a_image_smoothing/func_tests/main.cpp
- tasks/seq/vershinina_a_image_smoothing/include/ops_seq.hpp
- tasks/seq/vershinina_a_image_smoothing/perf_tests/main.cpp
- tasks/seq/vershinina_a_image_smoothing/src/ops_seq.cpp
Reverts learning-process/ppc-2024-autumn#668
> Revert "Revert "Вершинина Александра. Задача 2. Вариант 26. Сглаживание изображения""

- tasks/mpi/petrov_a_ribbon_vertical_scheme/func_tests/main.cpp
- tasks/mpi/petrov_a_ribbon_vertical_scheme/include/ops_mpi.hpp
- tasks/mpi/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
- tasks/mpi/petrov_a_ribbon_vertical_scheme/src/ops_mpi.cpp
- tasks/seq/petrov_a_ribbon_vertical_scheme/func_tests/main.cpp
- tasks/seq/petrov_a_ribbon_vertical_scheme/include/ops_seq.hpp
- tasks/seq/petrov_a_ribbon_vertical_scheme/perf_tests/main.cpp
- tasks/seq/petrov_a_ribbon_vertical_scheme/src/ops_seq.cpp
Вертикальная схема ленты для умножения матрицы на вектор делит матрицу по столбцам (или, точнее, по блокам столбцов) и распределяет части вектора по каждому процессу. Этот подход особенно полезен, когда матрица разреженная или полосатая, что позволяет эффективно распараллеливать.
> Петров Артём Андреевич/Задача2/вариант16/Ленточная вертикальная схема

- tasks/mpi/kharin_m_radix_double_sort/func_tests/main.cpp
- tasks/mpi/kharin_m_radix_double_sort/include/ops_mpi.hpp
- tasks/mpi/kharin_m_radix_double_sort/perf_tests/main.cpp
- tasks/mpi/kharin_m_radix_double_sort/src/ops_mpi.cpp
- tasks/seq/kharin_m_radix_double_sort/func_tests/main.cpp
- tasks/seq/kharin_m_radix_double_sort/include/ops_seq.hpp
- tasks/seq/kharin_m_radix_double_sort/perf_tests/main.cpp
- tasks/seq/kharin_m_radix_double_sort/src/ops_seq.cpp
Поразрядная сортировка чисел с плавающей точкой выполняется последовательно. Программа проходит несколько этапов:
Инициализация и чтение данных: исходный массив чисел загружается из входных данных. Каждое число преобразуется в 64-битное представление для обработки на уровне бит.
Поразрядная сортировка: числа сортируются по 8 битам за одну итерацию (всего 8 итераций для 64-битных чисел). На каждом этапе создается массив подсчета для текущего разряда, который используется для перестановки элементов.
Преобразование результата: после завершения сортировки 64-битные представления обратно преобразуются в числа с плавающей точкой.
Запись результата: отсортированный массив возвращается через выходные данные.
Данная реализация минимизирует использование памяти и оптимизирована для корректной …
> Харин Матвей. Задача 3. Вариант 20. Поразрядная сортировка для вещественных чисел (тип double) с простым слиянием.

- tasks/mpi/sorokin_a_graham_algorithm/func_tests/main.cpp
- tasks/mpi/sorokin_a_graham_algorithm/include/ops_mpi.hpp
- tasks/mpi/sorokin_a_graham_algorithm/perf_tests/main.cpp
- tasks/mpi/sorokin_a_graham_algorithm/src/ops_mpi.cpp
- tasks/seq/sorokin_a_graham_algorithm/func_tests/main.cpp
- tasks/seq/sorokin_a_graham_algorithm/include/ops_seq.hpp
- tasks/seq/sorokin_a_graham_algorithm/perf_tests/main.cpp
- tasks/seq/sorokin_a_graham_algorithm/src/ops_seq.cpp
На вход подаётся одномерный массив, который содержит координаты точек. Используя проход Грэхема (не знаю стоит ли прописывать суть алгоритма, так как он упоминался на лекции и в самом задании есть ссылка на видеоролик) мы получаем точки которые образуют выпуклую оболочку. Таким образом мы получили часть из имеющихся изначально точек, а все остальные находятся внутри фигуры которую можно изобразить из точек которые мы выделили, и они не попадают в ответ. Параллельная реализация заключается в разбиении общего числа точек на части. Так в каждом отдельном процессе получится ответом свой массив, а позже совместим их в нулевом процессе и запустим тот же алгоритм ещё раз, так и получится конечный ответ.
> Сорокин Андрей. Задача 3. Вариант 24. Построение выпуклой оболочки – проход Грэхема

- tasks/mpi/yasakova_t_reduce/func_tests/main.cpp
- tasks/mpi/yasakova_t_reduce/include/ops_mpi.hpp
- tasks/mpi/yasakova_t_reduce/perf_tests/main.cpp
- tasks/mpi/yasakova_t_reduce/src/ops_mpi.cpp
- tasks/mpi/yasakova_t_reduce_custom/func_tests/main.cpp
- tasks/mpi/yasakova_t_reduce_custom/include/ops_mpi.hpp
- tasks/mpi/yasakova_t_reduce_custom/perf_tests/main.cpp
- tasks/mpi/yasakova_t_reduce_custom/src/ops_mpi.cpp
Реализована функция reduce, которая используется для решения задачи нахождения минимального элемента в матрице.
Процесс работы следующий:
1. Корневой процесс разбивает исходную матрицу на равные части.
2. Каждый процесс получает свою часть матрицы и находит минимум в ней, используя функцию CustomReduce.
3. Функция CustomReduce реализована по принципу двоичного дерева. Начиная с листовых процессов (которые обрабатывают отдельные части данных), процессы постепенно объединяются со своими соседями.
4. На каждом шаге два объединяющихся процесса сливают свои промежуточные результаты (найденные минимумы), пока не останется одно итоговое минимальное значение, которое будет у корневого процесса.
Таким образом, распараллеливая обработку матрицы и используя иерархическое объединение промежуточных …
> Ясакова Татьяна. Задача 2. Вариант 6. Передача от всеx одному (reduce)

- tasks/mpi/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
- tasks/mpi/korovin_n_matrix_multiple_cannon/include/ops_mpi.hpp
- tasks/mpi/korovin_n_matrix_multiple_cannon/perf_tests/main.cpp
- tasks/mpi/korovin_n_matrix_multiple_cannon/src/ops_mpi.cpp
- tasks/seq/korovin_n_matrix_multiple_cannon/func_tests/main.cpp
- tasks/seq/korovin_n_matrix_multiple_cannon/include/ops_seq.hpp
- tasks/seq/korovin_n_matrix_multiple_cannon/perf_tests/main.cpp
- tasks/seq/korovin_n_matrix_multiple_cannon/src/ops_seq.cpp
В MPI-версии алгоритма Кэннона основная идея состоит в том, чтобы использовать наименьший квадрат числа процессов. Если общее количество процессов не является квадратом, выбирается `q = floor(sqrt(size))`, и только `q×q` процессов активно участвуют в вычислениях, в то время как остальные остаются неактивными. Такой подход упрощает реализацию алгоритма Кэннона, который наиболее эффективно работает именно на квадратной решётке процессов.
Для упрощения обмена данными между процессами используется декартовая топология MPI. Команды `MPI_Cart_create`, `MPI_Cart_coords` и `MPI_Cart_shift` позволяют просто и наглядно осуществлять циклические сдвиги блоков матриц вдоль строк и столбцов. Хотя декартовая топология особенно актуальна для систем с распределённой памятью и сложной топологией …
> Коровин Никита. Задача 3. Вариант 1. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Кэннона.

- tasks/mpi/zinoviev_a_readers_and_writers/func_tests/main.cpp
- tasks/mpi/zinoviev_a_readers_and_writers/include/ops_mpi.hpp
- tasks/mpi/zinoviev_a_readers_and_writers/perf_tests/main.cpp
- tasks/mpi/zinoviev_a_readers_and_writers/src/ops_mpi.cpp
- tasks/seq/zinoviev_a_readers_and_writers/func_tests/main.cpp
- tasks/seq/zinoviev_a_readers_and_writers/include/ops_seq.hpp
- tasks/seq/zinoviev_a_readers_and_writers/perf_tests/main.cpp
- tasks/seq/zinoviev_a_readers_and_writers/src/ops_seq.cpp
В данной работе представлена реализация классической задачи синхронизации "Читатели-Писатели" в контексте параллельного программирования. Решение предоставлено как в параллельной версии с использованием MPI, так и в последовательной версии. Реализация включает в себя функциональные тесты, тесты производительности, а также необходимые исходные и заголовочные файлы.
Проект содержит два основных класса задач:
**ReadersWritersMPITaskSequential:** Класс, реализующий последовательное выполнение задачи "Читатели-Писатели". Используется для сравнения с параллельным выполнением.
**ReadersWritersMPITaskParallel:** Класс, реализующий параллельное выполнение задачи "Читатели-Писатели" с использованием MPI. Распределяет вычисления на несколько процессов и использует механизмы синхронизации для …
> Зиновьев Александр Задача 2 Вариант 2 Задача «Читатели-Писатели»

- README.md
- tasks/mpi/drozhdinov_d_mult_matrix_fox/func_tests/main.cpp
- tasks/mpi/drozhdinov_d_mult_matrix_fox/include/ops_mpi.hpp
- tasks/mpi/drozhdinov_d_mult_matrix_fox/perf_tests/main.cpp
- tasks/mpi/drozhdinov_d_mult_matrix_fox/src/ops_mpi.cpp
- tasks/seq/drozhdinov_d_mult_matrix_fox/func_tests/main.cpp
- tasks/seq/drozhdinov_d_mult_matrix_fox/include/ops_seq.hpp
- tasks/seq/drozhdinov_d_mult_matrix_fox/perf_tests/main.cpp
- tasks/seq/drozhdinov_d_mult_matrix_fox/src/ops_seq.cpp
**Последовательная задача:** реализовано тривиальное умножение матриц с размером блока 1
**Параллельная задача:** создаётся дополнительный коммуникатор с декартовой топологией, по которому будут взаимодействовать процессы, передавая блоки матриц. Создание решетки производится при помощи функции `MPI_Cart_create`. После создания решетки каждый процесс параллельной программы будет иметь координаты своего положения в решетке; получение этих координат обеспечивается при помощи функции `MPI_Cart_coords`. 
Сам алгоритм Фокса работает следующим образом:
в цикле по размеру сетки:
1)блок A~i~i разделяется по строке i, далее умножается на блоки B~i~j, соответствующие начальному положению. Обновляется C~i~j.
2)блок А~i~i+1 разделяется по строке i, а блоки B~i~j делают циклический сдвиг по столбцу …
> Дрождинов Дмитрий. Задача 3. Вариант 2. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Фокса.

- tasks/mpi/malyshev_a_two_dim_global_optimization_characteristics/func_tests/main.cpp
- tasks/mpi/malyshev_a_two_dim_global_optimization_characteristics/include/ops_mpi.hpp
- tasks/mpi/malyshev_a_two_dim_global_optimization_characteristics/perf_tests/main.cpp
- tasks/mpi/malyshev_a_two_dim_global_optimization_characteristics/src/ops_mpi.cpp
- tasks/seq/malyshev_a_two_dim_global_optimization_characteristics/func_tests/main.cpp
- tasks/seq/malyshev_a_two_dim_global_optimization_characteristics/include/ops_seq.hpp
- tasks/seq/malyshev_a_two_dim_global_optimization_characteristics/perf_tests/main.cpp
- tasks/seq/malyshev_a_two_dim_global_optimization_characteristics/src/ops_seq.cpp
Последовательный алгоритм глобальной оптимизации представляет собой комплексный подход к поиску глобального минимума функции с ограничениями. Рассмотрим каждый этап подробно:
1. Начальный поиск на сетке (Grid Search)
- Область поиска разбивается равномерной сеткой на подобласти
- Размер сетки определяется константой `grid_initial_size`
- В каждой точке сетки запускается локальный поиск
- Сохраняется лучшая найденная точка как потенциальный глобальный минимум
2. Локальный поиск (Local Search)
- Использует метод градиентного спуска с адаптивным шагом
- Градиент вычисляется численно через центральные конечные разности
- На каждой итерации:
- Вычисляется направление спуска
- Проверяются ограничения области и дополнительные условия
- Адаптивно подбирается размер шага
- При отсутствии улучшения …
> Малышев Антон. Задача 3. Вариант 13. Многошаговая схема решения двумерных задач глобальной оптимизации.  Распараллеливание по характеристикам.

- tasks/mpi/ermilova_d_min_element_matrix/func_tests/main.cpp
- tasks/mpi/ermilova_d_min_element_matrix/include/ops_mpi.hpp
- tasks/mpi/ermilova_d_min_element_matrix/perf_tests/main.cpp
- tasks/mpi/ermilova_d_min_element_matrix/src/ops_mpi.cpp
- tasks/seq/ermilova_d_min_element_matrix/func_tests/main.cpp
- tasks/seq/ermilova_d_min_element_matrix/include/ops_seq.hpp
- tasks/seq/ermilova_d_min_element_matrix/perf_tests/main.cpp
- tasks/seq/ermilova_d_min_element_matrix/src/ops_seq.cpp
Работу ревертнули из-за бага с gcc:
> REVERT Ермилова Дарья. Задача 1. Вариант 14. Минимальное значение матрицы.

- tasks/mpi/zinoviev_a_sum_cols_matrix/func_tests/main.cpp
- tasks/mpi/zinoviev_a_sum_cols_matrix/include/ops_mpi.hpp
- tasks/mpi/zinoviev_a_sum_cols_matrix/perf_tests/main.cpp
- tasks/mpi/zinoviev_a_sum_cols_matrix/src/ops_mpi.cpp
- tasks/seq/zinoviev_a_sum_cols_matrix/func_tests/main.cpp
- tasks/seq/zinoviev_a_sum_cols_matrix/include/ops_seq.hpp
- tasks/seq/zinoviev_a_sum_cols_matrix/perf_tests/main.cpp
- tasks/seq/zinoviev_a_sum_cols_matrix/src/ops_seq.cpp
Здесь представлены последовательная и параллельная реализации суммы значений по столбцам матрицы. **В последовательной** реализуем вложенный цикл, проходя по каждому столбцу матрицы, суммируя значения её элементов. Итоговые суммы помещаются в отдельный вектор. **В параллельной** распределяем столбцы матрицы в зависимости от числа доступных процессов. Определяем величину, которая обозначает количество столбцов, отведенных каждому процессу, а также индекс последнего обрабатываемого столбца для каждого процесса. Каждая группа столбцов суммируется с использованием функции, аналогичной той, что применяется в последовательной версии. Полученные результаты затем консолидируются в общий вектор.
> Зиновьев Александр Задача 1 Вариант 12 Сумма значений по столбцам матрицы

- tasks/mpi/shvedova_v_mult_int_simpson/func_tests/main.cpp
- tasks/mpi/shvedova_v_mult_int_simpson/include/ops_mpi.hpp
- tasks/mpi/shvedova_v_mult_int_simpson/perf_tests/main.cpp
- tasks/mpi/shvedova_v_mult_int_simpson/src/ops_mpi.cpp
- tasks/seq/shvedova_v_multi_integral_simpson/func_tests/main.cpp
- tasks/seq/shvedova_v_multi_integral_simpson/include/ops_seq.hpp
- tasks/seq/shvedova_v_multi_integral_simpson/perf_tests/main.cpp
- tasks/seq/shvedova_v_multi_integral_simpson/src/ops_seq.cpp
1. **Инициализация**  
- Устанавливается начальное число подынтервалов (`subintervalCount = 2`).
- Определяются пределы интегрирования.
2. **Рекурсия**  
- Обрабатывается одна переменная, текущая точка добавляется в массив `currentArgs`.
- Если переменных больше одной, вызывается рекурсивная функция для следующей переменной.
- Если пределы закончились, вычисляется значение целевой функции.
3. **Метод Симпсона**  
- Делится интервал на подынтервалы (`stepSize`).
- Вычисляются значения функции с учетом весов:
- Крайние точки: вес = 1.
- Промежуточные точки: вес = 4 (нечетные индексы) или 2 (четные индексы).
- Интегральная сумма масштабируется и проверяется на сходимость (точность).
4. **Возврат результатов**  
- Результаты собираются с каждого уровня рекурсии.
- Итерации повторяются до …
> Шведова Виталина. Задача 3. Вариант 9. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона)

- tasks/mpi/anikin_m_contrastscale/func_tests/main.cpp
- tasks/mpi/anikin_m_contrastscale/include/ops_mpi.hpp
- tasks/mpi/anikin_m_contrastscale/perf_tests/main.cpp
- tasks/mpi/anikin_m_contrastscale/src/ops_mpi.cpp
- tasks/seq/anikin_m_contrastscale/func_tests/main.cpp
- tasks/seq/anikin_m_contrastscale/include/ops_seq.hpp
- tasks/seq/anikin_m_contrastscale/perf_tests/main.cpp
- tasks/seq/anikin_m_contrastscale/src/ops_seq.cpp
В результате тестирования ошибка возникала раз в 10000 раз, связана с тем что функция, возвращающая контраст изображения, учитывала только один канал R, ошибка поправлена, функция учитывает все каналы.
> Fix Revert Аникин Максим. Задача 2. Вариант 27. Повышение контраста изображения

- tasks/mpi/ermilova_d_Shell_sort_simple_merge/func_tests/main.cpp
- tasks/mpi/ermilova_d_Shell_sort_simple_merge/include/ops_mpi.hpp
- tasks/mpi/ermilova_d_Shell_sort_simple_merge/perf_tests/main.cpp
- tasks/mpi/ermilova_d_Shell_sort_simple_merge/src/ops_mpi.cpp
- tasks/seq/ermilova_d_Shell_sort_simple_merge/func_tests/main.cpp
- tasks/seq/ermilova_d_Shell_sort_simple_merge/include/ops_seq.hpp
- tasks/seq/ermilova_d_Shell_sort_simple_merge/perf_tests/main.cpp
- tasks/seq/ermilova_d_Shell_sort_simple_merge/src/ops_seq.cpp
Сортировка Шелла.
Внешний цикл for (size_t gap = n / 2; gap > 0; gap /= 2):
Внешний цикл управляет значением интервала. Он начинается с половины длины массива и уменьшается в два раза на каждом шаге, пока не достигнет 1. Для каждого интервала, элементы массива, расположенные через этот интервал, будут сравниваться и переставляться.
Внутренний цикл for (size_t i = gap; i < n; i++):
Внутренний цикл выполняет сортировку вставками для элементов, расположенных через интервал. То есть, для каждого элемента с индексом i, начиная с позиции gap, выполняется сортировка с соседними элементами, находящимися на расстоянии gap друг от друга.
Когда интервал достигает 1, выполняется обычная сортировка вставками для всех элементов.
Последовательная версия:
Выполняется сортировка Шелла на массиве данных. …
> Ермилова Дарья. Задача 3. Вариант 16. Сортировка Шелла с простым слиянием

- tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
- tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/include/ops_mpi.hpp
- tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/perf_tests/main.cpp
- tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
- tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
- tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/include/ops_seq.hpp
- tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/perf_tests/main.cpp
- tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/src/ops_seq.cpp
https://github.com/learning-process/ppc-2024-autumn/pull/513 Добавил рандомные тесты
> Fix revert Fix revert Одинцов Михаил. Задача 1.Вариант 27 Подсчет числа несовпадающих символов двух строк

- tasks/mpi/kudryashova_i_graham's_scan/func_tests/Graham'sScanMPIFuncTests.cpp
- tasks/mpi/kudryashova_i_graham's_scan/include/Graham'sScanMPI.hpp
- tasks/mpi/kudryashova_i_graham's_scan/perf_tests/Graham'sScanMPIPerfTests.cpp
- tasks/mpi/kudryashova_i_graham's_scan/src/Graham'sScanMPI.cpp
- tasks/seq/kudryashova_i_graham's_scan/func_tests/Graham'sScanSeqFuncTests.cpp
- tasks/seq/kudryashova_i_graham's_scan/include/Graham'sScanSeq.hpp
- tasks/seq/kudryashova_i_graham's_scan/perf_tests/Graham'sScanSeqPerfTests.cpp
- tasks/seq/kudryashova_i_graham's_scan/src/Graham'sScanSeq.cpp
Последовательная реализация
На вход подаём массив точек, в котором сначала идут координаты по x, а потом по y. Среди всех точек выбирается та, у которой координата y меньше остальных. Перемещаем эту точку в самое начало массива. Она будет опорной. Сортируем оставшиеся точки по углу образованному с начальной точкой и осью x. Если две точки имеют одинаковый угол, оставим ту, которая ближе к начальной точке. Создайте пустой вектор hull для хранения точек выпуклой оболочки. Добавляем туда начальную точку и первые две отсортированные точки. Проверим, образуют ли последние две точки в стеке и текущая точка левый поворот. Если происходит правый поворот, удаляем верхнюю точку, так как она не будет частью выпуклой оболочки. Добавляем текущую точку. Будем повторять этот процесс, пока не обработаем …
> Кудряшова Ирина. Задача 3. Вариант 24. Построение выпуклой оболочки – проход Грэхема

- tasks/mpi/rezantseva_a_simple_iteration_method/func_tests/main_rezantseva.cpp
- tasks/mpi/rezantseva_a_simple_iteration_method/include/ops_mpi_rezantseva.hpp
- tasks/mpi/rezantseva_a_simple_iteration_method/perf_tests/main_rezantseva.cpp
- tasks/mpi/rezantseva_a_simple_iteration_method/src/ops_mpi_rezantseva.cpp
- tasks/seq/rezantseva_a_simple_iteration_method/func_tests/main_rezantseva.cpp
- tasks/seq/rezantseva_a_simple_iteration_method/include/ops_seq_rezantseva.hpp
- tasks/seq/rezantseva_a_simple_iteration_method/perf_tests/main_rezantseva.cpp
- tasks/seq/rezantseva_a_simple_iteration_method/src/ops_seq_rezantseva.cpp
Revert: исправила perf тесты, изменив размер матриц
> Fix revert "Резанцева Анастасия. Задача 2. Вариант 24. Метод простых итераций."

- tasks/mpi/veliev_e_sobel_operator/func_tests/main.cpp
- tasks/mpi/veliev_e_sobel_operator/include/ops_mpi.hpp
- tasks/mpi/veliev_e_sobel_operator/perf_tests/main.cpp
- tasks/mpi/veliev_e_sobel_operator/src/ops_mpi.cpp
- tasks/seq/veliev_e_sobel_operator/func_tests/main.cpp
- tasks/seq/veliev_e_sobel_operator/include/ops_seq.hpp
- tasks/seq/veliev_e_sobel_operator/perf_tests/main.cpp
- tasks/seq/veliev_e_sobel_operator/src/ops_seq.cpp
> Велиев Эльвин Задача 3 Вариант 29. Выделение ребер на изображении с использованием оператора Собеля

- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_mpi.hpp
- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
- tasks/mpi/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_mpi.cpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/func_tests/main.cpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/include/ops_seq.hpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/perf_tests/main.cpp
- tasks/seq/sozonov_i_gaussian_method_horizontal_strip_scheme/src/ops_seq.cpp
Алгоритм состоит из двух этапов: прямой ход и обратный ход.
**Этап 1: Прямой ход**
Для всех строк от i=0 до n-1 (перебираем ведущие строки):
Для всех строк от i=k+1 до n:
Вычисляем множитель: m_ik=A[k,i]/(A[i,i]) ;
Обновляем элементы строки i от j=i до n+1: A[k,j]=A[k,j]− A[i,j]⋅m_ik
После выполнения прямого хода матрица становится верхнетреугольной.
**Этап 2: Обратный ход**
Для всех строк от i=n−1 до 0 (в обратном порядке):
Находим свободный член b= A[i,n];
Находим значение очередной неизвестной, используя предыдущие:
Вычитаем из свободного члена сумму: ∑_(j=i+1)^n▒〖A[i,j]∙x[j]〗 ;
Получившееся выражение делим на диагональный элемент: x[i]=b/(A[i,i]);
После выполнения обратного хода получаем значения всех неизвестных.
**Описание MPI задачи**
Циклически …
> Fix Revert. Созонов Илья. Задача 2. Вариант 19. Метод Гаусса – ленточная горизонтальная схема. 

- tasks/mpi/kalyakina_a_trapezoidal_integration_mpi/func_tests/main.cpp
- tasks/mpi/kalyakina_a_trapezoidal_integration_mpi/include/ops_mpi.hpp
- tasks/mpi/kalyakina_a_trapezoidal_integration_mpi/perf_tests/main.cpp
- tasks/mpi/kalyakina_a_trapezoidal_integration_mpi/src/ops_mpi.cpp
- tasks/seq/kalyakina_a_trapezoidal_integration_seq/func_tests/main.cpp
- tasks/seq/kalyakina_a_trapezoidal_integration_seq/include/ops_seq.hpp
- tasks/seq/kalyakina_a_trapezoidal_integration_seq/perf_tests/main.cpp
- tasks/seq/kalyakina_a_trapezoidal_integration_seq/src/ops_seq.cpp
**Входные параметры:** 
- указатель на интегрируемую функцию,
- количество переменных функции,
- пределы интегрирования по каждой переменной,
- количество интервалов (шагов) по каждой переменной.
Интегрирование происходит по всем переменным функции.
**Алгоритм параллельного решения:**
- подсчет количества точек, в которых надо вычислить значение функции,
- распределение точек, по возможности равномерное, среди всех процессов (вычисление количества точек для каждого процесса и номера первой точки),
- определение координат точек по их номерам каждым процессом, вычисление значений функции в этой точке и умножение их на некоторый коэффициент, определяемый по методу трапеций,
- суммирование всех значений функций в нулевом процессе,
- обработка суммы: умножение на шаг по каждой переменной и на …
> Калякина Анастасия. Задача 3. Вариант 8. Вычисление многомерных интегралов с использованием многошаговой схемы (метод трапеций).

- tasks/mpi/matyunina_a_batcher_qsort/func_tests/main.cpp
- tasks/mpi/matyunina_a_batcher_qsort/include/ops_mpi.hpp
- tasks/mpi/matyunina_a_batcher_qsort/perf_tests/main.cpp
- tasks/mpi/matyunina_a_batcher_qsort/src/ops_mpi.cpp
- tasks/seq/matyunina_a_batcher_qsort/func_tests/main.cpp
- tasks/seq/matyunina_a_batcher_qsort/include/ops_seq.hpp
- tasks/seq/matyunina_a_batcher_qsort/perf_tests/main.cpp
- tasks/seq/matyunina_a_batcher_qsort/src/ops_seq.cpp
- Использует классическую быструю сортировку (QuickSort) с нерекурсивной реализацией через стек
- Работает с векторами элементов произвольного типа (шаблонная реализация)
1. Разделение исходного массива между процессами
2. Локальная сортировка на каждом процессе
3. Параллельное слияние отсортированных частей
1. Функциональные тесты:
- Случайный вектор
- Пустой вектор
- Вектор с одним элементом
- Вектор с повторяющимися элементами
- Тестовый пример из видео
> Матюнина Александра. Задача 3. Вариант 15. Задача: Быстрая сортировка с четно-нечетным слиянием Бэтчера.

- tasks/mpi/kapustin_i_bubble/func_tests/main.cpp
- tasks/mpi/kapustin_i_bubble/include/avg_mpi.hpp
- tasks/mpi/kapustin_i_bubble/perf_tests/main.cpp
- tasks/mpi/kapustin_i_bubble/src/avg_mpi.cpp
- tasks/seq/kapustin_i_bubble/func_tests/main.cpp
- tasks/seq/kapustin_i_bubble/include/avg_seq.hpp
- tasks/seq/kapustin_i_bubble/perf_tests/main.cpp
- tasks/seq/kapustin_i_bubble/src/avg_seq.cpp
#671 Исправлены данные в perf_tests.
> [FIX REVERT] Капустин Иван. Вариант 16. Сортировка "Пузырьком"

- tasks/mpi/korablev_v_quick_sort_simple_merge/perf_tests/main.cpp
- tasks/seq/korablev_v_quick_sort_simple_merge/perf_tests/main.cpp
Увеличил размер сортируемого вектора для увеличения времени прохождения perf тестов.
> [FIX PERF TESTS] Кораблев Владлен. Задача 3. Вариант 14. Быстрая сортировка с простым слиянием

- tasks/mpi/muradov_m_matrix_multiply_ccs/func_tests/main.cpp
- tasks/mpi/muradov_m_matrix_multiply_ccs/include/ops_mpi.hpp
- tasks/mpi/muradov_m_matrix_multiply_ccs/perf_tests/main.cpp
- tasks/mpi/muradov_m_matrix_multiply_ccs/src/ops_mpi.cpp
- tasks/seq/muradov_m_matrix_multiply_ccs/func_tests/main.cpp
- tasks/seq/muradov_m_matrix_multiply_ccs/include/ops_seq.hpp
- tasks/seq/muradov_m_matrix_multiply_ccs/perf_tests/main.cpp
- tasks/seq/muradov_m_matrix_multiply_ccs/src/ops_seq.cpp
В тесте создаются две матрицы `A_` и `B_`, которые синхронизируются на нулевом воркере для обеспечения согласованности данных. Обе матрицы конвертируются в формат CCS (Compressed Column Storage) для последующей обработки. Алгоритм выполняет транспонирование матрицы `A` в формате CCS, после чего производит оптимизированное умножение с матрицей `B`, постепенно заполняя результирующие массивы `res`. Эти массивы возвращаются в тестовую функцию, где результат умножения в формате CCS сверяется с эталонным значением, полученным через умножение исходных плотных матриц, также переведенных в формат CCS.
> Мурадов Майк. Задача 3. Вариант 5. Умножение разреженных матриц. Элементы типа double.  Формат хранения матрицы – столбцовый (CCS).

- tasks/mpi/gusev_n_hypercube_topology/func_tests/main.cpp
- tasks/mpi/gusev_n_hypercube_topology/include/ops_mpi.hpp
- tasks/mpi/gusev_n_hypercube_topology/perf_tests/main.cpp
- tasks/mpi/gusev_n_hypercube_topology/src/ops_mpi.cpp
Фикс реверта. Была проблема с perf тестами, которые возвращали нулевое время
Прошлый pr: https://github.com/learning-process/ppc-2024-autumn/pull/336
> [FIX REVERT] Гусев Никита. Задача 2. Вариант 14. Топология сети передачи данных - гиперкуб

- tasks/mpi/kurakin_m_graham_scan/perf_tests/kurakin_graham_scan.cpp
- tasks/seq/kurakin_m_graham_scan/perf_tests/kurakin_graham_scan.cpp
Увеличил число точек, чтобы время выполнения было больше 1 секунды
> Исправлены Perf tests. Куракин Матвей. Задача 3. Вариант 24. Построение выпуклой оболочки – проход Грэхема

- tasks/mpi/sorochkin_d_radix_sort_batcher_merge_double/func_tests/main.cpp
- tasks/mpi/sorochkin_d_radix_sort_batcher_merge_double/include/ops_mpi.hpp
- tasks/mpi/sorochkin_d_radix_sort_batcher_merge_double/perf_tests/main.cpp
- tasks/mpi/sorochkin_d_radix_sort_batcher_merge_double/src/ops_mpi.cpp
- tasks/seq/sorochkin_d_radix_sort_batcher_merge_double/func_tests/main.cpp
- tasks/seq/sorochkin_d_radix_sort_batcher_merge_double/include/ops_seq.hpp
- tasks/seq/sorochkin_d_radix_sort_batcher_merge_double/perf_tests/main.cpp
- tasks/seq/sorochkin_d_radix_sort_batcher_merge_double/src/ops_seq.cpp
**Последовательная версия**
В последовательной версии используется алгоритм поразрядной сортировки, который обрабатывает массив чисел с плавающей точкой. На каждом этапе сортировки числа преобразуются в битовый формат, чтобы обеспечить корректное сравнение их разрядов. Сначала массив сортируется по младшему байту, затем по следующему, и так далее до старшего байта. После каждой итерации производится пересортировка, чтобы сохранить порядок. Для упрощения выполнения и интеграции результат копируется в выходной массив.
**Параллельная версия**
Параллельная версия основывается на использовании библиотеки Boost.MPI для распределения работы между несколькими процессами. Исходный массив разделяется на части, которые передаются разным процессам для локальной поразрядной сортировки. После этого …
> Сорочкин Данила. Задача 3. Вариант 21. Поразрядная сортировка для вещественных чисел с четно-нечетным слиянием Бэтчера.

- tasks/mpi/polikanov_v_gradient_method/func_tests/main.cpp
- tasks/mpi/polikanov_v_gradient_method/include/ops_mpi.hpp
- tasks/mpi/polikanov_v_gradient_method/perf_tests/main.cpp
- tasks/mpi/polikanov_v_gradient_method/src/ops_mpi.cpp
- tasks/seq/polikanov_v_gradient_method/func_tests/main.cpp
- tasks/seq/polikanov_v_gradient_method/include/ops_seq.hpp
- tasks/seq/polikanov_v_gradient_method/perf_tests/main.cpp
- tasks/seq/polikanov_v_gradient_method/src/ops_seq.cpp
Этот код реализует метод сопряженных градиентов для решения систем линейных уравнений с использованием плоского представления матрицы. Основная функция, `ConjugateGradientMethod`, итеративно уточняет решение, вычисляя невязку и корректируя направление поиска с учетом коэффициентов α и β, полученных через скалярные произведения.
**О функциях:**
`MultiplyMatrixByVector`: умножает матрицу на вектор, используя индексацию в плоском массиве
`DotProduct`: вычисляет скалярное произведение
`VectorNorm`: находит норму вектора
> Поликанов Виталий. Задача 3. Вариант 6. Решение систем линейных уравнений методом сопряженных градиентов.

- tasks/mpi/milovankin_m_component_labeling/func_tests/main.cpp
- tasks/mpi/milovankin_m_component_labeling/include/component_labeling.hpp
- tasks/mpi/milovankin_m_component_labeling/perf_tests/main.cpp
- tasks/mpi/milovankin_m_component_labeling/src/component_labeling.cpp
- tasks/seq/milovankin_m_component_labeling/func_tests/main.cpp
- tasks/seq/milovankin_m_component_labeling/include/component_labeling_seq.hpp
- tasks/seq/milovankin_m_component_labeling/perf_tests/main.cpp
- tasks/seq/milovankin_m_component_labeling/src/component_labeling_seq.cpp
_**Последовательная задача**_
Проход по массиву с бинарным изображением. Для каждого элемента не равного 0 проверяются значения `labels` (ID компонентов) в 3 соседях - слева, сверху и слева-сверху.
- Если каждое из них равно 0 или сосед не существует, компонент обозначается новым ID в векторе `labels`.
- Если не все значения равны 0 и ненулевые равны между собой, этот элемент входит в соответствующий компонент и обозначается тем же значением в `labels`.
- Когда более одного значения не равны 0, и при этом не равны между собой, текущий элемент связывает части одного компонента, обозначенные разными ID. Элементу присваивается значение одной из частей. ID этой части выбирается как ID компонента и в таблицу (_unordered hash map_) для каждого из остальных ID записывается значение этого …
> Милованкин Максим. Задача 3. Вариант 31. Маркировка компонент на бинарном изображении.

- tasks/mpi/pikarychev_i_monte_carlo/func_tests/main.cpp
- tasks/mpi/pikarychev_i_monte_carlo/include/ops_mpi.hpp
- tasks/mpi/pikarychev_i_monte_carlo/perf_tests/main.cpp
- tasks/mpi/pikarychev_i_monte_carlo/src/ops_mpi.cpp
- tasks/seq/pikarychev_i_monte_carlo/func_tests/main.cpp
- tasks/seq/pikarychev_i_monte_carlo/include/ops_seq.hpp
- tasks/seq/pikarychev_i_monte_carlo/perf_tests/main.cpp
- tasks/seq/pikarychev_i_monte_carlo/src/ops_seq.cpp
Метод pre_processing() определяет границы интегрирования a и b, а также количество случайных точек num_points на основе входных данных.
Интегрирование:
Метод run() выполняет следующие шаги:
1. Инициализирует генератор случайных чисел.
2. Генерирует num_points случайных значений x в диапазоне [a, b].
3. Для каждого x вычисляет значение функции и суммирует результаты.
4. Вычисляет итоговый результат интегрирования как произведение диапазона интегрирования (b — a) на среднее значение вычисленных функций.
MPI
Метод run() выполняет следующие шаги на каждом процессе:
1. Определяет количество точек num_points_for_process, которое необходимо обработать текущему процессу, учитывая общее количество процессов и возможный остаток.
2. Генерирует num_points_for_process случайных значений x в диапазоне …
> Пикарычев Илья. Задача 1. Вариант 21. Интегрирование - метод Монте-Карло

- tasks/mpi/koshkin_m_dining_philosophers/func_tests/main.cpp
- tasks/mpi/koshkin_m_dining_philosophers/include/ops_mpi.hpp
- tasks/mpi/koshkin_m_dining_philosophers/perf_tests/main.cpp
- tasks/mpi/koshkin_m_dining_philosophers/src/ops_mpi.cpp
В данной реализации рассматривается классическая задача синхронизации в параллельных вычислениях — "Проблема обедающих философов". Она описывает ситуацию, в которой несколько философов (задач) сидят за круглым столом, чередуя размышления и прием пищи. Каждый философ может приступить к еде только после того, как завладеет двумя "вилками" (ресурсами), лежащими слева и справа от него. Проблема заключается в предотвращении взаимоблокировок (deadlocks), голодания задач (starvation) и обеспечении корректного взаимодействия при совместном использовании ресурсов.
Что исправлено: решена проблема perf тестов
> [FIX PERF TEST] Кошкин Матвей. Задача 2. Вариант 3. «Обедающие философы»

- tasks/mpi/korablev_v_jacobi_method/perf_tests/main.cpp
- tasks/seq/korablev_v_jacobi_method/perf_tests/main.cpp
Reverts learning-process/ppc-2024-autumn#684
> Revert "[FIX PERF TESTS] Кораблев Владлен. Задача 2. Вариант 22. Итеративные методы (Якоби)"

- tasks/mpi/durynichev_d_most_different_neighbor_elements/func_tests/main.cpp
- tasks/mpi/durynichev_d_most_different_neighbor_elements/include/ops_mpi.hpp
- tasks/mpi/durynichev_d_most_different_neighbor_elements/perf_tests/main.cpp
- tasks/mpi/durynichev_d_most_different_neighbor_elements/src/ops_mpi.cpp
- tasks/seq/durynichev_d_most_different_neighbor_elements/func_tests/main.cpp
- tasks/seq/durynichev_d_most_different_neighbor_elements/include/ops_seq.hpp
- tasks/seq/durynichev_d_most_different_neighbor_elements/perf_tests/main.cpp
- tasks/seq/durynichev_d_most_different_neighbor_elements/src/ops_seq.cpp
Исправил распределение данных между процессами, теперь они отправляются с перехлестом, так же исправил рассчет индексов в начальном значении ответа и чтение освобождённой памяти в post_processing
> FIX Revert "Дурыничев Дмитрий. Задача 1. Вариант 8. Нахождение наиболее отличающихся по значению соседних элементов вектора."

- tasks/mpi/savchenko_m_matrix_mult_strassen/func_tests/main_savchenko_L3.cpp
- tasks/mpi/savchenko_m_matrix_mult_strassen/include/ops_mpi_savchenko_L3.hpp
- tasks/mpi/savchenko_m_matrix_mult_strassen/perf_tests/main_savchenko_L3.cpp
- tasks/mpi/savchenko_m_matrix_mult_strassen/src/ops_mpi_savchenko_L3.cpp
- tasks/seq/savchenko_m_matrix_mult_strassen/func_tests/main_savchenko_L3.cpp
- tasks/seq/savchenko_m_matrix_mult_strassen/include/ops_seq_savchenko_L3.hpp
- tasks/seq/savchenko_m_matrix_mult_strassen/perf_tests/main_savchenko_L3.cpp
- tasks/seq/savchenko_m_matrix_mult_strassen/src/ops_seq_savchenko_L3.cpp
Алгоритм Штрассена — это метод умножения матриц, который уменьшает количество необходимых умножений по сравнению с классическим методом. 
- **Базовый случай:** Если размер матрицы меньше или равен 4, используется стандартное умножение матриц.
- **Преобразование матриц:** Если размер матрицы не является степенью двойки, матрицы дополняются нулями до ближайшей степени двойки.
- **Разделение матриц:** Исходные матрицы A и B разбиваются на четыре подматрицы (A11, A12, A21, A22 и B11, B12, B21, B22).
- **Рекурсивные вызовы:** Вычисляются семь произведений (M[0] до M[6]) с использованием рекурсивных вызовов функции `strassen`, которые комбинируют подматрицы.
- **Сбор результата:** Результаты M[0] до M[6] комбинируются для получения итоговой матрицы C.
- Инициализация MPI: Определяется ранг и …
> Савченко Максим. Задача 3. Вариант 3. Умножение плотных матриц. Элементы типа double. Алгоритм Штрассена.

- tasks/mpi/savchenko_m_ribbon_mult_split_a/func_tests/main_savchenko.cpp
- tasks/mpi/savchenko_m_ribbon_mult_split_a/include/ops_mpi_savchenko.hpp
- tasks/mpi/savchenko_m_ribbon_mult_split_a/perf_tests/main_savchenko.cpp
- tasks/mpi/savchenko_m_ribbon_mult_split_a/src/ops_mpi_savchenko.cpp
- tasks/seq/savchenko_m_ribbon_mult_split_a/func_tests/main_savchenko.cpp
- tasks/seq/savchenko_m_ribbon_mult_split_a/include/ops_seq_savchenko.hpp
- tasks/seq/savchenko_m_ribbon_mult_split_a/perf_tests/main_savchenko.cpp
- tasks/seq/savchenko_m_ribbon_mult_split_a/src/ops_seq_savchenko.cpp
Ленточная горизонтальная схема умножения матриц — это параллельный алгоритм, при котором исходные матрицы разбиваются на горизонтальные (для матрицы A) и вертикальные (для матрицы B) полосы. В данной реализации разбиение происходит только матрицы A.
Классическое умножение матриц основано на тройном цикле, который проходит по всем элементам матриц. Для двух матриц A (размером `m * n`) и B (размером `n * p`), результатом будет матрица C (размером `m * p`). 
Параллельная реализация использует библиотеку MPI для распределения вычислений между несколькими процессами. Основные шаги алгоритма:
1. **Инициализация MPI:** Получение ранга и размера коммуникатора.
2. **Рассылка размеров матриц:** Процесс 0 рассылает размер матриц всем процессам.
3. **Распределение матриц:** Матрица A разбивается на …
> Савченко Максим. Задача 2. Вариант 17. Ленточная горизонтальная схема - разбиение только матрицы А.

- tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
- tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/include/ops_mpi.hpp
- tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/perf_tests/main.cpp
- tasks/mpi/Odintsov_M_CountingMismatchedCharactersStr/src/ops_mpi.cpp
- tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/func_tests/main.cpp
- tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/include/ops_seq.hpp
- tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/perf_tests/main.cpp
- tasks/seq/Odintsov_M_CountingMismatchedCharactersStr/src/ops_seq.cpp
Как и просили присылаю скрины перезапущенных CL в локальном репозитории 
https://github.com/learning-process/ppc-2024-autumn/pull/636
P.S После дополнительного анализа, все таки была замечено утечка данных. ( не там скобочку поставил) 
P.S.S Пофиксил.
> Revert revert revert Одинцов Михаил Задача 1. Вариант 27. Подсчет числа несовпадающих символов 2 строк

- tasks/mpi/ivanov_m_optimization_by_characteristics/func_tests/main.cpp
- tasks/mpi/ivanov_m_optimization_by_characteristics/include/ops_mpi.hpp
- tasks/mpi/ivanov_m_optimization_by_characteristics/perf_tests/main.cpp
- tasks/mpi/ivanov_m_optimization_by_characteristics/src/ops_mpi.cpp
- tasks/seq/ivanov_m_optimization_by_characteristics/func_tests/main.cpp
- tasks/seq/ivanov_m_optimization_by_characteristics/include/ops_seq.hpp
- tasks/seq/ivanov_m_optimization_by_characteristics/perf_tests/main.cpp
- tasks/seq/ivanov_m_optimization_by_characteristics/src/ops_seq.cpp
**Входные параметры:**
- целевая функция (`f`)
- набор функция-ограничений (характеристик) (`restriction`)
- координаты центра области поиска (`centerX`, `centerY`)
- характеристика длины стороны области поиска, выраженная в количестве точек (`size`) (общее число точек в области для поиска оптимального решения `size `* `size`; область поиска - квадрат)
- длина шага (`step`)
- приближение, до которого нужно искать ответ (`approximation`)
**Последовательная версия:**
Пока не достигнута необходимая величина приближения:
- проходим по каждой точке области
- - оцениваем, удовлетворяет ли точка всем ограничениям
- - если удовлетворяет, находим значение функции в этой точке
- - если значение меньше предыдущего результата, то перезаписываем результат
- уменьшаем область в 5 раз
**Параллельная …
> Иванов Михаил. Задача 3. Вариант 13. Многошаговая схема решения двумерных задач глобальной оптимизации.  Распараллеливание по характеристикам.

- tasks/mpi/vershinina_a_cannons_algorithm/func_tests/main.cpp
- tasks/mpi/vershinina_a_cannons_algorithm/include/ops_mpi.hpp
- tasks/mpi/vershinina_a_cannons_algorithm/perf_tests/main.cpp
- tasks/mpi/vershinina_a_cannons_algorithm/src/ops_mpi.cpp
- tasks/seq/vershinina_a_cannons_algorithm/func_tests/main.cpp
- tasks/seq/vershinina_a_cannons_algorithm/include/ops_seq.hpp
- tasks/seq/vershinina_a_cannons_algorithm/perf_tests/main.cpp
- tasks/seq/vershinina_a_cannons_algorithm/src/ops_seq.cpp
**seq**: реализован класс TMatrix, с помощью которого строки или столбцы матриц виртуально сдвигаются в соответствии с алгоритмом, ответ записывается в результирующую матрицу.
**mpi**: из активных процессов формируется декартова топология, корневой процесс рассылает блоки данных каждому процессу и происходит умножение локальных блоков, затем производится циклический сдвиг строк или столбцов матриц, ответ собирается корневым процессом и записывается в результирующую матрицу.
> Вершинина Александра. Задача 3. Вариант 1. Умножение плотных матриц. Элементы типа double. Блочная схема, алгоритм Кэннона

- tasks/mpi/tyurin_m_shell_sort_batcher_merge/func_tests/main.cpp
- tasks/mpi/tyurin_m_shell_sort_batcher_merge/include/ops_mpi.hpp
- tasks/mpi/tyurin_m_shell_sort_batcher_merge/perf_tests/main.cpp
- tasks/mpi/tyurin_m_shell_sort_batcher_merge/src/ops_mpi.cpp
- tasks/seq/tyurin_m_shell_sort_batcher_merge/func_tests/main.cpp
- tasks/seq/tyurin_m_shell_sort_batcher_merge/include/ops_seq.hpp
- tasks/seq/tyurin_m_shell_sort_batcher_merge/perf_tests/main.cpp
- tasks/seq/tyurin_m_shell_sort_batcher_merge/src/ops_seq.cpp
Данная реализация объединяет алгоритм сортировки Шелла с оптимизированной последовательностью шагов, параллельный обмен данными с использованием MPI и эффективные стратегии слияния для сортировки распределённых данных. Последовательность шагов в сортировке Шелла рассчитана с использованием математической формулы для повышения производительности. Функции swapSortedArrays и алгоритмы слияния обеспечивают эффективное объединение данных между процессами MPI. Такой подход оптимизирует локальные вычисления с помощью сортировки Шелла и синхронизацию между процессами через слияние по схеме Батчера, обеспечивая высокую масштабируемость и эффективность для работы с большими наборами данных.
> Тюрин Михаил. Задача 3. Вариант 17. Сортировка Шелла с четно-нечетным слиянием Бэтчера.

- tasks/mpi/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
- tasks/mpi/yasakova_t_quick_sort_with_simple_merge/include/ops_mpi.hpp
- tasks/mpi/yasakova_t_quick_sort_with_simple_merge/perf_tests/main.cpp
- tasks/mpi/yasakova_t_quick_sort_with_simple_merge/src/ops_mpi.cpp
- tasks/seq/yasakova_t_quick_sort_with_simple_merge/func_tests/main.cpp
- tasks/seq/yasakova_t_quick_sort_with_simple_merge/include/ops_seq.hpp
- tasks/seq/yasakova_t_quick_sort_with_simple_merge/perf_tests/main.cpp
- tasks/seq/yasakova_t_quick_sort_with_simple_merge/src/ops_seq.cpp
Алгоритм включает в себя следующие основные этапы:
1. Декомпозиция данных:
Данные равномерно распределяются между процессами с помощью scatterv.
Каждый процесс сортирует свою часть данных с помощью итеративной быстрой сортировки.
2. Взаимодействие между рабочими процессами и мастером:
Рабочие процессы отправляют свои отсортированные элементы по одному мастеру.
Перед отправкой каждого элемента рабочий процесс ждет подтверждения от мастера.
Мастер-процесс использует минимальную кучу для эффективного слияния данных, поступающих от рабочих процессов.
На каждом шаге мастер извлекает наименьший элемент из кучи, добавляет его в результирующий массив и запрашивает следующий элемент у соответствующего рабочего процесса.
3.  Синхронизация и сбор результатов:
Функция merge_func вызывает …
> Ясакова Татьяна. Задача 3. Вариант 14. Быстрая сортировка с простым слиянием.

- tasks/mpi/shpynov_n_mismatched_characters_amount/func_tests/main.cpp
- tasks/mpi/shpynov_n_mismatched_characters_amount/include/mismatched_numbers_mpi.hpp
- tasks/mpi/shpynov_n_mismatched_characters_amount/perf_tests/main.cpp
- tasks/mpi/shpynov_n_mismatched_characters_amount/src/mismatched_numbers_mpi.cpp
- tasks/seq/shpynov_n_mismatched_characters_amount/func_tests/main.cpp
- tasks/seq/shpynov_n_mismatched_characters_amount/include/mismatched_numbers.hpp
- tasks/seq/shpynov_n_mismatched_characters_amount/perf_tests/main.cpp
- tasks/seq/shpynov_n_mismatched_characters_amount/src/mismatched_numbers.cpp
На вход приходят две строки. Обе обходятся параллельно. Каждый n элемент одной строки сравнивается с n элементом второй, если они не совпадают, увеличиваем счетчик на 1. В конце прибавляем к счетчику разницу в длинах строк. Это те элементы, которые есть только в более длинной строке, они точно не совпадают.
В параллельной реализации обе строки делятся на количество потоков по формуле:
```
(длина части строки, передаваемой потоку (в коде - delta)) = (количество элементов наименьшей строки) / (количество потоков)
```
или
(длина части строки, передаваемой потоку (в коде - delta)) = (количество элементов наименьшей строки) / (количество потоков) + 1
Если длина наименьшей строки некратна количеству потоков.
В таком случае последний поток получит меньше данных на обработку, чем остальные, но …
> Шпынов Никита. Задача 1. Вариант 27. Подсчет числа несовпадающих символов двух строк

- tasks/mpi/leontev_n_image_enhancement/func_tests/main.cpp
- tasks/mpi/leontev_n_image_enhancement/include/ops_mpi.hpp
- tasks/mpi/leontev_n_image_enhancement/perf_tests/main.cpp
- tasks/mpi/leontev_n_image_enhancement/src/ops_mpi.cpp
- tasks/mpi/leontev_n_vector_sum/func_tests/main.cpp
- tasks/mpi/leontev_n_vector_sum/include/ops_mpi.hpp
- tasks/mpi/leontev_n_vector_sum/perf_tests/main.cpp
- tasks/mpi/leontev_n_vector_sum/src/ops_mpi.cpp
- tasks/seq/leontev_n_image_enhancement/func_tests/main.cpp
- tasks/seq/leontev_n_image_enhancement/include/ops_seq.hpp
- tasks/seq/leontev_n_image_enhancement/perf_tests/main.cpp
- tasks/seq/leontev_n_image_enhancement/src/ops_seq.cpp
- tasks/seq/leontev_n_vector_sum/func_tests/main.cpp
- tasks/seq/leontev_n_vector_sum/include/ops_seq.hpp
- tasks/seq/leontev_n_vector_sum/perf_tests/main.cpp
- tasks/seq/leontev_n_vector_sum/src/ops_seq.cpp
Последовательная реализация:
Преобразуем изображение в вектор, затем для каждого пикселя вычислим его яркость по формуле среднего арифм. (R+G+B)/3. Линейным растяжением получим новую яркость для каждого пикселя. Результирующий вектор - вектор с повышенным контрастом.
MPI реализация:
Разделим все пиксели на N, где N - число процессов. Остаток распределим между процессами, используется broadcast, all_reduce, gatherv, scatterv. Далее используется алгоритм из посл. реализации.
> Леонтьев Никита. Задача 3. Вариант 30. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы

- tasks/mpi/gromov_a_convex_hull/func_tests/main.cpp
- tasks/mpi/gromov_a_convex_hull/include/ops_mpi.hpp
- tasks/mpi/gromov_a_convex_hull/perf_tests/main.cpp
- tasks/mpi/gromov_a_convex_hull/src/ops_mpi.cpp
- tasks/seq/gromov_a_convex_hull/func_tests/main.cpp
- tasks/seq/gromov_a_convex_hull/include/ops_seq.hpp
- tasks/seq/gromov_a_convex_hull/perf_tests/main.cpp
- tasks/seq/gromov_a_convex_hull/src/ops_seq.cpp
> [Fix Revert] Громов Алексей. Задача 3. Вариант 32. Построение выпуклой оболочки для компонент бинарного изображения.
